### ISSUE TITLE
Parabolic SAR transition verification

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#1031]
Here is a side by side comparison of Skender 2.4.10 PSAR and TV PSAR.  It seems that the numbers are very close for a good while, then there are groups of 20 or so quotes that are wildly off for some reason: 

[TradingViewAndSkenderPsar_Point2_Point2_Point2.csv](https://github.com/DaveSkender/Stock.Indicators/files/10780854/TradingViewAndSkenderPsar_Point2_Point2_Point2.csv)

![image](https://user-images.githubusercontent.com/8295183/220040249-1a7acdb4-99d2-40f1-a6b7-67f173805ab5.png)

_Originally posted by @tanolan in https://github.com/DaveSkender/Stock.Indicators/discussions/1029#discussioncomment-5047157_

**Comment by DaveSkender** [comment]
That odd 13 price may not be handled well by TV. When transitioning to a downward trend, the new point should start at the last high extreme, so I suspect there’s an error in the TV one.

**Comment by tanolan** [comment]
Thanks @DaveSkender.  If you are going to try and line it up (I feel like TradingView is  kind of the defacto standard for indicators, do you agree?), would you create a new method like PsarExperimental or maybe add an overload parameter for the different style PSAR?  I've seen other libraries do this specifically for PSAR, one of the TALib ones calls the second method PsarExperimental.

**Comment by DaveSkender** [comment]
No, I have no intention of "matching" any other system.  I only seek to understand and explain, and possibly make improvements to this library if there is an error when compared to the [original reputable author](https://github.com/DaveSkender/Stock.Indicators/discussions/1024)'s intent.  We never copy or use someone else's code and implementation approach as a basis for correctness.

**Comment by DaveSkender** [comment]
Visualizing the data here to explain better, the purple dots are this library, squares are what you're showing for TradingView (TV).  The green dots represent what the SAR point would have been if a transition did not occur; they also represent a transitional reversal in direction.  Anytime the SAR crosses between the gray lines, a reversal and reset of the SAR should occur.

On 6/21 TV transitions correctly, but re-reverses incorrectly on 6/22 without crossing the new SAR threshold.  The only reason that would happen is if they're double-evaluating the directional SAR in the prior period based on the new SAR (a bug in their implementation).  The next correct transition is on 6/28.

![psar-chart](https://user-images.githubusercontent.com/8432125/220207310-76243a7f-924f-4ddd-81eb-672ffcfc3eb3.png)

**Comment by DaveSkender** [comment]
Another example of the 2-day rule not being implemented correctly in TradingView:

- https://github.com/DaveSkender/Stock.Indicators/issues/1226#issuecomment-2254297073
