### ISSUE TITLE
AlphaTrend indicator

### ISSUE THREAD

**Issue by giraygokirmak** [DaveSkender/Stock.Indicators#1041]
There's a good indicator superior to SuperTrend called Alphatrend.

Could you please consider including it?

Here is the pinescript source code:

https://www.tradingview.com/script/o50NYLAZ-AlphaTrend/

**Comment by DaveSkender** [comment]
I'll track this in our discussions.  We generally don't include community-contributed indicators since we can't [vet their quality or reputation](https://github.com/DaveSkender/Stock.Indicators/discussions/1024). Please have a look at #779 for a discussion on this indicator.
