### ISSUE TITLE
Rsi results seems to be wrong

### ISSUE THREAD

**Issue by Callightman** [DaveSkender/Stock.Indicators#1076]
I am getting ohlc data using yahoofinance api and then calculate the rsi but results are wrong.

I checked with tradingview rsi values and i also used other nuget packages (NetTrader.Indicator) to double check but for example as for AKBNK it calculates rsi value of 63 but in fact it is 67. And i have checked it with all stocks.

The version i use is 2.4.10

Thanks on advance

**Comment by DaveSkender** [comment]
Check to make sure you're using enough historical data to exceed the normal [warmup and convergence](https://github.com/DaveSkender/Stock.Indicators/discussions/688) periods for [Relative Strength Index (RSI)](https://dotnet.stockindicators.dev/indicators/Rsi/#response).  It's a [common problem](https://github.com/DaveSkender/Stock.Indicators/discussions/801) that is misunderstood that can be extra frustrating when comparing to other potentially faulty platforms.

> **Warning**
> For RSI, the first `10×N` periods will have decreasing magnitude, convergence-related precision errors that can be as high as ~5% deviation in indicator values for earlier periods.

Review this additional information and see if it can explain what you're seeing.  If you still believe there's something wrong with this library, please provide more specific information to allow us to narrow down the source or to reproduce the error.

**Comment by Callightman** [comment]
Sorry for misunderstanding i did not mean to compare you with other libraries it was just to double check. 

I am sure there is enough historical data as i have tried remove warmup periods which did not have any effect. 
With the attached file when i use getrsi it calculates rsi as "52.5963803620636" . Close is the last coloumn.


[aksen.csv](https://github.com/DaveSkender/Stock.Indicators/files/12244634/aksen.csv)

And here are the results from other sources. It should be 56. 

![aksen](https://github.com/DaveSkender/Stock.Indicators/assets/26795611/1fe8ff4f-9713-4913-807e-b81d46a7953a)

![aksent](https://github.com/DaveSkender/Stock.Indicators/assets/26795611/1a09f24d-eb92-4d20-af6a-8e41a428c27c)

![aksenf](https://github.com/DaveSkender/Stock.Indicators/assets/26795611/b1144c82-3a49-49e3-ab8a-3c3a8a72e1ed)

**Comment by DaveSkender** [comment]
Oh, it’s a good idea to compare to other libraries, it’s really your only way to double check that everything’s okay.  Some are not good sources of truth, is the only point I was making.

My guess is that there’s a slight variance between the data sources you’re comparing.  Are you able to get the raw data from each of these sources to compare equivalency?  Some of them may use dividend adjusted prices, Yahoo might have a separate adjusted price too.

**Comment by Callightman** [comment]
After getting raw data from tw problem seems to be with the Yahoo adjusted data. Thanks for your help
