### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [DaveSkender/Stock.Indicators#1082]
Maybe You will be interested in hosting API Explorer online:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/skender-stock-indicators/api/Skender.Stock.Indicators.html)

https://www.robiniadocs.com/d/skender-stock-indicators/api/Skender.Stock.Indicators.html

**Comment by DaveSkender** [comment]
I’ll check it out.  Thanks for sharing.
I’ll have to decide how much more work I’ll want to put into docs.

We already have:

- https://dotnet.stockindicators.dev
- native inline IDE XML-based docs
- https://www.fuget.org/packages/Skender.Stock.Indicators

**Comment by DaveSkender** [comment]
@NeuroXiq I haven’t read your own docs yet, is your site essentially just extracting the *public* interfaces and related [inline XML comments](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/)?  Maybe I’d just need to cleanup and fill some gaps in my own (2nd bullet) this can work without an real extra special effort?

**Comment by NeuroXiq** [comment]
`your site essentially just extracting the public interfaces and related [inline XML comments](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/)`
Yes
`Maybe I’d just need to cleanup and fill some gaps in my own (2nd bullet) this can work without an real extra special effort?`
Not sure what You mean.

You can think of RobiniaDocs as something similar to fuget.org but RobiniaDocs uses docfx generator.\
If project does not have any API explorer online,  point of using RobiniaDocs is:
1. Login to https://www.robiniadocs.com
2. Create a new projects and fill 'nuget package name' or upload .dll and .xml files
3. Go to project and click 'Rebuild'

Docfx documentation is hosted online and it took 1 minute to host. My first comment is example of this :)

This is ready-to-go, so above link can be added to README for other people to see it.
Or using ready shields.io badge:


```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/skender-stock-indicators/api/Skender.Stock.Indicators.html)
```

https://github.com/NeuroXiq/RobiniaDocs

**Comment by DaveSkender** [comment]
To be honest, I don't use either fuget.org or anything like this, really. 
When I'm in my developer IDE, I usually just use the "see definition" feature.

**I do see some benefits and like where you're headed** with the site, but you'll have to make it effortless for the same reason you're building it - we're lazy developers who don't want to do a lot of extra work on documentation, like manually uploading DLLs.  Here's a few things for your backlog to help me skip the part where I have to find, extract, upload and rebuild with every change to my DLLs:

- Auto-extract DLL from NuGet.org after subscribing to your site.

   I'd like to set it and forget it, so after initial subscription is setup on your site, it should automatically get and rebuild after a new version is published on NuGet.org.  Side benefit: you might be able to find and present even more information from the `.nupkg` file too (or `snupkg` if also published).  They're just ZIP files, FYI.
- Build a GitHub Action that'll work to rebuild your site from my continuous delivery pipeline.
- Generate my own site, like the build model from Swagger and other Open API standards

Do some of these enablers and keep refining the site styles and mobile views a bit more and I think you'll get more traction.  Next phase after that, go big on further enriched information, so you can move past regurgitating the cold code API.

Making it easier to provide more contextual and helpful written narrative explanations of those APIs could be a real differentiator.  Maybe someday an AI will write those things? 😺 

I'm not going to mess with this now, but if you need someone to test out how well various [inline XML documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/) looks when regenerated in your site, let me know.
