### ISSUE TITLE
Changing Volume type from long to decimal

### ISSUE THREAD

**Issue by ikorman** [DaveSkender/Stock.Indicators#110]
Hi

Is it possible to change inside Quote type of Volume from long to decimal? I know that for stocks long is fine, but when you are trading for example with crypto currencies volume is decimal number (as for example you can buy 0,00125 bitcoins).

Thank you
Ivan

**Comment by DaveSkender** [comment]
I think that change would be okay.  Decimal will support sufficiently large numbers as well.

**Comment by ikorman** [comment]
That would be great, thank you.

Here also one small suggestion: on couple of places you are using CultureInfo("en-US", false) - is it possible to make those properties public in order to adjust to local needs? I noticed it when I was cleaning history data and exception was thrown and had to figure out what was date behind exception text (as I'm from country where usual notation is dd.MM.yyyy). It's just cosmetic as it does not influence calculations.

Ivan

**Comment by DaveSkender** [comment]
this change was implemented in v0.10.10
