### ISSUE TITLE
Forward Curve for CoT Trading

### ISSUE THREAD

**Issue by endeffects** [DaveSkender/Stock.Indicators#1103]
I'm looking for an indicator to display the forward curve of commodities like available on trading view:

https://www.tradingview.com/symbols/NYMEX-CL1%21/forward-curve/

Is this included in your library under an other name or will it be possible to add such indicator?

**Comment by DaveSkender** [comment]
This isn't an indicator.  It's just a plot of current [crude oil price futures](https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.quotes.html).  Checkout the Chicago Mercantile Exchange (CME) [data feed options](https://www.cmegroup.com/market-data).
