### ISSUE TITLE
How to calculate a stream

### ISSUE THREAD

**Issue by MhAllan** [DaveSkender/Stock.Indicators#1106]
Hi, is there any reference on how do I calculate a stream? I see there is preview version but I can't see code or docs!

**Comment by DaveSkender** [comment]
There's not much documentation yet as we're still working through the basic model for how this will work; however, you can get the [basic syntax in our preview tracking discussion](https://github.com/DaveSkender/Stock.Indicators/discussions/1018#discussioncomment-4878084) (subscribe to follow) and in a simple [downloadable example](https://dotnet.stockindicators.dev/examples/#content).  Note at this time, the preview is limited any will only track a set of streamed `quotes` and used with EMA or SMA indicators.  We'll expand to all indicators once we have a core concept stabilized.
