### ISSUE TITLE
Can't seem to matchup the SuperTrend or ATR results with the results showing on chart.

### ISSUE THREAD

**Issue by TBOpen** [DaveSkender/Stock.Indicators#1118]
There were some indicators in this package that didn't exist in the QuanTower API.  I decided to look in to them to see if I could match up what I see in their charts.   I tried SuperTrend (10, 3) and the results just wouldn't match, and it was way to close to the bars, even increasing the multiplier didn't do much.   It sure looked like it may be the ATR.   So I ran a test on that and sure enough, I see the ATR (10) barely moving even with large swings.   I was using June 5, 2023 data, 1 min period, the data consisted of the bars from midnight to the open (6.5 hrs - 390 periods).  Any ideas?

**Comment by DaveSkender** [comment]
I have no idea how they calculated it, but I do know that TradingView has some sort of error, based on [my prior analysis](https://github.com/DaveSkender/Stock.Indicators/issues/318#issuecomment-761232310).  Maybe they copied their bad code?

**Comment by DaveSkender** [comment]
If you’re still seeking support on this issue, please provide the underlying price `quotes` and any other information about your sources of comparison.  I’ll take a closer look.
