### ISSUE TITLE
Use native culture for dates in main library [exception messages]

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#112]
> Here also one small suggestion: on couple of places you are using CultureInfo("en-US", false) - is it possible to make those properties public in order to adjust to local needs? I noticed it when I was cleaning history data and exception was thrown and had to figure out what was date behind exception text (as I'm from country where usual notation is dd.MM.yyyy). It's just cosmetic as it does not influence calculations.

From #110

**Comment by DaveSkender** [comment]
I thought we only added culture info in unit tests since it uses static U.S. formatted dates (#76).  I'll check.  If it's used in the main library, that was a mistake.

**Comment by DaveSkender** [comment]
I see what's happening in the cleaner.   Since I've not Localized error messages, I default format their culture to English.  In the cleaner, I coincidentally include a date in the Exception error message, which would then convert to English format.

This would only happen if you had a duplicate date in your history and the mismatch culture would be purely cosmetic; though, I can see how this might cause confusion when troubleshooting.  I'll see if I can get it to keep the native culture format for the date.

**Comment by ikorman** [comment]
This was exactly how I have noticed it :)

Thx.
Ivan

**Comment by DaveSkender** [comment]
this change was implemented in v0.10.10
