### ISSUE TITLE
Fractal all nulls

### ISSUE THREAD

**Issue by MhAllan** [DaveSkender/Stock.Indicators#1132]
This code `quotes.GetFractal()` is always returning nulls

**Comment by DaveSkender** [comment]
> This code `quotes.GetFractal()` is always returning nulls

Can you provide a copy of your quotes, and the parameters you’re using if they are different from the default.

**Comment by DaveSkender** [comment]
@MhAllan I haven't heard back from you, so closing this issue.  Please let me know if you need further assistance on this matter.
