### ISSUE TITLE
RSI missing default param value when chainee

### ISSUE THREAD

**Issue by cyberprophet** [DaveSkender/Stock.Indicators#1133]
```C#
var result = quotes.GetObv().GetRsi();
```
Chaining is possible only when **obv** returns **IReusableResult**, but **ObvResult** is returned.

The same goes for other methods.

**Comment by DaveSkender** [comment]
> ```cs
> var result = quotes.GetObv().GetRsi();
> ```
> 
> Chaining is possible only when **obv** returns **IReusableResult**, but **ObvResult** is returned.
> 
> The same goes for other methods.

So there is a minor bug here, but it's not this.  We simply omitted the default value in the chainable RSI value.  Workaround is to simply add the default value yourself:

```csharp
// chained
IEnumerable<RsiResult> results = quotes
    .GetObv()
    .GetRsi(14);   //  <-- must provide value for RSI param
```

https://dotnetfiddle.net/mYKSJX

**Comment by DaveSkender** [comment]
To address your initial thought, _most_ of these results classes inherit the interface, which is why the concrete type behaves appropriately as a chainee.

https://github.com/DaveSkender/Stock.Indicators/blob/9016f9ef04e1d004c74ec7a4267895723b577079/src/m-r/Obv/Obv.Models.cs#L4
