### ISSUE TITLE
Ichimoko SenkouSpanA miscalculation

### ISSUE THREAD

**Issue by h-fathi** [DaveSkender/Stock.Indicators#1158]
Hi, I hope you are well

### the problem
I tested the Ichimoku cloud and noticed the problem of miscalculating SenkouSpanA.
In this way, SenkouSpanA always displays the value n-1

### my situation

- library version:  v2.5.0
- indicator and params: GetIchimoku()

```csharp
      var ichimokuResult = quotes.GetIchimoku(tenkanPeriods, kijunPeriods, senkouBPeriods);
      var lastIchimoku = ichimokuResult.Last();
      lastIchimoku.SenkouSpanA equal with tradingview lastIchimoku.SenkouSpanA - 1

```

**Comment by DaveSkender** [comment]
Other than comparing to TradingView, do you have any additional information that can help us identify the problem.  We can’t go on faith that TradingView is an accurate source of truth.  Ref:

- #801

**Comment by DaveSkender** [comment]
I’ll check the math to see if `n` looks right.

**Comment by DaveSkender** [comment]
The default should set it 26 periods ahead.  Do you have both outputs to share?

**Comment by DaveSkender** [comment]
Looks like I’ve already done this analysis and concluded that TradingView is incorrect.

- https://github.com/DaveSkender/Stock.Indicators/discussions/251#discussioncomment-5894003

**Comment by h-fathi** [comment]
> Looks like I’ve already done this analysis and concluded that TradingView is incorrect.
> 
> * [Ichimoku Cloud (aka Ichimoku Kinkō Hyō) #251 (reply in thread)](https://github.com/DaveSkender/Stock.Indicators/discussions/251#discussioncomment-5894003)

Hi, thanks for your response. When I setting chikouOffset to 25, the problem was solved.

`var results = quotes.GetIchimoku(9,26,52,26,25);`

But is it true that the performance of the method is different from the TradingView Ichimoku indicator?
