### ISSUE TITLE
GetEma return NULL

### ISSUE THREAD

**Issue by MSLight** [DaveSkender/Stock.Indicators#1160]
This is my custom indicator class.

I applied the GetHeikinAshi function to my quotes, successfully obtaining Heikin-Ashi values. Subsequently, I aim to calculate the Exponential Moving Average (EMA) twice based on the close values derived from each Heikin-Ashi result. To achieve this, I utilized the GetEma function with a specific length parameter.

**However, I encountered an issue where the list of results contains NULL values for all instances of EMA, which is stored in the preEmaClose variable.**

If I directly calculate EMA on my quotes (without using GetHeikinAshi) it return result without problem.

How Can I solve the problem?

```
public static class CustomIndicator
    {
        public static List<ShaResult> GetSmoothedHa<TQuote>(
            this IEnumerable<TQuote> quotes,
            int preSmoothLength,
            int postSmoothLength)
            where TQuote : IQuote
        {
            var listQuotes = quotes.ToSortedCollection();
            List<ShaResult> results = new();

            var ha = listQuotes.GetHeikinAshi();

            var preEmaClose = haQuotes.GetEma(preSmoothLength);
            var postEmaClose = preEmaClose.GetEma(postSmoothLength);
            
            .
            .
            .

            return results;
        }
    }
```

**Comment by DaveSkender** [comment]
@MSLight have you overcome your problems here?  If so, please close this issue or let us know how we can help.
