### ISSUE TITLE
Native support of Pandas DataFrame?

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#1166]
We've seen several Python users get frustrated over issues related to converting quotes from Pandas [DataFrame](https://pandas.pydata.org/docs/reference/frame.html) into _iterable_ quotes.  Are there opportunities to add a native strongly typed DataFrame interface implementation to the .NET library?  I'm assuming this might then enable better interface design for our Python implementation.

Some paths to explore:

1. improve existing Python `stock-indicators` package code to be more resilient or to provide enhanced error handling / messages
2. improve [documentation website](https://python.stockindicators.dev) by either / or:
    - a dedicated page for Pandas DataFrame users
    - add full downloadable _example usage_ code, like the [Stock Indicators for .NET | Examples](https://dotnet.stockindicators.dev/examples)
3. the mentioned native [implementation of .NET DataFrame](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.analysis.dataframe)

For now, to help users, I've started a specific support discussion on the topic, including a list of reported examples.

- https://github.com/DaveSkender/Stock.Indicators/discussions/1165

cc: @LeeDongGeon1996

**Comment by LeeDongGeon1996** [comment]
About `1`, do we need to provide helper method for converting into Iterable[Quote]?

**Comment by DaveSkender** [comment]
> Looks like `2` is almost done :) About `1`, how do you think about providing helper method for converting into Iterable[Quote]?

I think what you've done with Exception handling might be enough; unless you can think of some better utility method that'd work better.  Right now they have to do some custom transform with a number of methods using `zip()` or `numpy.vectorize()` or `iterrows()` with code like:

```python
quotes_list = [
    Quote(d,o,h,l,c,v) 
    for d,o,h,l,c,v 
    in zip(df['date'], df['open'], df['high'], df['low'], df['close'], df['volume'])
]
```
A utility would have more validation and error handling and be in a much simpler interface, like:

```python
quotes = df.ToQuotes(d,o,h,l,c.v);
```
or 
```python
quotes = df_to_quotes(df['date'], df['open'], df['high'], df['low'], df['close'], df['volume']);
```

**Comment by DaveSkender** [comment]
For this issue, I’m not sure where to go at this point.  The [example usage](https://python.stockindicators.dev/guide/#using-pandasdataframe) we’ve given so far somewhat explain how to use a DataFrame, maybe that’s enough?

**Comment by LeeDongGeon1996** [comment]
@DaveSkender 
I also think that what we've done for dealing with `DataFrame` is enough. Most of cases were the problem of what the beginners are usually struggled with (except for `locale` issue). So now let's just see how it goes.
