### ISSUE TITLE
Connors RSI accuracy (during warmup periods)

### ISSUE THREAD

**Issue by hmuhdkamran** [DaveSkender/Stock.Indicators#1169]
### the problem

I am using Stock.Indicators to calculate [Connors RSI](https://dotnet.stockindicators.dev/indicators/ConnorsRsi/#content), but never been able to get the accurate or near to accurate value, just do the following steps and you will understand

### steps to reproduce

goto https://scstrade.com/TechnicalAnalysis/TA_RealTimeCharting.aspx and select PTC, and select indicator Connor RSI, then  get the data from https://dps.psx.com.pk/historical of PTC, and use Connors RSI over it with default valus 3, 2, 100. you will understand. the gape is quite huge.

**Comment by DaveSkender** [comment]
> ### the problem
> I am using Stock.Indicators to calculate Connors RSI, but never been able to get the accurate or near to accurate value, just do the following steps and you will understand
> 
> ### steps to reproduce
> goto https://scstrade.com/TechnicalAnalysis/TA_RealTimeCharting.aspx and select PTC, and select indicator Connor RSI, then get the data from https://dps.psx.com.pk/historical of PTC, and use Connors RSI over it with default valus 3, 2, 100. you will understand. the gape is quite huge.

Thank you for reporting. :heart: I'm not sure yet why there's a difference, but will dig in deeper when I have more time.  We like to double-check for accuracy.

Some initial thoughts:

- I see this website is using _TradingView_ charts.  I have a running list of examples of related problems worth reviewing: #801.  This one is not on the list (yet).
- Like most of our indicators, our Connors RSI formula is sourced from the _[original authors publication](https://alvarezquanttrading.com/wp-content/uploads/2016/05/ConnorsRSIGuidebook.pdf)_, which may not be the case for TradingView -- they have a history of simply re-using [unverified community indicators](https://www.tradingview.com/scripts/connorsrsi/).
- Anecdotally, when we double-check formulas, we usually find that the problem is with the third-party software.  Since I've not looked at this one in a while, I'll dig deeper to document my findings.

**Comment by DaveSkender** [comment]
Doing a quick comparison here from my demo site; they visually look the same to me.  Both are using daily QQQ quotes.  Can you _show more_ of what you're seeing?

## Demo site - [charts.stockindicators.dev](https://charts.stockindicators.dev)

![image](https://github.com/DaveSkender/Stock.Indicators/assets/8432125/c0398364-56ef-4342-8648-9ea6e8231348)

Note: uses the [v2.5.0 package](https://www.nuget.org/packages/Skender.Stock.Indicators/2.5.0#readme-body-tab)

## TradingView - [tradingview.com/chart/ErfRNj6y](https://www.tradingview.com/chart/ErfRNj6y/?symbol=QQQ)

![image](https://github.com/DaveSkender/Stock.Indicators/assets/8432125/5082744d-b81d-4130-93d2-ad30cb8ea3cb)

**Comment by hmuhdkamran** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators/assets/28337118/3d436684-c0a6-4276-a081-6bedcea2fb60)

` def apply_connors_rsi(self, quotes, df, rsi_periods=3, streak_periods=2, rank_periods=100):
        # Calculate SuperTrend and handle returned data
        results = indicators.get_connors_rsi(quotes, rsi_periods, streak_periods, rank_periods)

        df_temp = pd.DataFrame({
                'rsi_close': [float(result.rsi_close) if result.rsi_close is not None else None for result in results],
                'rsi_streak': [float(result.rsi_streak) if result.rsi_streak is not None else None for result in results],
                'percent_rank': [float(result.percent_rank) if result.percent_rank is not None else None for result in results],
                'connors_rsi': [float(result.connors_rsi) if result.connors_rsi is not None else None for result in results],
            })
        
        return pd.concat([df, df_temp], axis=1) `

There is quite the difference.

**Comment by DaveSkender** [comment]
I’ll  analyze further if you can upload the raw unaltered quotes that you’re using in this example.  If you want to analyze yourself, you can compare what you’re seeing with manual calculations by putting your raw quotes into our [manual calculation spreadsheet](https://github.com/DaveSkender/Stock.Indicators/blob/2985a242a0a8c740ce3f1b527fa1e01a4185df03/tests/indicators/a-d/ConnorsRsi/ConnorsRsi.Calc.xlsx).

**Comment by hmuhdkamran** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators/assets/28337118/e8943e1a-a66c-495c-aeec-77565339407b)
[data.csv](https://github.com/DaveSkender/Stock.Indicators/files/14483481/data.csv)

I have shared image with data

**Comment by DaveSkender** [comment]
This doesn't answer the question we're seeking, but one quick observation here is that you're probably showing the `Rsi` field here instead of the `ConnorsRsi` field from the results.

<img width="756" alt="image" src="https://github.com/DaveSkender/Stock.Indicators/assets/8432125/1a957bc9-36bd-43aa-94f3-304ca9e454b1">

```csharp
// ConnorsRsiResult
public double? Rsi { ... }         // --> showing this one
public double? RsiStreak { ... }
public double? PercentRank { ... }
public double? ConnorsRsi { ... }  // <-- instead of this one
```

**Comment by hmuhdkamran** [comment]
I am sharing the code, you will now understand
```
def apply_connors_rsi(self, quotes, df, rsi_periods=3, streak_periods=2, rank_periods=100):
        # Calculate SuperTrend and handle returned data
        results = indicators.get_connors_rsi(quotes, rsi_periods, streak_periods, rank_periods)

        df_temp = pd.DataFrame({
                'rsi_close': [float(result.rsi_close) if result.rsi_close is not None else None for result in results],
                'rsi_streak': [float(result.rsi_streak) if result.rsi_streak is not None else None for result in results],
                'percent_rank': [float(result.percent_rank) if result.percent_rank is not None else None for result in results],
                'connors_rsi': [float(result.connors_rsi) if result.connors_rsi is not None else None for result in results],
            })
        
        return pd.concat([df, df_temp], axis=1)
```

    rsi_close  rsi_streak percent_rank connors_rsi
0         NaN         NaN         None        None
1         NaN         NaN         None        None
2         NaN         NaN         None        None
3   95.575221         NaN         None        None
4   77.978339         NaN         None        None
..        ...         ...          ...         ...
95  90.200257   60.569297         None        None
96  67.784504   46.311620         None        None
97  82.153815   51.396506         None        None
98  72.300096   46.502803         None        None
99  83.737490   51.621015         None        None

**Comment by hmuhdkamran** [comment]
Thanks man, Found my error, I was getting and calculating on 100 records, when I increase the size to 500, it get fixed, I am very happy and appreciate the help you put on explaining and fixing.

**Comment by DaveSkender** [comment]
This is a very common issue with the warmup and convergence periods.  I've done the math on indicators that require more history.  This section in the documentation (example below) will help you determine approximately how much you'll need; and it varies for different indicators.  You should be okay with ~200-250 periods here.

<img width="637" alt="image" src="https://github.com/DaveSkender/Stock.Indicators/assets/8432125/b305caea-f7e3-48e2-82fa-042fbb688c46">
