### ISSUE TITLE
Last entry in bollinger bands is partially filled

### ISSUE THREAD

**Issue by MightyPowerNuke** [DaveSkender/Stock.Indicators#1193]
### the problem

Bollinger Bands sometimes has last or last couple elements of the result being partially filled, like so:

quotes.GetBollingerBands(5, 2).Last()
{Skender.Stock.Indicators.BollingerBandsResult}
    Date: {23/04/2024 19:00:00}
    LowerBand: 2.565
    PercentB: null
    Sma: 2.565
    UpperBand: 2.565
    Width: 0
    ZScore: null

quotes.GetBollingerBands(5, 2).Reverse().ToArray()[2]
{Skender.Stock.Indicators.BollingerBandsResult}
    Date: {23/04/2024 18:30:00}
    LowerBand: 2.565
    PercentB: null
    Sma: 2.565
    UpperBand: 2.565
    Width: 0
    ZScore: null

quotes.GetBollingerBands(5, 2).Reverse().ToArray()[3]
{Skender.Stock.Indicators.BollingerBandsResult}
    Date: {23/04/2024 18:15:00}
    LowerBand: 2.562
    PercentB: 0.37500000000001388
    Sma: 2.566
    UpperBand: 2.57
    Width: 0.0031176929072486391
    ZScore: -0.49999999999995554

### my situation

- library version: 2.5.0
- indicator and params: GetBollingerBands(lookbackPeriods: 5, standardDeviation: 2)
- with these quotes: attached as file

```csharp
// my code
double bollingerZScore = quotes.GetBollingerBands(5, 2).Last().ZScore ?? throw new ArgumentException(ExceptionMessage_InsufficientNumberOfQuotes);
```

### steps to reproduce

Stock BTG in time interval: 2024-01-24 19:00 to 2024-04-23 19:00 with lookbackPeriods = 5, standardDeviations = 2. Attached the exact quotes as CSV.

Error message(s) or maleficent outcome:
ZScore, PercentB is null.
[dump.csv](https://github.com/DaveSkender/Stock.Indicators/files/15193657/dump.csv)

**Comment by DaveSkender** [comment]
Interesting.  Rare find, thank you.  I’ll take a closer look.

Hypothesis: over that 5 period span, you get a standard deviation of `0`, so those values are incalculable (infinity value).

**Comment by DaveSkender** [comment]
### findings

I've done some manual calculation here to confirm my initial thought and have concluded that this falls into the _it's not a bug, it's a feature_ category.  :neckbeard:

If you look at the close prices for the 5 periods included in each incremental calculation, you'll see that the price does not vary -- there's no standard deviation.  In this case, %B and Z-Score can't be calculated without producing a divide-by-zero error, so returning `null` here, to indicate an _incalculable value_ is the only viable outcome.

![image](https://github.com/DaveSkender/Stock.Indicators/assets/8432125/cd7e312c-b6a5-456d-9b7b-a87ea6e3b193)

With that said, if you prefer `NaN` values over `null`, the library has a [`.Null2NaN()` extension utility](https://dotnet.stockindicators.dev/utilities/#nullmath) that'll convert them for you.

ref: 
[1193-BollingerBands-null-values.xlsx](https://github.com/DaveSkender/Stock.Indicators/files/15196437/1193-BollingerBands-null-values.xlsx)
