### ISSUE TITLE
GetDonchian off by one time period

### ISSUE THREAD

**Issue by pgrimstrup** [DaveSkender/Stock.Indicators#1195]
### the problem

Using the GetDonchian method to calculate Donchian Channels appears to be off by one time period. The new high/low is shown on the candle that is _after_ the candle that triggered the new high/low.

Interestingly, the sample image on the Donchian Indicator page also shows this behavior. 
https://dotnet.stockindicators.dev/indicators/Donchian/#content

Checking the code, there appears to be an off-by-one error with the inner-loop calculation. 
The condition is currently
```csharp
                    for (int j = i - lookbackPeriods; j < i; j++)
```

The condition should be (as it should include the current time period in the high/low calculation)
```csharp
                    for (int j = i - lookbackPeriods + 1; j <= i; j++)
```

Correcting this appears to fix the problem, and new high/lows now begin on the correct candle.

> Please determine if other charting platforms are accurate before comparing to this library.  We're unable to debug their problems for you.

Yes - comparing against Donchian Channel usage on TradingView where new high/lows start on the candle, not after it.

### my situation

- library version: 3.0.0-preview1014-0025
- indicator and params: GetDonchian(20)
- with these quotes: any set of IQuote data

### workaround
Implemented my own GetDonchian for now. Looking forward to an update.

**Comment by DaveSkender** [comment]
@pgrimstrup any change in your perspective after reviewing my previous analyses here?  I’d concluded that the TradingView author didn’t implement it in accordance with the original authors intent; and provided a few other reputable sources to back that up.

**Comment by DaveSkender** [comment]
@pgrimstrup, do you have any open issues here?
I don't believe there's an bug or issue with this library.

Please reopen if you disagree, or otherwise let us know how we can help.
