### ISSUE TITLE
Indicator classes as sealed? Why?

### ISSUE THREAD

**Issue by DanyLinuxoid** [DaveSkender/Stock.Indicators#1205]
Situation is not a bug, not a feature request, I just want a clarification.

I just had quite a portion of code based on BollingerBandResult and TemaResult classes, they were used as a base for a wrapper classes with additional fields and actual "core" logic.

Previous version was 1.21.1, used it for year+, but it had some inconsistencies and was missing some indicators/some of them were calculating stuff incorrectly (as I discovered later and that made my decision to update).

So, I updated to latest 2.5.0 and was eager to see improvements/changes/new things...
But instead I saw 100+ reference errors stating"cannot derive from sealed class"...

![изображение](https://github.com/DaveSkender/Stock.Indicators/assets/53906830/21947eeb-01df-4b0f-aa0a-6dec1fadee2c)
+ same for TemaResult

![изображение](https://github.com/DaveSkender/Stock.Indicators/assets/53906830/13c6608b-524a-482b-acfc-e427fc38c069)

Can you provide reasoning behind this? Why these were made sealed?

**Comment by DaveSkender** [comment]
When we added chaining, we had to map a primary `Value` property, which makes it uninheritable.  I didn’t love the tradeoff, but it was needed to ensure a consistent `IReusableResult` interface.

https://github.com/DaveSkender/Stock.Indicators/blob/a18129b44e9fc8e5b35c4644154524ed43347e32/src/e-k/Ema/Ema.Models.cs#L13

I’m exploring some alternatives in the next major version (v3).  I’m leaning towards `record struct` to better support streaming use cases that have more memory load, but am also exploring some base class types.  It’d still likely be uninheritable, but am not sure yet.

**Comment by DaveSkender** [comment]
If you have some ideas on how to handle these constraints in a different inheritance approach, I’m happy to take suggestions.  I may missed a more open, viable option.

**Comment by DanyLinuxoid** [comment]
Got it, thanks for quick response.
And no, unfortunately, no ideas on how to solve problem.

You can close this if needed.

**Comment by DaveSkender** [comment]
I’ll keep this in mind as I work on v3.  I did like the idea of letting users extend these without needing to re-write or transform to a new type, but just ran into some syntax limitations that I couldn’t get around.

**Comment by DaveSkender** [comment]
> I’ll keep this in mind as I work on v3. I did like the idea of letting users extend these without needing to re-write or transform to a new type, but just ran into some syntax limitations that I couldn’t get around.

Just an FYI, there's a good chance I'll be able to bring back inheritance in v3; but no promises, we're still early in the _beta testing lifecycle_ and things can change.  I'm hoping to release v3 sometime towards the end of the year after several more _preview_ iterations.
