### ISSUE TITLE
Parabolic SAR has any bugs

### ISSUE THREAD

**Issue by Sonovogod** [DaveSkender/Stock.Indicators#1226]
### What happened?

Hello, today I was watching my new strategy based on the SAR indicator and noticed that its work often differs from the same indicator on TraidingView with the same settings.

On TraidingView the indicator works correctly, shows a reversal on time, and does not intersect with the price 
On SAR In the indicator from the library, I noticed problems with reversals, not always, but very often, SAR notices a reversal with a delay of three candles, and until that moment it continues to draw levels, although they already intersect with the price.

Tested on a minute timeframe

**Comment by Sonovogod** [comment]
Here is an example, here you can see on the screen that a reversal occurred on the SAR indicator taken from Binance, but not yet on the SAR from the library, also if you look at the time 00:59 on the chart in Binance SAR there are dots above the price chart, while the SAR from the libraries are still downstairs

![1](https://github.com/user-attachments/assets/0a6029ae-ffa6-497c-a988-307882a501be)
![2](https://github.com/user-attachments/assets/cdacf4fb-b7da-4514-a3f7-4789ce3b45f6)
![3](https://github.com/user-attachments/assets/e3501a68-b0d5-43bb-9f25-388cd078ee01)

**Comment by DaveSkender** [comment]
Based on my analysis in #1031, you cannot get these to match since there are at least two observable bugs in the TradingView code.  In other words, _the TradingView version is incorrect_.  More info:

- #1031
- #801
