### ISSUE TITLE
Is TEMA working correctly?

### ISSUE THREAD

**Issue by DanyLinuxoid** [DaveSkender/Stock.Indicators#1269]
### What happened?

Using latest 2.5.1 version

From what I've seen and I've used, I know that TEMA requires 3x amount of candles required for median calculation, since it is triple "filtering".
I had this behavior back in the old versions and I remember seeing this in code as well while debugging.
I was using this indicator for like 6 months+, then I switched to SMA.
Now, after few months, I'm trying TEMA again, and I see this:
![image](https://github.com/user-attachments/assets/034c250e-b453-4761-a734-ee454b82f46e)

On image it is seen that indicator is already calculated after 100 candles, soo... is this actually correct behavior?

P.S: if issue is known or bug report is already created or I don't understand something - you can close bug yourself but before that please provide a reply.

### Code usage

```csharp
var median = quotes.GetTema(lookbackPeriods: strategy.QuickTrendLength).ToList();
```

**Comment by DaveSkender** [comment]
Let me know if this answers your question:
- https://github.com/DaveSkender/Stock.Indicators/discussions/808#discussioncomment-3553406

**Comment by DanyLinuxoid** [comment]
> Let me know if this answers your question:
> 
> * [Triple Exponential Moving Average (TEMA) #808 (comment)](https://github.com/DaveSkender/Stock.Indicators/discussions/808#discussioncomment-3553406)

Yep, got it.
Thank you

Closing
