### ISSUE TITLE
Add an option to control which type of MA should be used to calculate `SignalLine` of `MACD`

### ISSUE THREAD

**Issue by dehghani-mehdi** [DaveSkender/Stock.Indicators#1284]
### the problem

In MetaTrader, the signal line of MACD is calculated using SMA, I know the official formula uses the EMA, but I want the result of my code to be the same as MetaTrader's result. _of course I checked a few other platforms and all of them use SMA instead of EMA and I don't know why_

So, Could you add an option in order to control the type of MA for calculating the Signal line?

Of course for now I calculate the signal line using the `GetSma` method, and it works, but having the option in MACD itself would be nice.

**Comment by DaveSkender** [comment]
We've included a way to [make your own custom indicators](https://dotnet.stockindicators.dev/custom-indicators) specifically to address this situation where a user wants to do something in a non-standard way.

Generally speaking, we're rarely going to modify indicators away from _the original author's formula_.  We also don't view other platforms as a _source of truth_ for a number of reasons, so trying to match them isn't something we seek to do.
