### ISSUE TITLE
Req: Hull Moving Average

### ISSUE THREAD

**Issue by ikorman** [DaveSkender/Stock.Indicators#129]
Hi

Did you plan to add Hull Moving Average to your repository of indicators?

Thx
Ivan

**Comment by DaveSkender** [comment]
Already there: [GetHma](https://daveskender.github.io/Stock.Indicators/indicators/Hma/#content)

**Comment by ikorman** [comment]
Sorry, overlook on my side when I checed the source code

BR
Ivan
