### ISSUE TITLE
Error: Insufficient history provided for EMA

### ISSUE THREAD

**Issue by Eli-N** [DaveSkender/Stock.Indicators#157]
Hi guys
I want to use EMA with lookbackPeriod=101 but I got an error that says 
"
$exception | {"Insufficient history provided for EMA.  You provided 101 periods of history when at least 202 is required.  Since this uses a smoothing technique, for a lookback period of 101, we recommend you use at least 351 data points prior to the intended usage date for maximum precision."} | Skender.Stock.Indicators.BadHistoryException
"
P.S: If I set any lookbackPeriod but I got a similar error

**Comment by DaveSkender** [comment]
@Eli-N if you have a further inquiry I can reopen this issue.  I'm closing it for now as I believe this to be an end-user setup issue.
