### ISSUE TITLE
Please add TD sequential indicator.

### ISSUE THREAD

**Issue by M22arius494** [DaveSkender/Stock.Indicators#162]
Could you please add the TD sequential indicator?

https://www.investopedia.com/terms/d/demarkerindicator.asp

Thanks and regards,
Marius

**Comment by DaveSkender** [comment]
Do you have any public domain calculation of the TD Sequential® indicators?  I think the link you sent is a reference to the more traditional DeMarker indicator, which is something different.  If these are not public domain indicators, I may need to ask [DeMark Analytics](https://demark.com/demark-indicators) for permissions and update the repo license to limit it private non-commercial use before attempting to add these to the library.

**Comment by DaveSkender** [comment]
Due to the proprietary nature of this indicator, I don't think we'll be able to add this one; however, will keep it in mind if we ever want to change the licensing model to include such items.

**Comment by M22arius494** [comment]
Yeah, I understand after reading/caching up a bit on this indicator, no problem!
