### ISSUE TITLE
Average Directional Index seems to be slightly off

### ISSUE THREAD

**Issue by op1031** [DaveSkender/Stock.Indicators#173]
Hi Dave,

First, thank you for your contribution to this project. I am excited to find this time-saving project a couple of weeks ago.
The issue I am submitting has to do with Average Directional Index (ADX). I notice that it is somewhat off when I compare it with tradingview's ADX/DMI indicator.

For example, on 2000-11-27, the Skender ADX indicator shows 
ADX=30.1245
+DI=16.898
-DI=30.579

On the same day, TradingView indicator shows 
ADX=30.4113
+DI=16.9263
-DI=30.6871

Could you check if this is a bug? 

Thank you,

**Comment by DaveSkender** [comment]
I’ll take a look.  Are you able to confirm that the historical quote data used in both is the same?  Some providers will adjust slightly differently for splits and dividends, which would produce slightly different results.  Also, make sure you are providing at least 250 points of quote history prior to the measured date in the GetAdx call.  This algorithm uses a convergence method that increases in precision when more history is provided.

**Comment by DaveSkender** [comment]
I did find a minor bug with the initialization value that only had minor impacts on the initialization period values.  This bug did not impact the accuracy of values after the initialization period. I also increased the minimum required history from `2×N+1` to `2×N+150` to ensure users are aware of the initialization period where values are less precise and that this indicator needs more runway.

**Comment by DaveSkender** [comment]
This fix was implemented in v1.1.1

**Comment by op1031** [comment]
Hi Dave,

Thank you for the swift response and for taking the time to respond to my
concern. I think you are right about the data set. I got my quotes from
yahoo finance, and TradingView probably uses a different type of data
source.

Have a nice weekend,
Alex
