### ISSUE TITLE
Implement IQuote interface to expand utility of quote class

### ISSUE THREAD

**Issue by MithrilMan** [DaveSkender/Stock.Indicators#179]
I'm not going to criticize you work at all, it's cool that you put lot of effort in this project, I'm just offering some help if you want to talk about the design of the library and possible improvements both in memory and performance.

An example is about your Quote class, I think it's not a good idea to require a specific class because that way an user has to convert it's own models to Quote with problems both at performance level and design

A proper solution would be to use a IQuote interface, so that it's easy to adapt our own model because it's a matter of implementing that interface in our model without having to convert any object (most of the time our source model already contains close, high, low, date etc... so it's a no brainer to adapt)

Of course Quote class can still be there in the library for those that want to use that model.

Also the Index property is something not needed as I pointed out in a comment here https://github.com/DaveSkender/Stock.Indicators/issues/170#issuecomment-727620632

but even if needed, having a different interface like IIndexedQuote required only by indicators that need to manage an index would be enough (and if we want to adapt our model adding the index property, we can do that with explicit interface declaration so that our model will not be polluted externally)

If you are open to changes I can try to find some time to contribute and do some benchmark too

**Comment by DaveSkender** [comment]
Hey, I'm always looking for passionate people who want to contribute, either with feedback or more directly by helping, so, thank you for that.  I think you have some good ideas here, worth exploring.

**Comment by DaveSkender** [comment]
One of the key design decisions to keep in mind is that the `Quote` is the natural shape of historical data from pretty much all data feeds and sources; as such, I do not want to force users (developers) to do a lot of manipulation of data before using it in the library.  If I wanted to spend time coding data transformation and matching and rematching data after I get results, I'd use some of the other libraries out there, like Tulip or TA-Lib, which are very difficult to use IMHO.

**Comment by MithrilMan** [comment]
Sure, my main problem is time but I'll fork the repo and implement a couple of Indicators following my proposal to showcase
I'll keep you updated on this issue

**Comment by DaveSkender** [comment]
Thank you.  In the meantime, I'll take a look at removing the internal Index altogether.  It's something I've been interested in doing anyway.

**Comment by MithrilMan** [comment]
removing index will be really appreciated and will even solve the issue I opened from the root (about trimming date).

I think that removing index will mean even that you must expect data passed is already sorted by date and don't contains date duplication, but I think it's good because it has performance implication to do that inside your indicators
Expect the user to feed proper data is something you could set as requirement to users, I don't think that users should pay performance because of checks to try to fix bad usage (you can anyway have helpers for users to call and clean data as you have now)

**Comment by DaveSkender** [comment]
I'll probably do it in two steps.  1) remove the use of Index in indicator algorithms, then 2) address cleaning and pre-cleaning (figure out how to make it optional, but still available)

**Comment by MithrilMan** [comment]
I don't think that a library has to fix all bad usage problems because often this mean that you complicate your solution and a bad user will still find ways to misuse your library :)

Anyway if you want to have an automatic cleanup where possible, while leaving the chance to feed a sorted one, you can 
create an extension of `IEnumerable<IQuote>` (or quote atm)  called like "AsSortQuotes" that returns a
SortedQuotes result, where SortedQuotes is a class that implements `IEnumerable<IQuote>` (could just be a wrapper of IEnumerable<IQuote>) and in your indicators you check like
```
 if(!(historyData is SortedQuotes) {
   // perform data cleanup
}
```
so if someone call AsSorted he ensure he already did what he had to do to give you a proper data set

**Comment by DaveSkender** [comment]
Yah, I was thinking the same thing but wanted to take care of that in Step 2, after removing Index dependency in the indicators.  The sort is the biggest concern.  Other checks, like duplicate dates or for impossible values can probably be optional, but I'd like to provide the method for it so users don't have to roll their own.

**Comment by DaveSkender** [comment]
I’m going to merge the Index removal refactoring in the next few days.  I’ll hold off on the “AsSortQuotes” since that will depend on the contributions you may make.  You’ll probably want to wait for my merge before starting, to avoid a potentially large conflict resolution.

**Comment by MithrilMan** [comment]
I'm going to implement stuff this weekend, starting tonight probably

**Comment by DaveSkender** [comment]
Ok, cool.  There's a Benchmark.NET project already in there, in case you didn't notice.

**Comment by MithrilMan** [comment]
Yes that was the benchmark I was refering to, this is current branch perf on my pc
![image](https://user-images.githubusercontent.com/5107375/99875276-8647df00-2bee-11eb-9019-e7ff12aa1ce3.png)

**Comment by MithrilMan** [comment]
ok submitted the PR that implements IQuote making use of generics
#190

documentation should reflect changes once approved
I tried to be as less intrusive as possible code wise, just allow to use our own models instead of Quote, the rest is still the same

**Comment by DaveSkender** [comment]
This change is available in version 1.2.0

@MithrilMan thank you for your contributions.  Check out [the backlog](https://dev.azure.com/skender/Stock.Indicators/_boards/board/t/Stock.Indicators) if you're interested in tackling others.

**Comment by MithrilMan** [comment]
you are welcome
I don't have access to the backlog

**Comment by DaveSkender** [comment]
Oh, that's not good.  This backlog is supposed to be a public project.  Can you [DM me on Twitter](https://twitter.com/messages/compose?recipient_id=27475431) to troubleshoot?

**Comment by DaveSkender** [comment]
FYI.  I've moved the backlog to GitHub: https://github.com/DaveSkender/Stock.Indicators/projects/1
