### ISSUE TITLE
IQuote not found

### ISSUE THREAD

**Issue by Jenscaasen** [DaveSkender/Stock.Indicators#203]
Hi,
this page suggests to implement "IQuote" rather than creating a child object of Quote:
https://daveskender.github.io/Stock.Indicators/docs/GUIDE.html#using-custom-quote-classes

But no matter what i include, IQuote can not be resolved using the Nuget Package.

My goal here is to try out the performance of the Lib when using IQuote, as i currently loose a lot of processor time converting my custom Quote Class back to "Quote"
Do i miss a package?

**Comment by DaveSkender** [comment]
You cannot modify `IQuote` directly, rather you'd need to add it to your pre-existing class equivalent of `Quote`.  The code in your app should look something like this:
```
public class MyCustomQuote : IQuote
{
    // required base properties
    public DateTime Date { get; set; }
    public decimal Open { get; set; }
    public decimal High { get; set; }
    public decimal Low { get; set; }
    public decimal Close { get; set; }
    public decimal Volume { get; set; }

    // custom properties
    public int MyOtherProperty { get; set; }
}
```
If you're getting [CS2046 'IQuote' could not be found](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246), then I'd check to make sure you've specified -- and downloaded -- the latest version of the library in your project.
```
<ItemGroup>
    <PackageReference Include="Skender.Stock.Indicators" Version="1.3.0" />
</ItemGroup>
```

cc @MithrilMan, thoughts?
