### ISSUE TITLE
Request: Arnaud Legoux Moving Average (ALMA)

### ISSUE THREAD

**Issue by Dav-id** [DaveSkender/Stock.Indicators#204]
Hi Dave, 

Thanks, for this fantastic library you've created. Do you have any plans to add ALMA indicator to the library? 

Thanks!

**Comment by DaveSkender** [comment]
Thanks for suggesting.  I'll add this to the backlog.  I have KAMA and MAMA adaptive moving averages in the backlog as well and had previously implemented HMA, which is similar.

**Comment by DaveSkender** [comment]
This is now available in version 1.4.0
