### ISSUE TITLE
Add AROON Indicators?

### ISSUE THREAD

**Issue by GelLiNN** [DaveSkender/Stock.Indicators#23]
Would it be possible to add the AROON indicators (upper and lower) as a function in this library?
I would very much appreciate it :)

**Comment by DaveSkender** [comment]
Yes, I have this towards the top of the backlog, AB#498

**Comment by DaveSkender** [comment]
This is now available in #25

**Comment by GelLiNN** [comment]
Tested and verified - VERY much appreciated.
