### ISSUE TITLE
ADl, OBV values are not correcct.

### ISSUE THREAD

**Issue by vebollu** [DaveSkender/Stock.Indicators#319]
I'm using your nuget package from a month , it's been really good.  I have the following issues with the package.

1)  OnBalanceVolume Indicator.GetObv(history) is not match with stockcharts/tradingview obv value
2) Accumulation Distribution (ADL) Indicator.GetAdl(history) also not matching with the  stockcharts/tradingview Adl value

Suggestions:

Earlier we have properties IsReversal, Isrising, Isdiverging in MAcd, Rsi, PsarIsrising etc... can you please add those back if possible? can you please apply the same for aaron and others?

**Comment by DaveSkender** [comment]
I know OBV and ADL absolute values are based on a specific starting date and can be confusing if you're trying to compare absolute values.  Are your examples in StockCharts and TradingView the same?

**Comment by vebollu** [comment]
perfect. just compared obv values and adl values in tradingview, stock charts and alpha vintage. all these are having different values. Regarding the extra "analysis" values if you add a default parameter to the methods, who ever wants those values they will pass the value to that parameter. if you are okay please change otherwise it's still okay.

**Comment by DaveSkender** [comment]
I'll keep thinking about how to provide extended analysis values.  There are a few different ways to implement it.  Let's continue this discussion on #320
