### ISSUE TITLE
GetHistoryFromFeed("MSFT"); isn't being recognized

### ISSUE THREAD

**Issue by Jammooly1** [DaveSkender/Stock.Indicators#323]
using System;
using System.Collections.Generic;
using System.Linq;
using Skender.Stock.Indicators;

namespace Stock_API_Core.Calculations
{
    public class Rsi
    {
        public void sample()
        {
            // fetch historical quotes from your favorite feed, in Quote format
            IEnumerable<Quote> history = GetHistoryFromFeed("MSFT");

            // calculate 20-period SMA
            IEnumerable<SmaResult> results = Indicator.GetSma(history,20);

            // use results as needed
            SmaResult result = results.LastOrDefault();
            Console.WriteLine("SMA on {0} was ${1}", result.Date, result.Sma);
        }
    }
}

The `GetHistoryFromFeed("MSFT");` isn't being recognized despite importing `Skender.Stock.Indicators`

I don't understand why this is happening

**Comment by Jammooly1** [comment]
nvm, I solved it. I manage to provide my own data source so everything is good.

**Comment by DaveSkender** [comment]
Yah, getting the historical price quotes from a source is something you’ll have to do in your own code.  This library will take your historical quotes and convert them into indicators, nothing more.
