### ISSUE TITLE
Tillson T3 Moving Average

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#331]
Private request from a user to add [Tillson T3 Moving Average](https://www.forexfactory.com/attachment.php/845855?attachmentid=845855&d=1322724313)

**Comment by allcasper99** [comment]
hello, i'm ryu on twitter. Is it possible to add Tillson T3 Moving Average indicator to Stock.Indicators?

**Comment by DaveSkender** [comment]
This is now available in version 1.7.0
