### ISSUE TITLE
Vortex Indicator

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#340]
Add Vortex Indicator, requested by @vebollu
Ref: https://en.wikipedia.org/wiki/Vortex_indicator

**Comment by vebollu** [comment]
ty, so much.

**Comment by DaveSkender** [comment]
@8AWESOME4 subscribe to this to be notified when VI is released.  Code is merged, but the new package hasn’t been published yet.  It will be in v1.8.0

Ref #353 comment

**Comment by DaveSkender** [comment]
This is now available in version 1.8.0
