### ISSUE TITLE
Choppiness Index

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#349]
add [Choppiness Index](https://www.forexfactory.com/attachment.php/2876703?attachmentid=2876703&d=1530393505)

**Comment by tanjera** [comment]
I'm starting work on this one 😄

**Comment by DaveSkender** [comment]
Excellent, thanks for helping out. + 🌟

**Comment by DaveSkender** [comment]
I'll re-close this once it's been released to NuGet.  It's code complete and will be available in version 1.8.0

**Comment by DaveSkender** [comment]
This is now available in version 1.8.0
