### ISSUE TITLE
Hilbert transform instantaneous trendline

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#350]
Recommend by @Fredrik-C while [discussing](https://github.com/DaveSkender/Stock.Indicators/discussions/211#discussioncomment-350180) MAMA, which is a similar formula.

**Comment by DaveSkender** [comment]
@Frederik-C do you know of any reputable public charting sites that use this indicator?  I've completed the coding and done fairly extensive manual calculations and unit testing, so I believe it to be correct; however, I like to compare it to others' implementations for a final sanity check.  Ideas?

Here's what it looks like currently:
![image](https://user-images.githubusercontent.com/8432125/108002668-50807f80-6fbe-11eb-9015-f85ce3c4f57e.png)

**Comment by Fredrik-C** [comment]
@DaveSkender Awesome!

I have previously been using Alpha Vantage and found the "Hilbert transform instantaneous trendline" to be very usefull.
https://www.alphavantage.co/documentation/#httrendline

**Comment by Fredrik-C** [comment]
@DaveSkender I cloned your "hilbert" branch and did some numbercrunching with my backtrader and a few quotes ran into a "index out of bounds" exception.

I attached a couple of sample "history" data that the indicator has issues with.

[HT_trendLine_unfriendly_json.zip](https://github.com/DaveSkender/Stock.Indicators/files/5990372/HT_trendLine_unfriendly_json.zip)

**Comment by Fredrik-C** [comment]
BTW, running a Rsi on the HTTrendLine gives you some sweet results!

**Comment by DaveSkender** [comment]
I'll add your test data and will probably make some new unit tests with it.  I have a bad data test dataset that usually catches those sorts of things.  Thanks for providing.

**Comment by Fredrik-C** [comment]
> I'll add your test data and will probably make some new unit tests with it. I have a bad data test dataset that usually catches those sorts of things. Thanks for providing.

Seems to be related to the number of items in the quotes array.
The original dataset has 533 items and fails, but if I make a ".TakeLast(500)" then it works:

`        [Fact]
        public void HTTrend()
        {
            var json = File.ReadAllText(@"G:\ContainerCache\HT_trendLine_unfriendly.json");
            var quotes = JsonConvert.DeserializeObject<List<Quote>>(json).TakeLast(500);
            var htTrendline = Indicator.GetHtTrendline(quotes);
        }
`

**Comment by DaveSkender** [comment]
Hmmm.  One of my unit tests has more than 1100 points in history.  Something seems fishy.

**Comment by Fredrik-C** [comment]
Yes, there is nothing to pull from the branch. I'm at commit bf8114 (bf8114825b5181f5aecbdc455022e3c0104e8de8)

**Comment by DaveSkender** [comment]
I’ll get back to this over the weekend.

**Comment by DaveSkender** [comment]
Thanks for the data.  I found the bug.  It's a rare data scenario where the adaptive dominant cycle period (calculated lookback period) grows to be bigger than the amount of lookback data.  It has nothing to do with the size of your dataset, but more to do with the specific scenario the first 40+ elements created.

**Comment by DaveSkender** [comment]
I've pushed the fix to the feature branch.  Wanna give it another try?

**Comment by DaveSkender** [comment]
One thing to note about the Alpha Vantage API is that they have chosen to use Close price instead of the original Ehler's formula `(High+Low)/2` price. The difference between using the two alternative prices is small.  This library uses and is true to the original recipe, as depicted in Ehler's book [Rocket Science for Traders](https://isbndata.org/978-0-471-40567-2).

**Comment by DaveSkender** [comment]
This is now available in version [1.9.0](https://github.com/DaveSkender/Stock.Indicators/releases/tag/1.9.0)
