### ISSUE TITLE
RSI, AROON the output does not match with the BINANCE exchange

### ISSUE THREAD

**Issue by 8AWESOME4** [DaveSkender/Stock.Indicators#353]
![image](https://user-images.githubusercontent.com/74122431/107672023-cbece300-6cd7-11eb-82e5-42fa6313fead.png)

GetKlinesBefore_300(DateTime.Now);
  private void GetKlinesBefore_300(DateTime dateTime)
        {
            init_quote_300_Tick_For_Signals.AddRange(BiClient.Spot.Market.GetKlines(pair, KlineInterval.ThreeMinutes, endTime: dateTime)
                .Data.Select(u => new Quote
                {
                    Open = u.Open,
                    Close = u.Close,
                    Low = u.Low,
                    High = u.High,
                    Volume = u.QuoteVolume,
                    Date = u.CloseTime
                }).ToList());
        }
   decimal? RSI = Indicator.GetRsi(init_quote_300_Tick_For_Signals, 4).LastOrDefault().Rsi;
            decimal? RSI_24 = Indicator.GetRsi(init_quote_300_Tick_For_Signals, 6).LastOrDefault().Rsi;
            var AROON = Indicator.GetAroon(init_quote_300_Tick_For_Signals,23).LastOrDefault();

**Comment by DaveSkender** [comment]
Are you aware of and considered the warmup period required for precision in RSI?  I've been debating whether or not we should exclude this warmup period because we do get this inquiry occasionally (#306).  Make sure you're using enough preceding price history and then ignore the warmup period, which - for RSI - is the first 10xN or 40-60 or more dates in your case.

For Aroon, I can't say what or where the issue is without more information.  It's a fairly simple calculation.  Can you compare your Binance chart to a more reputable site like StockCharts.com and let me know what you find?  I personally do not trust the Binance and TradingView charts because they often use unverified user provided indicators (#318).

**Comment by 8AWESOME4** [comment]
List<Quote> init_quote_300_Tick_For_Signals = new List<Quote>();
        Quote quote_ = new Quote();
        decimal open = 0;
        private void GetTick()
        {
            _ = BiSocketClient.Spot.SubscribeToKlineUpdates(pairs, interval, (data) =>
              {
                  _ = Invoke(new Action(() =>
                  {
                      quote_.CloseDate = data.Data.CloseTime;
                      quote_.Open = data.Data.Open;
                      quote_.High = data.Data.High;
                      quote_.Low = data.Data.Low;                      
                      quote_.Close = data.Data.Close;                      
                      quote_.Volume = data.Data.QuoteVolume;

                      init_quote_300_Tick_For_Signals.RemoveAt(init_quote_300_Tick_For_Signals.Count - 1);
                      init_quote_300_Tick_For_Signals.Add(quote_);

                      
                      decimal? RSI = Indicator.GetRsi(init_quote_300_Tick_For_Signals, 4).LastOrDefault().Rsi; // the value does not change((((
                      decimal ? RSI_24 = Indicator.GetRsi(init_quote_300_Tick_For_Signals, 6).LastOrDefault().Rsi;// the value does not change((((
                      var AROON = Indicator.GetAroon(init_quote_300_Tick_For_Signals).LastOrDefault();// the value does not change((((
                      listBox1.Items.Add($"{data.Symbol}\tClose {data.Data.Close}\tOpen {data.Data.Open}\t{DateTime.Now.ToShortTimeString()}\tRSI-4 {Math.Round((decimal)RSI, 1)}\tRSI-6 {Math.Round((decimal)RSI_24, 1)}\tAroon_DOWN {AROON.AroonDown}\tAroon_UP {AROON.AroonUp}");
                      if (open != data.Data.Open)
                      {
                          listBox1.Items.Add("INTERVAL");
                          init_quote_300_Tick_For_Signals.RemoveAt(0);
                          init_quote_300_Tick_For_Signals.Add(quote_);
                          open = data.Data.Open;
                      }
                  }));// Handle account info update 
              });
        }
    private void GetKlinesBefore_300() // GOOD History  
        {
            init_quote_300_Tick_For_Signals.AddRange(BiClient.Spot.Market.GetKlines(pair, interval)
                .Data.Select(u => new Quote
                {
                    Open = u.Open,
                    Close = u.Close,
                    Low = u.Low,
                    High = u.High,
                    Volume = u.QuoteVolume,
                    Date = u.CloseTime
                }).ToList());
        }

**Comment by 8AWESOME4** [comment]
RSI values do not change ((((

**Comment by 8AWESOME4** [comment]
[Serializable]
    public class Quote : IQuote
    {
        internal int? Index { get; set; }
        public DateTime Date { get; set; }
        public DateTime CloseDate { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public decimal Volume { get; set; }
    }

**Comment by 8AWESOME4** [comment]
version 1.7.0 does not have Vortex indicator

**Comment by DaveSkender** [comment]
I can see you’re stuck here.  I suspect there’s something in your implementation that’s problematic, around use of `LastOrDefault()`.  

Call for help:  Anyone available to help with a user code review?

**Comment by 8AWESOME4** [comment]
Help me

**Comment by 8AWESOME4** [comment]
Нашел ошибку, исправил теперь все работает!!! ) тикет можете закрыть

**Comment by DaveSkender** [comment]
Add `DateTime IQuote.Date => CloseDate;` into your custom Quote class.  If you're customizing like this, you have to map your custom `CloseDate` to the original `Date` property.  You may have to remove the `Date` property if you do it this way though.

More info: [Using custom quote property names](https://daveskender.github.io/Stock.Indicators/docs/GUIDE.html#using-custom-quote-property-names)
