### ISSUE TITLE
Standard Deviation Channel

### ISSUE THREAD

**Issue by ray2k** [DaveSkender/Stock.Indicators#361]
As referenced in this discussion:

Community discussion about [Slope and Linear Regression](https://daveskender.github.io/Stock.Indicators/indicators/Slope/#content)

_Originally posted by @DaveSkender in https://github.com/DaveSkender/Stock.Indicators/discussions/241_

**Comment by DaveSkender** [comment]
For implementation, I think having the `lookbackPeriod` optional, it can then span the entire provided `history`.  When a `lookbackPeriod` is provided, we can either just map the last regression line, or do windowed channels, like:

![image](https://user-images.githubusercontent.com/8432125/108002480-c89a7580-6fbd-11eb-939d-d75d76208a6b.png)

**Comment by DaveSkender** [comment]
@ray2k have you seen these lookback windows covering fixed calendar periods, like weeks or months; or are they usually X days repeated, like the picture above?  The reason I ask is that these will produce different historical results based on a rolling window position, so it won't be persistent.  In other words, you'd never really be able to use these for backtesting.

**Comment by DaveSkender** [comment]
To fix this problem, we could just trace the last points of the linear regression line (e.g. the last point shown on the chart above.  This would provide consistent historical results.  I'm not sure if this would be better or different enough from the other channels.  I need to look at the regression math and see if this just reverse-engineers itself into a regular moving average centerline.

![image](https://user-images.githubusercontent.com/8432125/108614098-d12beb00-73c5-11eb-90d5-e63a23dec9b9.png)

**Comment by ray2k** [comment]
@DaveSkender I've only seen this indicator in full-chart mode to be honest, because it gives an immediate LR trend-line and and the deviation lines capture certain percentages of price action. But I'm also nowhere near an expert in technical analysis/stock market knowledge in general. Personally if I would use other indicators like vwap or bbands before using standard deviation with a lookback period that isn't the whole chart i'm analyzing.

**Comment by DaveSkender** [comment]
I think we'll stick with the original channels with the option for windows lookback or full variants.  They'll look like this:
![image](https://user-images.githubusercontent.com/8432125/108636752-50b4cb00-7455-11eb-81e5-a0f5368d5c91.png)
![image](https://user-images.githubusercontent.com/8432125/108636756-58746f80-7455-11eb-86b0-0af799289ce4.png)

**Comment by DaveSkender** [comment]
This is now available in version [1.9.0](https://github.com/DaveSkender/Stock.Indicators/releases/tag/1.9.0)

**Comment by ray2k** [comment]
@DaveSkender Dude! This is awesome, thanks for getting this in there so quick. Checked it out and seems to be exactly what I need
