### ISSUE TITLE
StarcBandsResult typo in documentation

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#367]
`StarcBandResult` should be `StarcBandsResult` in `Indicators\StarcBands\README.md`, multiple places.

If you are interested in contributing this fix, let us know with a comment below.  This is a good issue for a GitHub newbie so you can get experience with the process of making a contribution.  The change itself is minor.

**Comment by ssathya** [comment]
Submitted a pull request to address this issue. As indicated in the pull request did not run unit tests as this was an update to the README file.
