### ISSUE TITLE
Bull and Bear Power Indicator

### ISSUE THREAD

**Issue by moslem7026** [DaveSkender/Stock.Indicators#373]
i cant find Bull Power and Bear Power Indicator, Is there ?

**Comment by DaveSkender** [comment]
Can you point me to any documentation or information about the indicator?  I'll take a look and see if its something we can add or if its something we already have but named differently.

**Comment by moslem7026** [comment]
https://www.metatrader5.com/en/terminal/help/indicators/oscillators/bulls
https://www.metatrader5.com/en/terminal/help/indicators/oscillators/bears

**Comment by DaveSkender** [comment]
Seems okay to add to our backlog.  We'll most likely implement this as one indicator with Bull+Bear in the results, rather than two separate indicators.

**Comment by DaveSkender** [comment]
Just an FYI, this is formally called the [Elder-ray Indicator](https://www.investopedia.com/articles/trading/03/022603.asp) or Elder-Ray Index.  Bull and Bear Power are its component parts.

**Comment by DaveSkender** [comment]
This is now available in version [1.10.0](https://github.com/DaveSkender/Stock.Indicators/releases/tag/1.10.0)
