### ISSUE TITLE
Ehlers Fisher Transform

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#395]
add EFT indicator
https://www.investopedia.com/terms/f/fisher-transform.asp

If you're interested in contributing this indicator, please stake your claim with a comment below.  Please also read our [contributing guidelines](https://daveskender.github.io/Stock.Indicators/docs/CONTRIBUTING.html) before starting.

**Comment by developer-myalgomate** [comment]
I can help you with the formula calculation in excel

**Comment by developer-myalgomate** [comment]
[Fisher Transaformation.xlsx](https://github.com/DaveSkender/Stock.Indicators/files/6249259/Fisher.Transaformation.xlsx)
I hope this is useful to you.

**Comment by DaveSkender** [comment]
> [Fisher Transaformation.xlsx](https://github.com/DaveSkender/Stock.Indicators/files/6249259/Fisher.Transaformation.xlsx)
> I hope this is useful to you.

Helpful.  Thank you.

**Comment by DaveSkender** [comment]
This is now available in v1.11.0
