### ISSUE TITLE
OBV value is wrong. It looks like, it is calculated as half of the actual value but i am not sure if exactly the half of real value.

### ISSUE THREAD

**Issue by kayahasa** [DaveSkender/Stock.Indicators#431]
## Describe the bug

A clear and concise description of the bug.  If known, explain why you believe the problem is within this library and not in your wrapper code or sources of comparison.

Error message(s):

```bash
# Include any error messages if available.
```

## To Reproduce

1. What indicator and parameter arguments were used?
2. Attach the historical quotes you used (as CSV or Excel file)

## Screenshots or other reference materials

If applicable, add screenshots or other reference materials to help explain the problem.

**Comment by kayahasa** [comment]
It s my wrong sorry,
I assumed the default length of trading view OBV was 300 but i think it is not 300. I couldnt find any default value for trading view. I think they take the start point from the first data in the history. So, i couldnt calculate it for 15m.

Thanks

**Comment by DaveSkender** [comment]
Thanks for reporting anyway.  I appreciate the opportunity to make the library better.  This is a common inquiry, with OBV and ADL.  I’ll add an explainer to our Q&A section of Discussions.
