### ISSUE TITLE
Enable Github Sponsors?

### ISSUE THREAD

**Issue by codebeaulieu** [DaveSkender/Stock.Indicators#440]
This repository is pretty outstanding. A trading based company that I work with would be interesting in doing a monthly sponsorship to help encourage continued development and support.

**Comment by DaveSkender** [comment]
How does all that work?  Seems fishy.

**Comment by codebeaulieu** [comment]
Pretty sure Microsoft isn't trying to scam anyone haha
https://github.com/sponsors

**Comment by DaveSkender** [comment]
I'll check it out.  Seems like a nice way for patrons to give back or show appreciation.

**Comment by DaveSkender** [comment]
I've enabled sponsorship.  Thank you for your patronage!

**Comment by codebeaulieu** [comment]
Great I just personally sponsored and I passed your repo on to our CEO to review.
