### ISSUE TITLE
Relative Strength Comparison

### ISSUE THREAD

**Issue by codebeaulieu** [DaveSkender/Stock.Indicators#441]
# Relative Strength Comparison

> Relative Strength Comparison compares a security's price change with that of a "base" security or index. When the Relative Strength Comparison indicator is moving up, it shows that the security’s price is performing better than the base security/index in relative terms. When the indicator is moving sideways, it shows that both securities prices are rising and falling by the same percentages. When the indicator is moving down, it shows that the security’s price is performing worse than the base security/index in relative terms.
> Relative Strength Comparison is often used to compare a security's performance with a market index.

[Read More...](https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/relative-strength-comparison)

[And another read from Investopedia.com](https://www.investopedia.com/ask/answers/06/relativestrength.asp)

I've built this in my own system but I'd like to migrate my system to use your library. It shouldn't be too hard to port to your formatting and I wouldn't mind making an attempt PR on this, though I'm not sure when I'll have time. Also your chops are definitely better than mine so perhaps you can improve upon my version.

Here's my code:

```
    public class RelativeStrengthComparison : IndicatorBase
    {
        public int AvgLength = 9;

        public decimal[] Result { get; set; }

        public decimal[] Average { get; set; }

        private bool _computeAverage = false;

        private int _collectionLength = 0;

        public RelativeStrengthComparison(IEnumerable<Candle> focus, IEnumerable<Candle> compare, int length, bool computeAverage = false)
            : base(focus, compare)
        {
            AvgLength = length;
            _computeAverage = computeAverage;
        }

        protected override void Initialize()
        {
            _collectionLength = Math.Min(Series.Length, SeriesCompare.Length);
            Result = new decimal[_collectionLength];
            Average = new decimal[_collectionLength];
        }

        public override void Compute(int startIndex = 0, int? endIndex = null)
        {
            if (endIndex == null)
                endIndex = _collectionLength;

            for (int index = startIndex; index < endIndex; index++)
            {
                decimal focusClose = Series.Close[index];
                decimal comprClose = SeriesCompare.Close[index];

                decimal result = focusClose / comprClose;

                Result.SetValue(result, index);

                if (_computeAverage)
                {
                    Average[index] = Avg(Result, index, AvgLength);
                }
            }
        }

        public decimal Avg(decimal[] input, int index, int period)
        {
            var pos = Math.Max(index - period + 1, 0);

            if (pos == 0)
                return 0;

            var sum = input.Sum(index, period);
            return sum / period;
        }
    }
```

## Additional context or information

My use case for this is building watchlists for my algorithm to watch.

**Comment by codebeaulieu** [comment]
Here's another example implementation:
https://www.tradingview.com/v/IpfLF3Oj/

```
study("Relative Strength Comparison", shorttitle="RSC")

a = tickerid
b = input("SPX500", type=symbol, title="Comparison Index")
len = input(50, type=integer, minval=1, title="Comparison Period")
ma_len = input(10, type=integer, minval=1, title="Moving Average Period")

as = security(a, period, close)
bs = security(b, period, close)

zeroline = 0
crs = ((as/as[len])/(bs/bs[len]) - 1)
ma = sma(crs, ma_len)

zero_color = (crs >= 0) ? green : orange
plot_color = (crs >= ma) ? green : orange
ma_color = (crs >= ma) ? green : orange
fill_color = (crs >= ma) ? green : orange

hzplot = plot(zeroline, title="Horiz. Axis", color=zero_color, linewidth=1)
crs_plot = plot(crs, title="CRS", color=plot_color, linewidth=2, transp=0)
ma_plot = plot(ma, title="Moving Average", color=ma_color, transp=0)
fill(plot1=crs_plot, plot2=hzplot, color=fill_color, transp=70)
```

**Comment by DaveSkender** [comment]
This is similar to [Price Relative Strenght](https://daveskender.github.io/Stock.Indicators/indicators/Prs/#content).  I'm adding it to the backlog and will likely take a look at it this weekend.

**Comment by codebeaulieu** [comment]
Yup, this seems like the same indicator. It just has a few names so I missed it. Backlog or even close as a duplicate imo.

Thanks!

**Comment by DaveSkender** [comment]
Already implemented as [Price Relative Strength](https://daveskender.github.io/Stock.Indicators/indicators/Prs/#content)
