### ISSUE TITLE
Div zero issue for Klinger Volume Oscillator

### ISSUE THREAD

**Issue by Obiwanbde** [DaveSkender/Stock.Indicators#450]
Hi,

First of all many thanks and congratulations for this huge and great work. It is a great treasury.

Few days ago, I have been discussing Klinger Volume Oscillator with my friend and some days after I saw that you have included it recently.

Today, I have collected some data and put it to your Excel file Kvo.Calc.xlsx. I have realized that for some intervals Div Zero error occurs on Volume Force(VF) column. The case happens when the cumulative measurement(cm) is zero, which happens when both current and previous dm is zero. This case happens on H = L for the interval for two subsequent intervals. After that all others(EMA34, EMA55,...) gives error. I have attached the file with my data but you can also reproduce anytime with setting H = L with two subsequent intervals/lines and get the problem. 

I'm not a C guy, but if I understand correctly, this could happen also on line 81 if c[i] is equal to zero.

Any ideas to have a fix ?

Thanks.
[Kvo.Calc-Problem.xlsx](https://github.com/DaveSkender/Stock.Indicators/files/6534309/Kvo.Calc-Problem.xlsx)

**Comment by DaveSkender** [comment]
Let me take a look.  I try to make these fail-safe for div/0 scenarios, but must have missed some aberrant data case, despite having all sorts of "bad data" unit tests.  Thanks for the detailed info.

**Comment by DaveSkender** [comment]
For clarification, was this div/0 error from the library itself, or just in the Excel spreadsheet?

**Comment by Obiwanbde** [comment]
In Excel and I have also coded the similar routine in Java and get the same error in Java when the High and Low prices are equal for the two subsequent intervals.

**Comment by DaveSkender** [comment]
Ah, okay.  I'll take a look in a few hours.  I may have already accommodated it in the .NET library by basically skipping VF calculation when `cm` is zero, but now that I'm looking at your spreadsheet, I think there's some handling improvements to reduce the occurrence, by first allowing VF=0 when `dm=0`.  In cases where VF cannot be calculated, the EMAs will not be able to continue due to the use of a missing VF.

**Comment by DaveSkender** [comment]
So, for the spreadsheet, you'd basically have to handle a bunch of IF statements to keep it from erroring out in your data scenario.  The .NET library already handles the `cm=0` case, so I'm not going to call it a software bug; however, you have inspired me to add some more handling around the `VF` formula to make it more resistant to failure.  Basically, I'm adding some more conditionals:
```
  // Volume Force (VF)
  vf[i] = (dm[i] == cm[i] || h.Volume == 0) ? 0
     : (dm[i] == 0) ? h.Volume * 2 * t[i] * 100m
     : (cm[i] != 0) ? h.Volume * Math.Abs(2 * (dm[i] / cm[i] - 1)) * t[i] * 100m  // primary case
     : vf[i - 1];
```
If you want to harden the Excel spreadsheet to do the same, you'd have to add these same criteria in it.

**Comment by DaveSkender** [comment]
By the way, there are some ways to use this .NET library in a Java program, but it can get complicated.  I'm looking for some volunteers to do a Java wrapper for this library to make it more usable for the Java community.  Let me know if you know of anyone interested in leading that work.

**Comment by Obiwanbde** [comment]
Yes I agree, I saw your additional if checks on C code and gonna make them as nested ifs in Excel. 

Thanks.

**Comment by Obiwanbde** [comment]
I think this is the Excel cell formula for VF column, if I understand your C changes correctly:

`=IF(OR([@dm]=[@cm];[@volume]=0);0;IF([@dm]=0;[@volume]*2*[@T]*100;IF([@cm]<>0;[@volume]*ABS(2*([@dm]/[@cm]-1))*[@T]*100;0)))`

**Comment by DaveSkender** [comment]
Yah, that looks about right, though I thought Excel uses `,` where you have `;` in your formula.  The last `0` could also be previous `VF`, but that's up to you as it's a subjective choice on how to propagate in that worst case scenario.

**Comment by Obiwanbde** [comment]
Thanks, Usage of ; or , based on the regional settings, mine is working with ;
