### ISSUE TITLE
Java wrapper

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#452]
Add Java wrapper and publish as a community JAR to Maven.
We're seeking Java contributors to lead an effort to build a version-synced parallel path Java wrapper for this library.

## Pull-Requests To Do

- [ ] Add baseline wrapper with 1-2 indicators to prove our approach
- [ ] Add initial unit tests to verify the implementation
- [ ] Add packaging and unit testing to the build
- [ ] Add remaining indicators and unit tests
- [ ] Final sanity check and any needed refactoring
- [ ] Add general "Java support" documentation to expand the Guide (e.g. how to use the Maven JAR plugin)
- [ ] Update individual indicator documentation for Java usage
- [ ] Add deployment to package manager(s), deploy

If you or anyone is interested in contributing to this or leading the project, let us know and we can start to discuss implementation details. I haven't done a lot of research, so I'm unclear on whether we need to add any more C# code to make this easier. I'm definitely here to help and contribute in those areas if needed. This will go in the `/wraps/java` folder in the repo.

My only ask is that we implement in small increments. In other words, the first Pull Request should only include one or two indicators, without any documentation updates, and will be used to establish the baseline approach.

We can then figure out a strategy to get all the way to a published package that people can get from the public Maven plugin manager. The above Pull Request To-Do list captures the current sequence of increments and who's working on what parts to coordinate amongst collaborators.

**To contribute, announce here what piece you're picking up and I'll put your name next to it, then check it off when done.**

**Comment by DaveSkender** [comment]
@97nitt, let me know if interested in supporting this.

**Comment by 97nitt** [comment]
@DaveSkender finally got around to looking into this. I've never attempted to write a Java wrapper around a C# library. And after a little research, I think I know why I've never seen it done. Requires some glue code, written in C++ in between. So you'd be maintaining, distributing, and installing 3 different libraries in 3 different languages. It's kinda gross. And it would come with performance costs too, running through 3 layers of software is likely to be significantly slower. I wouldn't recommend building a wrapper unless you _really_ think it's necessary to do it that way.

Alternatives would be to:

- create a "port" of the C# library in each language you would like to support. Basically implement the same functionality in each language. This is pretty common, lots of client libraries have several versions that strive to provide the same functionality in multiple languages. Inevitably, one language is the vanguard, and all the rest lag behind.

- provide a language-agnostic interface, mostly likely HTTP (e.g. a [REST](https://dotnet.microsoft.com/apps/aspnet/apis) or [GraphQL](https://github.com/graphql-dotnet/graphql-dotnet) API). This would require you to implement the HTTP interface around your C# library, and package the project so it can be deployed to a web server. In addition, you could provide a [Docker](https://www.docker.com/) image that would allow everything to be easily run in a virtualized environment. You could then host it on any cloud provider, or allow folks to run that image on whatever Docker-compatible infrastructure they want.

Happy to help out with any of these really. Even the wrapper, if that's what you decide you really want to do. I'd consider it one of those challenges you take on just to see if you can do it. But I do think you'd ultimately regret it.

**Comment by DaveSkender** [comment]
@97nitt Yah, the wrapper sounds problematic.  I like the other two options.  I don’t have the chops to do a good Java version, but have some of that REST API started in the Stock.Charts demo.

You interested in leading one of these?
