### ISSUE TITLE
Cannot Aggregate() to PeriodSize.ThirtyMinutes

### ISSUE THREAD

**Issue by moslem7026** [DaveSkender/Stock.Indicators#458]
Please add PeriodSize.ThirtyMinutes to this function
https://github.com/DaveSkender/Stock.Indicators/blob/2479b6ab16d463c8bd7037e14847dae43d902487/indicators/_Common/Functions.cs#L51

**Comment by DaveSkender** [comment]
This fix for this is to simply add `PeriodSize.ThirtyMinutes => TimeSpan.FromMinutes(30),` to this switch statement mentioned above.  Good first issue for someone interested in learning [how to contribute](https://daveskender.github.io/Stock.Indicators/docs/CONTRIBUTING.html) to open source projects.

**Comment by DaveSkender** [comment]
This was fixed in version 1.12.3
