### ISSUE TITLE
Hurst Exponent (Rescaled Range Analysis)

### ISSUE THREAD

**Issue by 8AWESOME4** [DaveSkender/Stock.Indicators#466]
https://github.com/Mottl/hurst

**Comment by DaveSkender** [comment]
Interesting.  I'll take a look.
https://en.wikipedia.org/wiki/Hurst_exponent

**Comment by DaveSkender** [comment]
@8AWESOME4 this one is going to take a while.  There's a lot of heavy math in this one.

**Comment by DaveSkender** [comment]
This was release as a Preview in v1.15.0
