### ISSUE TITLE
SMA overload for other OHLC parts

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#506]
### Discussed in https://github.com/DaveSkender/Stock.Indicators/discussions/505

<div type='discussions-op-text'>

<sup>Originally posted by **bitwizardry** August  5, 2021</sup>
Hi Dave, 

What about a GetSMA's overload with a `Func<IQuote, Decimal>`  allowing us to get the sma from any part of the candle, not only from the Close price? I think it's a nice idea.
</div>

**Comment by DaveSkender** [comment]
@bitwizardry, I'm taking a closer look at this one now.  The current API for this is `quotes.GetSma(lookbackPeriod)`.  I am considering having the override be `quotes.GetSma(lookbackPeriod,element)` where `element` is a string representation of `O`,`H`,`L`,`C`, or `V` to match the existing internal converter `quotes.ConvertToBasic(element)`.

I tend to prefer `enum` over `string` for public method parameters since `string` can be quite dirty and `enum` essentially forces a strict list.  Before I get started on this, do you have any thoughts to contribute?

https://github.com/DaveSkender/Stock.Indicators/blob/1ea501edd47c4c9954522f12b2176a7fa562d139/src/_Common/Quotes/Quotes.Functions.cs#L95-L118

**Comment by bitwizardry** [comment]
Hi Dave, to me sounds perfect. 

I thought about `Func<IQuote, Decimal>` to let the user free to code anything. For instance, we could extract the mean of the candle prices (open + close + high + low) / 4, and then get the moving average, crazy experimental stuffs, just to see how different the values are from the original close price. 

The way that you did it, to me is perfect. 

Would be nice if you implement this overload to GetSma and GetEma functions.

**Comment by DaveSkender** [comment]
I think there's always going to be a bit of a `hack` that someone can take if they want to do something exotic. See #500.
You have an opinion on `string` vs `enum`?

**Comment by bitwizardry** [comment]
Hard to say.. I would prefer `enum`. I let it up to you!

**Comment by DaveSkender** [comment]
This is now available in version 1.17.0

**Comment by bitwizardry** [comment]
Thank you Dave, soon I will offer more suggestions and implementations!

**Comment by DaveSkender** [comment]
Thanks for your help and suggestions!  I welcome all contributions in any form; I'm hoping you'll want to contribute code at some point ... 😃

**Comment by bitwizardry** [comment]
> Thanks for your help and suggestions! I welcome all contributions in any form -- and I'm hoping you'll want to contribute code at some point ... 😃

Surely my friend, but first I need to learn how to use the github correctly, my brother is giving me some tips.

**Comment by DaveSkender** [comment]
I have a few tips here: #503
