### ISSUE TITLE
Bug in ZigZag Indicator

### ISSUE THREAD

**Issue by heavymanto** [DaveSkender/Stock.Indicators#510]
## The problem

I would to draw 2 ZigZag line using first (represent short time) with percentuale = 1% and second with 10% (represent long time)
I have used a list of 250 quote element but the result is the same in both the first and second indicators. furthermore, the data does not seem correct, they follow every single candle and do not trace the long term

## To Reproduce

I attatch Json with elaboration with OHLC input and ZigZag calculated
[TradesData.zip](https://github.com/DaveSkender/Stock.Indicators/files/6950459/TradesData.zip)

## Expected behavior

I expeted this, a LONG line for ZigZag 10% (red) and a short line for ZigZag 1% (yellow)

![Expected ZigZag](https://user-images.githubusercontent.com/6449169/128626522-c8923e7a-a7a6-40a9-8068-3a8214daed6e.PNG)
 

## Screenshots or other reference materials

i have plot data in chart.

![chart_ZigZag](https://user-images.githubusercontent.com/6449169/128626490-9f6abf0e-eb5e-4b48-9f63-72a2dbf53f8e.PNG)

**Comment by DaveSkender** [comment]
Can you elaborate on the exact parameter arguments you put into the `GetZigZag(type, percentChange)` method and which `ZigZagResult` Properties you are using in your chart?  Maybe you're using `0.1` instead of `10` for the `percentChange` argument?  See [docs](https://daveskender.github.io/Stock.Indicators/indicators/ZigZag/#parameters).

If that's not the problem, I'll take a look.  Do you have the original historical quote data (input)?

**Comment by heavymanto** [comment]
Hi, that's ok. I have test with different percentuale but result are same,
not change by input data. You can found ohlc input/output in zip file
attached

Il Dom 8 Ago 2021, 19:49 Dave Skender ***@***.***> ha scritto:

**Comment by DaveSkender** [comment]
Works fine when I do it, with your data.  I suspect you're not using the right `percentChange` argument.  For this use case, you should use:

```csharp
var results01 = quotes.GetZigZag(EndType.HighLow, 1);
var results10 = quotes.GetZigZag(EndType.HighLow, 10);
```
![image](https://user-images.githubusercontent.com/8432125/128644362-43d46902-f2a1-4a14-9e4f-6bf4d714f506.png)

[Issue510.zip](https://github.com/DaveSkender/Stock.Indicators/files/6951384/Issue510.zip)

**Comment by heavymanto** [comment]
I m sorry, but not understend how to plot line, there is more detail to
draw it? Thanks

Il Dom 8 Ago 2021, 22:08 Dave Skender ***@***.***> ha scritto:

**Comment by DaveSkender** [comment]
> I m sorry, but not understend how to plot line, there is more detail to draw it? Thanks

This library only produces the data; how you use it is up to you.  To troubleshoot this issue, I simply put the result data in Microsoft Excel and created a chart, nothing special.

If you're looking for visualization technology examples and recommendations, see [discussion 430](https://github.com/DaveSkender/Stock.Indicators/discussions/430).

**Comment by heavymanto** [comment]
Please, can you check my result in attached file? Why zigzagfast and
zigzagslow have same result? I have to plot each point or only if are flag
H/L?
Thanks

Il Dom 8 Ago 2021, 23:04 Dave Skender ***@***.***> ha scritto:

**Comment by DaveSkender** [comment]
> Please, can you check my result in attached file?

There's a CSV file with results in this ZIP file that you can use for comparison: [Issue510.zip](https://github.com/DaveSkender/Stock.Indicators/files/6951384/Issue510.zip)

**Comment by heavymanto** [comment]
Thaks a lot, i will study and check. Last question, I have to plot each
point or only if are flag H/L?
Thanks

Il Dom 8 Ago 2021, 23:30 Dave Skender ***@***.***> ha scritto:

**Comment by DaveSkender** [comment]
> I have to plot each point or only if are flag H/L?

This is entirely up to you.  The results for Zig Zag always return the same number of data elements as are in the source quote history with interpolated linear values between H and L points.  If you were just wanting to plot the H/L points, you can filter the results.

```csharp
// H/L points only (using LINQ)
var results = quotes.GetZigZag(..)
  .Where(x => !string.IsNullOrEmpty(x.PointType))
```

**Comment by heavymanto** [comment]
thank for your time friend, I have study a lot of your data and understand my issue. A loop in foreach OHCL data and take(250) of them. I stored last OHCL and result as I did for the other indicators

` QI.ZigZagFast = retVal.LastOrDefault().ZigZag.Value;`

but in this case, if I'm not mistaken, the previous data are recalculated every time so saving only the last one is wrong. How can I understand when a calculation cycle is closed and from then on it doesn't change anymore? Is it sufficient to intercept the H / L points eg, start at L point and stop at H point? Can H / L be modified and recalculated at a time or are they fixed once identified?

Thanks

**Comment by heavymanto** [comment]
Hi, can you write code you have used for calcolated Issue510.CSV? 
Thanks

**Comment by heavymanto** [comment]
hi, I was able to draw the graphs. the slow zigzag index with parameter 1 looks great. But I see some uncertainty about the long zigzag index with parameter 10 in the final part of the graph. Could you tell me if this data is right for you or am I still doing something wrong? Please find attached the reference data.
thank you
[TradesData.zip](https://github.com/DaveSkender/Stock.Indicators/files/6954820/TradesData.zip)


![image](https://user-images.githubusercontent.com/6449169/128713478-18fda5e7-8ac4-462f-a304-aa879b7a7663.png)

**Comment by DaveSkender** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/8432125/128785853-1414ca12-73d8-4628-af45-323ff7950bb1.png)

**Comment by heavymanto** [comment]
hello, I finally solved the mystery and perfectly understood the functioning of the algorithm. I studied the whole source to understand it but it was worth it, it's very interesting. The documentation states that only two candles are needed to calculate a point. This is correct but nevertheless it is not sufficient to calculate an entire graph as this index continuously recalculates the points to be drawn from the beginning to the end of a certain trend delimited by the H / L points. In fact in the calculation I used groups of OHLC of 250 elements, and as you can see, the beginning of the graph is correct, then when the elements end, only the points calculated partially as last element remain. In my opinion it should be better indicated in the documents that the number of OHLC elements must be sufficient to calculate the latest trend even if it is not easy to calculate it. Obviously, the higher the percentage, the greater the number of OHLC elements. I hope my notes are helpful for other developers. Thanks

**Comment by DaveSkender** [comment]
> In my opinion it should be better indicated in the documents that the number of OHLC elements must be sufficient to calculate the latest trend

Almost all of the indicators in this library are intended to be calculated as a whole series; I can't think of any that can or should be calculated incrementally -- there's too much reliance on previous values to make that easy to do (though, I am considering how that might be done in streaming use cases in v2, at least for some non-repainting indicators - see #216).  Almost all indicators repaint intraday as HLC values change, but some repaint further back into history.

For ZigZag, the last trend is always just a repainted guess.  I think the issue here is in understanding which indicators repaint; ZigZag, Williams Fractal, and other do this.  I'm taking a note to highlight repainting more clearly in the documentation.

Docs for ZigZag currently state:

> You must have at least two periods of quotes to calculate, but notably more is needed to be useful.
..
Also, if you do not supply enough points to cover the percent change, there will be no Zig Zag points or lines.  The first line segment starts after the first confirmed point; ZigZag values before the first confirmed point will be `null`.  **The last line segment is an approximation as the direction is indeterminate**.  ...

**Comment by heavymanto** [comment]
hello, excuse me, tell me how do you extract the data produced in the results to copy them directly into the excel with quote + indicator zigzazg value? There are cases that don't come back to me and I don't understand if I'm wrong or there is a problem. Can you verify this data? I tried it with 12%

[TradesData.zip](https://github.com/DaveSkender/Stock.Indicators/files/6964916/TradesData.zip)
![image](https://user-images.githubusercontent.com/6449169/128946374-e60606de-5d81-4091-9f87-f217b055d552.png)

**Comment by heavymanto** [comment]
hi, , excuse me, tell me how do you extract the data produced in the results to copy them directly into the excel? There are cases that don't come back to me and I don't understand if I'm wrong or there is a problem. Can you verify this data? I tried it with 12%
[TradesData.zip](https://github.com/DaveSkender/Stock.Indicators/files/6964990/TradesData.zip)
![image](https://user-images.githubusercontent.com/6449169/128949027-7d3b028e-d263-41bb-8408-f14e23e23c06.png)

**Comment by DaveSkender** [comment]
I'm not going to get into a whole personal training session on how to do all these things; however, the gist is that I use `Console.WriteLine` to produce the CSV text within my unit test; when I run the test, it produces the results in the console window; and then I copy/paste it into Excel.  In Excel, I use the `Text to Column` feature in the `Data` ribbon menu to parse it.

There are probably better ways to do this, but it's my simple method.

I pushed [my code](https://github.com/DaveSkender/Stock.Indicators/blob/fc982c5721a76865ddf7548059768639c350b705/tests/indicators/Test.ZigZag.cs#L198-L199) to a branch for you to see.

**Comment by heavymanto** [comment]
hi, i have use your code to extract data and plot into Excel, it confirm mi previus chart. time from 1/4 to 25/5 seem wrong
P.S. not understand why excel not plot from 1/1 to 1/4

see attach
Thank a lot for your time

[Issue510_new.xlsx](https://github.com/DaveSkender/Stock.Indicators/files/6965245/Issue510_new.xlsx)
