### ISSUE TITLE
Aggregate using TimeSpan

### ISSUE THREAD

**Issue by heavymanto** [DaveSkender/Stock.Indicators#530]
Hi, I have a timespan value and i would want to convert him in Periodsize, can i implent this function?
Thanks you

**Comment by DaveSkender** [comment]
👍🏼  Seems simple enough to add this to our library of related helper methods.

**Comment by heavymanto** [comment]
Hi, i have implemented funtion and test method. Can a push? In what branch?
thanks you

**Comment by DaveSkender** [comment]
Create a PR from the feature branch in your Fork to the `main` branch in this repo and I’ll take a look.

**Comment by DaveSkender** [comment]
@heavymanto is the use case for this mostly about using a known `TimeSpan` in the `quotes.Aggregate(PeriodSize periodSize)` function?  I ask, because it would be cleaner to simply provide an override like `quotes.Aggregate(TimeSpan timeSpan)` instead.

**Comment by heavymanto** [comment]
hi Dave, yes this is my use case. The use of the overranide is an excellent choice. You want me to change the implementation by overriding quotes.Aggregate (TimeSpan timeSpan)?

**Comment by DaveSkender** [comment]
Yah, if that's your use case, I think it makes sense to do that instead ... it will make it one less step for users.  Thinking about this more, I was thinking that this `.ToPeriodSize()` would have really only one use, and it's probably better to just allow a different parameter type here instead.

**Comment by heavymanto** [comment]
What do you think if in the override Aggregate(TimeSpan timeSpan) call the extension method? In this way with only one method it can be used in multiple scenarios?

`funtion Aggregate(TimeSpan timeSpan)
  return Aggregate(timeSpan.ToPeriodSize())`

**Comment by DaveSkender** [comment]
That can work if `timeSpan` is a compatible value for `periodSize`.  I'm generally okay with skipping the intermediate conversion to `PeriodSize` for a few reasons: 1) `Aggregate` natively uses `TimeSpan` internally, 2) it would be a double conversion back to itself, and 3) using `timeSpan` without forcing `periodSize` would allow users to customize -- for example, if they wanted 45 second periods.

**Comment by heavymanto** [comment]
Ok, thanks for the clarification. I study code, and them propose a solution

**Comment by heavymanto** [comment]
ok, I have dev quotes.Aggregate(TimeSpan timeSpan) funtion and open PR.
Thanks

**Comment by DaveSkender** [comment]
This was release in version 1.17.1
