### ISSUE TITLE
post your btc or eth wallet please, so i can donate

### ISSUE THREAD

**Issue by iddqdelta** [DaveSkender/Stock.Indicators#557]
...

**Comment by DaveSkender** [comment]
Thank you for your interest in sponsoring!
I'm currently only setup for sponsors through GitHub, so if you can go that route I'd appreciate it:
https://github.com/sponsors/DaveSkender

I'll look into BTC/ETH options too, but not sure when I'll get that setup.

**Comment by DaveSkender** [comment]
I’ve now added this information to my [sponsorship profile](https://github.com/sponsors/DaveSkender)
