### ISSUE TITLE
Ichikomu Custom Offset Parameters

### ISSUE THREAD

**Issue by moslem7026** [DaveSkender/Stock.Indicators#558]
ichikomu have Default Paramater named Displacement or Offset that is 26 . how can i set to 0 in skender library ?

**Comment by DaveSkender** [comment]
There are a few offsets in Ichimoku.  I don’t use the term Displacement, do you have a reference where I can see it?

**Comment by moslem7026** [comment]
in trading View Ichikomu indicator have this input

**Comment by DaveSkender** [comment]
Do you have a URL to something that describes the TradingView parameters?

I’ve used an implementation more like what you see here:
https://school.stockcharts.com/doku.php?id=technical_indicators:ichimoku_cloud

**Comment by DaveSkender** [comment]
I’m open to upgrading this to add more parameters that might allow this extra customization that I think is what you’re seeking, but need to know more about it.

**Comment by DaveSkender** [comment]
I see this in Trading View.  I suspect this `Displacement` value is just the offset amount for `Chinkau Span (lagging span)`

![image](https://user-images.githubusercontent.com/8432125/132963070-06e4987e-fccb-499b-9ea2-a3809c32144c.png)

**Comment by DaveSkender** [comment]
To expand this indicator to allow custom offset periods for `Senkou` and `Chikou` spans, I think I'll implement these four overload methods:

```csharp
// defaults
.Ichimoku()

// standard offsets
.Ichimoku(signalPeriods,shortPeriods,longPeriods)

// custom offset
.Ichimoku(signalPeriods,shortPeriods,longPeriods,offsetPeriods)

// custom and different offsets
.Ichimoku(signalPeriods,shortPeriods,longPeriods,senkouOffset,chikouOffset)
```

**Comment by DaveSkender** [comment]
In my implementation, you'll be able to use whichever you prefer, 3/4/5 parameter variants.  I've also set it up so you can use an offset of 0, despite me not knowing why someone would do that -- no harm in allowing it if it doesn't break the calculation (and it does not).

**Comment by DaveSkender** [comment]
This was release in version 1.17.1
