### ISSUE TITLE
 `IPyObjectDecode` to use `CandlePart` in Python wrapper

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#563]
> I tried to call the function manually by fetching the parameter `Type`s of what I need to call among overloaded functions. But it keeps converting `Enum` to `int`. It was same even when I access the function via `System.Reflection.Assembly`.
As a result, we need to implement `IPyObjectDecode` to use `CandlePart` and it have to be done in C# code. Can I ask you to do this?

_Originally posted by @LeeDongGeon1996 in https://github.com/DaveSkender/Stock.Indicators.Python/issues/13#issuecomment-926566302_

More information:
https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python

**Comment by DaveSkender** [comment]
See comments in originating issue; this may be resolved in PythonNet v3

**Comment by DaveSkender** [comment]
Generally, for all enum, it might make sense to hardcode integer values for each and see if that works better with Python param

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 we don’t need this anymore, right?

**Comment by LeeDongGeon1996** [comment]
@DaveSkender  Right!
