### ISSUE TITLE
add an alias of K & D to Oscillator and Signal

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#569]
> Just curious if you could add an alias of K & D to Oscillator and Signal [for Stochastic]?  Totally not important, but helps my brain at times. 

_Originally posted by @wclark17 in https://github.com/DaveSkender/Stock.Indicators/discussions/315#discussioncomment-1408371_

**Comment by DaveSkender** [comment]
I'm looking at this briefly and realized that I've never created an alias for a property before.  I think the goal here is to see if an alias can be created for `StochResult` class properties without adding potentially confusing information.  Anybody have some ideas on how to do this?

**Comment by wclark17** [comment]
Can you just create another property and read the value of the Oscillator
and Signal?
i.e.

public K { get => Oscillator; }

**Comment by DaveSkender** [comment]
```csharp
public class StochResult : ResultBase
{
    public decimal? Oscillator { get; set; }
    public decimal? Signal { get; set; }
    public decimal? PercentJ { get; set; }

    // aliases
    public decimal? K => Oscillator;
    public decimal? D => Signal;
    public decimal? J => PercentJ;
}
```

**Comment by wclark17** [comment]
Awesome!  Thanks!
