### ISSUE TITLE
Apparently ZigZag cannot tolerate big number of candles

### ISSUE THREAD

**Issue by Salardx** [DaveSkender/Stock.Indicators#600]
Hi, thank you for your great tools,
I got 300 candles, when I run ZigZag(percentChange: 5) on them, it returns 300 ZigZagResult
but only its 74 latest results have values inside, the first 226 values all show null.
I expect the algorithm check all 300 candles
I pull data from coinex, its about ETH/USDT, timeframe is 5min
I attach a sample data as json here
will you please check it out?

[ethusdt.txt](https://github.com/DaveSkender/Stock.Indicators/files/7432056/ethusdt.txt)

**Comment by DaveSkender** [comment]
With just a quick look at your Close prices, here's what your chart looks like:

![image](https://user-images.githubusercontent.com/8432125/141394317-752844ec-85d1-4e07-ab6a-14268fba55f5.png)

Given the price around ~$4,000, a 5% range would mean you only plot swings > ~$200.  From your start point around $4,250 it continues to go down, without a 5% rebound, until it gets to the first confirmed bottom at $3,915 at bar number 224.

**Comment by DaveSkender** [comment]
Use a smaller change threshold, like 1.2%, and it would look like this:

![image](https://user-images.githubusercontent.com/8432125/141395424-9d09a270-83ac-4940-b677-1686b3302bc3.png)

**Comment by DaveSkender** [comment]
If you were to use a wider timeframe, 5% might look a bit better:

![image](https://user-images.githubusercontent.com/8432125/141396924-e1c64af6-f616-461e-87c9-b0f110a91a41.png)

Ref: https://schrts.co/bEtpQigk

**Comment by DaveSkender** [comment]
The basic issue in your use case is that you're not using enough quote history to have a meaningful ZigZag(5) drawn.
