### ISSUE TITLE
SAR Start Parameter

### ISSUE THREAD

**Issue by overstartup** [DaveSkender/Stock.Indicators#602]
I have a question, why SAR doesn't have start parameter?
![image](https://user-images.githubusercontent.com/56995550/139649023-40d1f4b7-2282-4fa4-81bb-6ec989403b80.png)

it is important to set stop lost.

**Comment by DaveSkender** [comment]
The short answer is that it is not needed, nor is is part of the original author's formula.  Welles Wilder developed this indicators in his book _New Concepts in Technical Trading Systems_.

The better question is:
> Why did the author of that non-standard customized version of Parabolic SAR decide to add a start parameter?

My answer: I don't know, I guess they think it's a good idea, you'll have to ask them.  The standard definition uses the acceleration factor as the starting and all subsequent step.

**Comment by overstartup** [comment]
Thank you very much for your reply,
I don't know too 😀. It seems all exchanges has it with start. So if it is possible please add new overload of it.

**Comment by DaveSkender** [comment]
TradingView is used by a lot of third parties because it’s free or inexpensive to add to your site, it’s really only one instance.

**Comment by overstartup** [comment]
thanks , that will be great

**Comment by DaveSkender** [comment]
@overstartup, what's your opinion on the naming of this new parameter?  I'm stuck between `initialStep` and `initialFactor`.  It's technically the starting `accelerationFactor`, but is usually the same as `accelerationStep`.  Leaning towards `initialFactor` or `initialAccelerationFactor`.

**Comment by overstartup** [comment]
Well, have seen it as a start parameter. I think if you just call it initstart is more clear to understand it.initstep is good too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DaveSkender** [comment]
This is now available in version 1.19.1
