### ISSUE TITLE
Feature to select moving average type in Stochastics

### ISSUE THREAD

**Issue by whatthejay** [DaveSkender/Stock.Indicators#603]
First, thank you for the great library.

Usually EMA is used when calculating Stochastics indicator.
But as EMA weighs more to latest price change, the oscillator changes very raplidly even when there's not much changes in the prices.
Will it be possible to offer an option to select MA type in GetStoch function?

Thanks.

**Comment by DaveSkender** [comment]
For [Stochastic Oscillator](https://en.m.wikipedia.org/wiki/Stochastic_oscillator), a simple moving average is used for the signal line (%D) only, not the oscillator itself.  Is that what you’re referring to?

**Comment by whatthejay** [comment]
Thanks for the answer. You're right, that was my misunderstanding.
EMA is used in the MACD and I was confused with Stochastics.
