### ISSUE TITLE
KDJ Calculation

### ISSUE THREAD

**Issue by kokazani** [DaveSkender/Stock.Indicators#612]
## the problem

I think that there is something wrong with the calculation of KDJ (GetStoch) or I miss something.
Is there anyone who has tried it and get the correct results?

## to reproduce

I am trying to calculate KDJ with (9 lookback, 3 signal, 3 smooth) for 1h candle chart of ETHUSDT.
In tradingview.com with Binance as source, we get for 

2021-Oct-11 08:00 **%J = 102.44**
2021-Oct-11 09:00 **%J = 105.89**

The corresponding results for these two candles calling GetStoch(9,3,3) for J values are completely different.  The data sample begins from 2021-Oct-1 00:00:00. 

Thank you in advance

**Comment by DaveSkender** [comment]
%J is a simple calculation = 3*%K - 2*%D

Have you checked to see if the TradingView calcs are okay?
I’d need more info to reproduce what you’re seeing and to determine where you’re having an issue.

**Comment by kokazani** [comment]
Thanks for the quick response. 
Of course I mean that the hypothetical issue is on %K and %D calcs and not in the %J calc formula as you mentioned above :)

Except from tradingview, I tried the Index on gate.io (in the build-in chart) too and the behavior of KDJ is exactly the same as tradingview's. 
From my dev side, I am connected to gate.io API and I retrieve data from there for my analysis. All the other indicators that I used from your library is 100% accurate except this one.

Back to our issue, the only thing that I saw, and I played around to find out what is the reason (with no result) is the different results from your library and the results from both sites.

Based on https://help.eaglesmarkets.com/hc/en-us/articles/900002690623-Calculation-method-of-KDJ-index-random-index-
I tried to figure out what may produce this difference on result by reading your code.

I don't think that the "If there is no K value and D value of the previous day, 50 can be used instead." makes so big deal. I have to read more carefully your code to understand what is the root of issue. Meanwhile, if you can take a look too, I ll appreciate it.

**Comment by DaveSkender** [comment]
That Eagles Market formula doesn't look right.  They're using a non-standard smoothing technique for the Stochastic parts.

Quickly looking at TradingView, here's the offending date you're referring to, using the "built-in" Stochastic indicator:

![image](https://user-images.githubusercontent.com/8432125/141399071-0e9c4c9e-0f07-4d52-86c6-c290d2b781b9.png)

%K = 88.01 and %D = 90.40 (see image above), so %J should be 3*88.01-2*90.40 = 83.23.  I've noticed there is no "built-in" KDJ indicator in TradingView, so you're probably using a "community script" .... watch out for those!  Might be unreliable.

**Comment by kokazani** [comment]
The build-in KDJ that I am using and referred to, is the one in gate.io charts. 
I gave the example of tradingview here because its free and easy-to-access from everyone to test, and of course has the same results as gate.io KDJ implementation. 

I understand that all implementations of KDJ in trading view are community scripts and only the Stoch is build-in.

My apologies for the gmt+2 dates that I gave.
The actual dates are 
2021-Oct-11 05:00 %J = 102.44
2021-Oct-11 06:00 %J = 105.89

You are right from the perspective of calculations based on Stoch formula (KD) and KDJ calculations that you provide. 
Is is interesting though that both sites for the KDJ they are using different but with same results formula. 
Obviously it is something different in smoothing.

I am closing this thread, If I find the way that they both calculate the KDJ I will post here the implementation to add it as feature based on params given if you want in your library.

Thank you

**Comment by DaveSkender** [comment]
Ok, thanks for checking.  I'm happy to take a closer look if we can find some more reliable source information on the formula.  I suspect there are 2-3 slightly different variants out there and it's going to be hard to determine which is the most correct one.  It's quite possible that Gate.io and TradingView either 1) randomly picked the same approach (group think), or 2) Gate.io is actually just using TradingView under the hood (this is common in crypto world).

If you do find another variant from a reputable source; it'd have to be either 1) a clear definitive source from the original author, that overrules all others, or 2) different enough to consider as a separate indicator -- I'd probably not put two nearly identical indicators in the library.

**Comment by preintel** [comment]
Without having the source code or underlying calculation of the external sites we would have to calculate the stochastic using the open/high/low/close values for the given days and then determine if the site is using a "fast" or "slow" stochastic to represent the K% and D% line, if they are showing the slow stochastic then the K% line is actually the D% line of the fast stochastic.
I would also be careful in the settings/parameters the equations are using as the J% may vary, some use EMA instead of SMA and can't easily tell which one they are using if they don't provide the equations unless you back calculate them to determine it.

https://docs.anychart.com/Stock_Charts/Technical_Indicators/KDJ
https://docs.anychart.com/Stock_Charts/Technical_Indicators/Mathematical_Description#kdj

**Comment by DaveSkender** [comment]
In our formula, setting `smoothPeriods=1` is Fast and `smoothPeriods`=3 is Slow for [Stochastic](https://daveskender.github.io/Stock.Indicators/indicators/Stoch/#content).

The AnyChart formula you've provided above implies that they use the Fast variant with a normal simple moving average for smoothing.  I see they left out some insight on what little `d` and `k` values to use for %J, any ideas?

![image](https://user-images.githubusercontent.com/8432125/141656479-6e508ecd-74d7-42fc-ada3-963b493a9b7a.png)

**Comment by DaveSkender** [comment]
In our formula, setting `smoothPeriods=1` is Fast and `smoothPeriods`=3 is Slow for [Stochastic](https://daveskender.github.io/Stock.Indicators/indicators/Stoch/#content).

The AnyChart formula you've provided above implies that they use the Fast variant with a normal simple moving average for smoothing.  I see they left out some insight on what little `k` and `d` values to use for %J, any ideas?  We're using static values of `3` and `-2`, which could potentially be parameterized.

![image](https://user-images.githubusercontent.com/8432125/141656479-6e508ecd-74d7-42fc-ada3-963b493a9b7a.png)

With that said, I'm wondering if KDJ might be served better as an entirely separate indicator, not directly tied to Stochastic in our library.  If we separated it, we'd be able to highly parameterize it with additional inputs, like (first three are same as Stoch):

- `lookbackPeriods` for %K
- `signalPeriods` (smoothing for %D)
- `smoothPeriods` for %K (for fast vs slow)
- `movingAverageType`  (SMA, SMMA, EMA, etc)
- `d` weight factor for %J
- `k` weight factor for %J

That should cover all the variants out there

**Comment by DaveSkender** [comment]
This advanced customization is available in version 1.19.1
