### ISSUE TITLE
HalfTrend Indicator

### ISSUE THREAD

**Issue by Salardx** [DaveSkender/Stock.Indicators#622]
Hi dave, great tools
Will you please add HalfTrend to your collection too?
https://www.tradingview.com/script/U1SJ8ubc-HalfTrend/

**Comment by DaveSkender** [comment]
Any information you have or can find from the original author would be appreciated.  I tend to not trust recreations and community contributors on TradingView or similar platforms.  I also like to do research to ensure that we only implement reputable indicators from recognized professionals or sources.  Help finding this info is much appreciated.

**Comment by DaveSkender** [comment]
Needs original source information.  I'm not yet comfortable with the reputation of this one.  Research leads me to a sketchy "free scalper indicator" marketing site + not a lot of convincing online discussion in reputable publications.

**Comment by DaveSkender** [comment]
This appears to be a recreation of a proprietary indicator from Karl Dittmann.

**Comment by DaveSkender** [comment]
Given all of the other opportunities and need to choose my battles, so am deciding not to implement this one, but will keep an eye on it to see if it becomes a more dominant indicator.

Salar, thank you for the recommendation.  Ideas always are welcome.
