### ISSUE TITLE
Get the Slope of any indicator in the library

### ISSUE THREAD

**Issue by preintel** [DaveSkender/Stock.Indicators#630]
For example if requesting any indicator the output is typically a series of time dependent values. Is there a "easy" solution that I can implement to calculate the first derivative (slope) of that indicator output or is that something that has to be manually coded for each indicator where I need to get the IEnumerable result then calculate each slope.

Would it be possible to add a shared method that can be inherited and can be called on any indicator output that will return a list of slope values at each possible point? For example if called on SmaResult output it will return a list of n-1 values of slope for each point except the first point of course.

**Comment by DaveSkender** [comment]
An extension utility method, like `results.CalcSlope(lookbackPeriod=1)` is possible, however, since we’re dealing with strongly typed results classes, we’d essentially be doing the exact same translation needed to reuse in the `GetSlope` indicator.

It’d have to be coded uniquely for each indicator in the same manner as our `ConvertToQuotes` helper utility.  It’s a lot of work to implement, though I’m sure we can start with a few obvious choices like SMA and EMA.

Are you ready to be an official code contributor?  I could use some extra help to implement these.

**Comment by preintel** [comment]
Not sure how much time I would have to commit to get this done. Any idea of how long it would take to code this for all indicators (including subindicator values, eg: separate slope of K/D/J lines of a KDJ indicator)?

If it is coded generically so it can perform different mathematical models aside from slope it can be more expandable in the future. For example if the method can take in the IEnumerable result and perform any mathematical manipulation to the dataset (for slope it would be straightforward: get value of lookback and current then determine the delta y/delta x). 

After some thought I am not sure how useful an actual slope calculation will be and thinking a %change calculation might be more useful. For example since a slope value returned will be dependent on the delta x (which is typically some set time interval, minutes/5 min/15 min/60 min/day/etc) this will return variable results depending on the indicator/stock price since the delta y does not correlate well with the delta x in most cases. Would we be able to code an extension that calculates the slope this way then normalizes it to be a value between -1 and +1 or -100 and +100, this can serve as a better oscillator value and is more useful.

For example if we calculate the slope of a stock that is trading at $1 and moves to $1.05 in one time interval that would be a +5% increase but would calculate a "slope" of (1.05 - 1.00)/1 = 0.05, whereas a stock trading at $200 and moves to $210 (+5% increase) would calculate a "slope" of (210-200)/1 = 10. Although in both cases the relative change in the two values was +5% the slope values does not represent the %change so maybe we should implement a %change slope instead? I need to think about this some more.

**Comment by DaveSkender** [comment]
> Any idea of how long it would take to code this for all indicators (including subindicator values, eg: separate slope of K/D/J lines of a KDJ indicator)?

I'd suggest starting with the primary indicator elements before exploring doing slope on all things.  Time commitment-wise, I think it would only be a few hours or so.  Essentially I'll have a working model done in a few, so all you'd need to do is copy code and tweak some property names × ~40 times.  I suspect we'd not need to cover all indicators; I think covering the moving averages first would be a start.

With that said, you raise some concerns here that are worth exploring before we commit to doing it.

**Comment by DaveSkender** [comment]
> After some thought I am not sure how useful an actual slope calculation will be and thinking a %change calculation might be more useful. For example since a slope value returned will be dependent on the delta x ...

Our [Slope](https://daveskender.github.io/Stock.Indicators/indicators/Slope/#content) indicator uses a [least squared method](https://en.wikipedia.org/wiki/Simple_linear_regression) to draw the best fit straight line through the specified `lookbackPeriod`.  That line can be described in the classic linear equation `y=mx+b` where `m` is the slope and is roughly on a scale of +/- 1.

Curiously, I'm not sure what happens with a `lookbackPeriod=1` setting.  I'll have to give that a try and see if it fails in some way.  There may be some room for improvement.  I'd like to test:

- [ ] Slope values sometimes exceed +/- 1, why?
- [ ] What happens with `lookbackPeriod=1`?  Is that even feasible with a least-squared method?

**Comment by DaveSkender** [comment]
> After some thought I am not sure how useful an actual slope calculation will be and thinking a %change calculation might be more useful.

See [Rate ofChange (ROC)](https://daveskender.github.io/Stock.Indicators/indicators/Roc/#content) indicator.

**Comment by DaveSkender** [comment]
@preintel I think I'm going to skip adding this for now.  Interesting idea, but probably not a good enough ROI to keep it in the backlog.  Let me know if you feel strongly otherwise.

**Comment by DaveSkender** [comment]
I'm reopening this because I keep thinking about Slope in several contexts.

1) It's important for trading algos and machine learning to understand if an indicator is moving up or down
2) I'm thinking about how to generally provide #320

**Comment by DaveSkender** [comment]
I think for this one, I'll want to try to add an extension method to the results class.

```csharp
// any indicator
var results = quotes.GetAnIndicator(...);

// get slope of one element
IEnumerable<SlopeResult> slopeOfElement = results.Slope("element name", lookbackPeriod);
```

Under the hood, we'd essentially be parsing this element down and using the existing internal CalcSlope() methods.

**Comment by tiger2014** [comment]
Can you restruct this function from seris of candle to any seris with date and numerical value?

so we can get the slope of any seris (for example: macd of MACD, signal of MACD, and so on.)

**Comment by DaveSkender** [comment]
I think so.  I'm still trying to decide on whether to use `struct`/`tuple` or a simple class structure.  `struct` is only _slightly_ more performant (I tested it in this use case), but less usable overall.  In any case, it wouldn't be difficult to add a special override to take in that format.
