### ISSUE TITLE
How to provide "history data" incrementally?

### ISSUE THREAD

**Issue by Gopichandar** [DaveSkender/Stock.Indicators#631]
In case If I'm computing RSI for a symbol for a period 1minute,  

Initial start, Consider I passed some 150 quote as history and computed the RSI values, If I want to include another incremental quote on it which was newly formed, Is that make sense to again pass the 151 quote to get the last RSI (as I already have the values for 150 quote).  

Any suggestions for me on this?  Thanks in advance.

**Comment by DaveSkender** [comment]
See #396 for discussion on this topic
