### ISSUE TITLE
Rsi: Value was either too large or too small for a decimal. 

### ISSUE THREAD

**Issue by 44m0n** [DaveSkender/Stock.Indicators#653]
### the problem

Sometimes an exception occurs when using the RSI Indicator. I think the value is too large for a Decimal because sometimes I get RSI values with more than 20 decimals (Last example: 95.54604824755205522087680710). 

Error message(s):

```bash
System.OverflowException: Value was either too large or too small for a Decimal.
                              at System.Number.ThrowOverflowException(TypeCode type)
                              at System.Decimal.DecCalc.SearchScale(Buf12& bufQuo, Int32 scale)
                              at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
                              at Skender.Stock.Indicators.Indicator.CalcRsi(List`1 bdList, Int32 lookbackPeriods)
```

### Steps to reproduce

1. What indicator and parameter arguments were used?
I'm using RSI with a lookBackPeriod of 2 and 5min candles on BTC.
2. Attach the historical quotes you used as JSON (preferred), CSV, or Excel file.
At this point I can't provide historical data. The given information should be enough, but if historical data is needed just tell me and I will try to provide it.

**Comment by DaveSkender** [comment]
This is actually really good timing for this bug to appear.  I've been doing some analysis to see where __reducing__ precision can be used to improve performance.  This may be an example of where we cannot do that.  See #649

Thank you for [intending to] provide the data, but I'm not seeing it attached.  Can you try again?

**Comment by DaveSkender** [comment]
I won’t be able to reproduce this without data, but #652 may resolve the issue, not sure.

**Comment by 44m0n** [comment]
I tried to reproduce this issue outside of my application, so I wrote a basic console app that calculates the RSI values of the same data from first application. But a something weird is happening. I can't reproduce the issue here. I thought maybe something was wrong with my main code and got a false error, but then I remembered that after submitting this issue, I stopped using the skender indicator to calculate the RSI and started to use another nuget package. And with this package, the issue is gone. Today I went back to skender indicator so I can reproduce this issue, but I can only reproduce it on my old application and not in the sample console app. I'm trying to find out if the decimal size is different from scenario (context) to scenario. Right now, I can't reproduce this issue on a new console application. I'm curious if after #652 is deployed, this issue will disappear. I will keep an eye on this.

**Comment by DaveSkender** [comment]
Give version 1.20.0 a try.  This should reduce the risk of overflow since we changed from using `decimal` to `double` data type for the RSI internals.  It makes it both faster and less likely to have that issue.  If you see it again, please do capture the historical quotes that caused it -- for the 2 years this library's been used, this is the first time this has been observed, so it has to be an extremely rare data scenario.

**Comment by DaveSkender** [comment]
With that said, I see you were trying other libraries.  Is there anything we can do to make this one better?
