### ISSUE TITLE
VWMA Indicator

### ISSUE THREAD

**Issue by Salardx** [DaveSkender/Stock.Indicators#655]
Hi dave,
Thank you for your tools, since VWMA is a standard tool (and not customized), will you please add it to your collection?
I read about it here
https://patternswizard.com/vwma-indicator/
There are some formulas in there you can use

**Comment by DaveSkender** [comment]
Yes, that looks like a good one to add.  It's similar to [VWAP](https://daveskender.github.io/Stock.Indicators/indicators/Vwap/#content) but different in that it does not use cumulative volume.  Thanks for the recommendation.

**Comment by Salardx** [comment]
is there any expectation on when its gonna get available?

**Comment by DaveSkender** [comment]
If you want an expectation, I'll say 3 weeks; and if you want it faster ... [consider becoming a contributor](https://github.com/DaveSkender/Stock.Indicators/blob/main/docs/contributing.md#readme)!  This work is not my day job, so I have to find extra time to contribute + I have a couple other things in [the backlog](https://github.com/DaveSkender/Stock.Indicators/projects/1) that I want to do first.

**Comment by DaveSkender** [comment]
This was released in version 1.20.0

**Comment by Salardx** [comment]
many thanks, you're awesome
