### ISSUE TITLE
Damn the [convergence] torpedos

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#656]
As a user who doesn’t care about convergence-related precision errors (see #215), I’d like to opt-out of the related extended minimum quote history threshold.

Requested from @Jammooly1 in [RSI discussion](https://github.com/DaveSkender/Stock.Indicators/discussions/224#discussioncomment-1784202)

This might be a global setting or a per-usage setting, but probably not an indicator parameter.  Consider also returning a null set series for incalculably small history.

Investigate:

- [x] [class attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/writing-custom-attributes).  Conclusion: too complicated to both implement and use.
- [x] [IDisposable](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) "using" for one-off usage.  Conclusion: only works with limited use cases and is not compatible with static classes.
- [x] other methods for changing runtime settings without the use of a config file.  Conclusion: trying with static global configurations, but don't love it due to thread-safety concerns; also, cannot find good alternatives and we really can't use config files as this somewhat relies on the caller application.

An example use case is to allow a new market issue (IPOs) to have indicators as early as they can be calculated, even if they're not entirely converged yet.

![image](https://user-images.githubusercontent.com/8432125/147420609-2757f3ae-2e30-4e39-9be5-b4a5a47468f1.png)

Open concerns:

- [ ] Running into constraints since we're using static classes that do not support independently threaded configurations, so the only option is to somehow gracefully set global configuration parameters.

**Comment by DaveSkender** [comment]
Does anybody have some thoughts on how to implement Attributes?  What I'd like to do, for example, is allow users to simply specify how quote history checking is handled by doing something like this:

```csharp
class MyStuff() {

  [QuoteCheck(QuoteCheckLevel.Min)]
  public static void UseMyIndicators(){
    var quotes = GetMyQuotes();
    var results = quotes.GetEma();
  }
}

```

**Comment by Jammooly1** [comment]
That sounds good.

An idea I had floating around included making the "damn the torpedoes" setting automatic whenever the quantity of quotes provided is less than desired for precision, and in order to notify a user it was used, you can add a field in the return object declaring whether is was used or not.

Example:
`RsiResult
{
    date: DateTime
    rsi: double
    damn_the_torpedoes: boolean
}`

The name for field should probably be different and shorter.

**Comment by myalgomate** [comment]
My suggestion is as below:

In EMA we have var results = quotes.GetEma();

We can add one more thing like ignoring the min period with the function name. like

var results = quotes.GetEma().IgnoreMinLookBackPeriod();

Or 
for new script IPOed if users know that 10 days data is there we can set as below
var results = quotes.GetEma().MinLookBackPeriod(10);

**Comment by DaveSkender** [comment]
The reason I like that Attribute method is that is requires users to knowingly understand and then opt-in to risky settings.  The problem I have is that I'm not sure exactly how to use Attributes provided on external classes or methods.  That would be my ideal approach.

> add a field in the return object declaring whether it [exception] was used or not

I like how this notifies the user, but not loving the extra overhead of carrying more data.  I'd also be concerned that it gets ignored and people use bad data unknowingly.

> var results = quotes.GetEma().MinLookBackPeriod(10);

This wouldn't work as an extension like this because the base method would have already run before the extension is even considered.  The base method needs to be informed somehow; and I really don't want to add parameter arguments for it.

**Comment by DaveSkender** [comment]
It's possible I'm just being too conservative.  I was looking back at the old TA_Lib docs and see that they basically had an opt-out approach, like our `.RemoveWarmupPeriods()` method that handled it all that business.

**Comment by myalgomate** [comment]
Another idea is like currently, we are directly using a Function like GetEMA().

Later first Class should be initialized with all the settings and then the function can be used.

**Comment by DaveSkender** [comment]
I think what I want to do is to remove the minimum history exception entirely, but add more emphasis in documentation to the use of the `.RemoveWarmupPeriods()` extension.  It's probably okay if someone does not supply enough data to calculate to just get a `null` set in return, instead of an exception.

For example, right now you will get a `BadQuotesException` if you provide less than `2×n` or `n+100` quotes, even though `n` is the minimum calculable lookback period threshold.

If I remove this check and exception, a user would then have to knowingly and intentionally opt-in to remove the aberrant convergence period values if they did not want them:

```csharp
int n = 20;

IEnumerable<EmaResult> results =
  quotes.GetEma(n)
     .RemoveWarmupPeriods(Math.Max(2*n, n+100));
```

My primary concern with implementing this now is that people who are relying on a `BadQuotesException` to gracefully handle these scenarios would no longer be getting those exceptions to handle and, if they're not paying attention to release notes, would unknowingly get unwanted [warmup] data.  I may delay implementing until v2, where major breaking will be more prevalent.

**Comment by DaveSkender** [comment]
Just to give you some history, the reason I implemented this in the first place is for two reasons:

1) I don't carefully monitor quote history size in my algo-trading system, so I needed feedback when insufficient data is provided,
2) I was seeing users always only provide minimum amounts of quotes (as if less is better) and were very often using unconverged warmup data.

**Comment by DaveSkender** [comment]
Lol.  I keep changing my mind on this one because I'm struggling to find a compromise solution that I like.
What do you think of this use case:

```csharp
// fetching [not-enough] quotes
IEnumerable<Quote> quotes = TestData.GetDefault(3);

// turn off the exception
Indicator.UseConfig(
    new IndicatorConfig
    {
        UseBadQuotesException = false
    });

// returns 3 dated records where Ema = null
// normally, this would throw a BadQuotesException
IEnumerable<EmaResult> ema = quotes.GetEma(5);
```

**Comment by DaveSkender** [comment]
I think I found the solution I like and causes less friction for users.  I'm going to entirely remove the use of `BadQuoteException` as I [mentioned above](https://github.com/DaveSkender/Stock.Indicators/issues/656#issuecomment-1013951341), but also add the [[Obsolete]](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute) attribute to it so anyone currently using it will get a warning that it is deprecated and point them to an explanation.

**Comment by DaveSkender** [comment]
`BadHistoryException` was removed in v1.21.0
