### ISSUE TITLE
"Rolling"

### ISSUE THREAD

**Issue by StevenFischerWI** [DaveSkender/Stock.Indicators#669]
Describe the problem and solution you would like.  Include reference materials (links, screenshots, etc).

If requesting a new indicator, please provide links to, or source information for, the original author's publication of the indicator recipe (i.e. avoid sending potentially deviant third-party reproductions, if possible).

Please delete this explanatory text when submitting.

**Comment by DaveSkender** [comment]
Replaced by #670
