### ISSUE TITLE
Heikin-Ashi CandleStick Pattern

### ISSUE THREAD

**Issue by moslem7026** [DaveSkender/Stock.Indicators#673]
hi dave , Thanks for your Great Library 
is it possible to convert `List<Quote>` from normal Candles to Heikin-Ashi ?

**Comment by DaveSkender** [comment]
Yes, this price transform is [already in the library](https://daveskender.github.io/Stock.Indicators/indicators/HeikinAshi/#content) and `List<Quote>` works the same as `IEnumerable<TQuote>`, they’re fully compatible.
