### ISSUE TITLE
add Chande Momentum Oscillator (CMO)

### ISSUE THREAD

**Issue by wclark17** [DaveSkender/Stock.Indicators#678]
Per the discussion:
https://www.investopedia.com/terms/c/chandemomentumoscillator.asp - This one has been around since 1994 and seems to be more established.

**Comment by DaveSkender** [comment]
Cool.  Adding to the backlog.  When I have more time, I'll have to double check to make sure this isn't the same things as our existing [Momentum Oscillator / ROC](https://daveskender.github.io/Stock.Indicators/indicators/Roc/#content).  Sometimes one thing has many names.

**Comment by NavjotSinghMinhas** [comment]
Hi @DaveSkender, Please assign the enhancement to me.
Will try my best to work on it.

Thanks

**Comment by DaveSkender** [comment]
It’s all yours!  Thanks for contributing ❤️

**Comment by DaveSkender** [comment]
This was added to v2.3.0

![image](https://user-images.githubusercontent.com/8432125/188789732-3ca62e9a-55e9-48db-912d-a96c72f1ff49.png)
