### ISSUE TITLE
Change validate functions

### ISSUE THREAD

**Issue by sporty81** [DaveSkender/Stock.Indicators#684]
I just want to suggest making a way to override the Validate functions. Using ValidateEma as an example, I may only care to find the EMA for the latest value based on a lookback period of 90. But your library wants basically 90 periods before the 90 back, which is 180. I don't even care about that data point.

There really needs to be a way to disable the validations via settings. I'm basically not even using the library and had to just copy the source out to remove the validate functions. Otherwise, it's an awesome looking library that I can't even use due to this.

Thanks!

**Comment by DaveSkender** [comment]
Yep, I hear you and am working on changing our approach with minimum history checks.  It is important to understand why that check exists -- and it has to do with data accuracy when using insufficient amounts of data.  

In any case, I'll have this fixed soon so you can override!

Checkout #656

**Comment by DaveSkender** [comment]
This has been resolved in v1.21.0
