### ISSUE TITLE
Chaiking Money Flow broken

### ISSUE THREAD

**Issue by olakemp** [DaveSkender/Stock.Indicators#691]
Hi, Thank you so much for this project! I've found it quite usefull. However, I tested **Chaiking Money Flow** indicator against Money Flow Index (MFI) and it does not at all reflect the price action. I tends to give weird negative results (atleast when market is bullish).

**Comment by DaveSkender** [comment]
Can you give me some data to review?

**Comment by olakemp** [comment]
Hi, yes certainly here is a sample of my data. Below you can see the chart from the said time period (2h utc timedifference)
![image](https://user-images.githubusercontent.com/98640373/151835896-25d46058-8461-46e4-b0b2-a3911beeba49.png)

[indicators.txt](https://github.com/DaveSkender/Stock.Indicators/files/7972571/indicators.txt)

The attached file has CMF values (CMF, CMV and CMM). As you can see Money Flow Index (MFI) fluctuates with price action but the CMF indicators present weird values sometimes going in the opposite direction, which lead me to believe there might be an error in the code. My code snippet is:

`                double Roc = Arg.GetRoc(10).Last().Roc.Value;
                double Cmf = Arg.GetCmf(14).Last().Cmf.Value;
                double Cmv = Arg.GetCmf(14).Last().MoneyFlowVolume;
                double Cmm = Arg.GetCmf(14).Last().MoneyFlowMultiplier;
                double Rsi = Arg.GetRsi(14).Last().Rsi.Value;
                double RsiSma = Convert.ToDouble(Arg.GetRsi(14).ConvertToQuotes().GetSma(14).Last().Sma.Value);
                double Adx = Arg.GetAdx(6).Last().Adx.Value;
                double Mdi = Arg.GetAdx(6).Last().Mdi.Value;
                double Pdi = Arg.GetAdx(6).Last().Pdi.Value;
                double Mfi = Convert.ToDouble(Arg.GetMfi(10).Last().Mfi.Value);`

The period length is 300n and timeframe is 60sec

**Comment by ooples** [comment]
So it looks like you are comparing two very different but similar indicators. I publish scripts on tradingview so I have some experience with this and Chaikin Money Flow oscillates between +1 and -1 and Money Flow Index oscillates between 0 and 100. Chaikin Money Flow can easily be negative even during bull markets. Let me know if you have any questions

**Comment by olakemp** [comment]
Yes but thats just the thing, it can go beyond -1 and 1 like extremely, here is what the above code snippet produced just now
ROC: -0,5070
CMF: -14,5923
MFI: 40,3953
RSI: 43,8279
RSI/SMA: 40,4009
ADX: 30,6206
PDI: 29,6953
MDI: 47,7529

**Comment by DaveSkender** [comment]
The [CMF formula](https://school.stockcharts.com/doku.php?id=technical_indicators:chaikin_money_flow_cmf) is not complicated, so you can check it manually against your raw quote data as well.  I’m happy to do that, but will need your raw quote data and info on your CMF parameters (if different from above) to do that.

**Comment by olakemp** [comment]
Hi, thank you I appreciate that! However, I found out that the problem was actually in my data. As far as I can say the indicator is working correctly sorry about that.
