### ISSUE TITLE
Please remove or rename the class Candle (if possible)

### ISSUE THREAD

**Issue by M22arius494** [DaveSkender/Stock.Indicators#712]
### the problem

The sudden introduction of a class "Candle" introduces troubles for a couple of my projects. It seems this class was internal in version 1.17.1 and has now made public. My own Candle class is tied to a database and cannot be easely converted/renamed. I'm sure my class can be renamed but any other name than Candle would not make any sense.

Error message(s):
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0104	'Candle' is an ambiguous reference between 'CryptoBot.Shared.Model.Candle' and 'Skender.Stock.Indicators.Candle'	CryptoBot.Shared	fileXyz.cs	160	Active

### the question/solution
Was this publishing a mistake or on purpose? (there's not much usefull properties in case of inheritance)

If on purpose: Would it be possible to rename the class Candle (filename=src\common\candles\models.cs) to something else? People can easely inherited it from the new name (or create a class candle).

As a quick fix I'm going to revert back to 1.17.1

Thanks,
Marius

**Comment by ooples** [comment]
There are a couple of easy solutions to this issue you are having. First you can do a namespace alias to differentiate your class and the Stock Indicators candle class by using the following to replace your current namespace reference

using SkenderCandle = Skender.Stock.Indicators.Candle;

Or for the more time consuming method you can create your own custom class and inherit the quote class and initialize it like it is done in the library

**Comment by M22arius494** [comment]
> 

Currently I'm using the IQuote for my candle (i have been migrating from other packages a couple of times). IQuote was the easiest way. Don't want to use more internals as I might migrate (experiment) with other indicator classes as well (its still compatible with TA lib for now)

Thanks for the quick fix. But after making 50 changes I'm not feeling very comfortable about it, it seems fix on fix just for name clashes. I had other conflicts as well so I'm going to rethink if i need to prefix my classes to avoid this stupid conflicts. Skender library does use kind of common names and its getting me worried they are going to clash with other packages as well (can't avoid them all together I guess).

Thanks again!
Marius

**Comment by endeffects** [comment]
I have the same issue with the lastest version, could you please move your model classes out of the Skender.Stock.Indicators namespace? something like Skender.Stock.Models so we don't run into such conflicts.

**Comment by DaveSkender** [comment]
I'll take a look at moving it to another namespace.  I'm not sure that will entirely fix the issue though, as it would still need to be public and would still conflict with your other external Candle property, albeit less often.

**Comment by DaveSkender** [comment]
I think what I'll do is simply rename class `Candle` to `CandleProperties` to reduce the occurrence of conflicts.  I know a lot of users use `Candle` synonymously with what I'm calling `Quote` in their generic types and elsewhere.

**Comment by DaveSkender** [comment]
This rename occurred in version 1.22.1
