### ISSUE TITLE
add Adaptive Moving Average

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#714]
But make sure it’s not already covered under a different name.

![image](https://user-images.githubusercontent.com/44271858/154012344-39475715-21e3-435a-afcb-090796efef82.png)

_Originally posted by @turok2000 in https://github.com/DaveSkender/Stock.Indicators/discussions/570#discussioncomment-2178818_

**Comment by turok2000** [comment]
This code is just a Schaff Trend Cycle with custom Kaufman Adaptive Moving Average as a smoother for the final result
I need it in this particular version - smoothed.
I ask for help in the implementation 
>Вторник, 15 февраля 2022, 21:40 +05:00 от cheatcountry ***@***.***>:
> 
> 
>You already have this moving average. This is the Kaufman Adaptive Moving Average
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <DaveSkender/Stock . Indicators/issues/714/1040500393 @ github . com> 
 
 
--
Тиму Джин
Отправлено из Почты  Mail.ru

**Comment by DaveSkender** [comment]
Making a note to consider this modified STC for #698, but nothing to do here specifically since KAMA is already in the library.
