### ISSUE TITLE
GetPivotPoints return null

### ISSUE THREAD

**Issue by overstartup** [DaveSkender/Stock.Indicators#719]
i just called GetPivotPointsmethod, it doesn't return any record. other methods are working fine. please check it if there any issue .
Candles.GetPivotPoints(candleVM.PivotsInterval, PivotPointType.Fibonacci);

**Comment by DaveSkender** [comment]
I'll take a look.  Can you provide the quotes ("Candles" in your depiction) that you're using?

**Comment by overstartup** [comment]
i get latest 100 candles:
`List<Quote> _candles = new List<Quote>();`

candleVM.PivotsInterval is a time period i'm using 3minutes,15minutes and1hour : 
    ```
    private PeriodSize pivotsInterval;
        public PeriodSize PivotsInterval
        {
            get { return pivotsInterval; }
            set
            {
                pivotsInterval = value;
                RaisePropertyChanged(() => PivotsInterval);
            }
        }

```

**Comment by DaveSkender** [comment]
It's only going to work with the enum options shown in the documentation (PeriodSize.Month, Week, Hour, OneDay) as the window size, by design.  Standard Pivot Points are based on these calendar "buckets", so overriding with some other rolling variant with custom periods wouldn't work in its current form.  I can explore this variant a bit more, but checkout [Rolling Pivot Points](https://daveskender.github.io/Stock.Indicators/indicators/RollingPivots/#content) as an option.

**Comment by overstartup** [comment]
i have changed my code to 
`Candles.GetPivotPoints(PeriodSize.ThreeMinutes, PivotPointType.Fibonacci);`

but it is still the same result, It returns the records with the correct date but with null values for P1,p2,..,s1,s2....

**Comment by overstartup** [comment]
i have tested it by all period sizes, it is just working with PeriodSize.Day and PeriodSize.OneHour.
there is any condition I have to check?

**Comment by DaveSkender** [comment]
Yes, it only works with the four period size options in the documentation, so the three minute one won’t work.  You’ll need more quotes history to get the longer two options to work.

**Comment by DaveSkender** [comment]
I've added some parameter validation here so users get better feedback when using alternates to the documented `windowSpan` values.

**Comment by DaveSkender** [comment]
I can take another look at it; however, I'm not yet sure how it would work in those time frames given that PP is intended to be based on a fixed calendar window and not a rolling window.

Please submit another Issue for the enhancement aspect, so it's under your name, for notification/tracking purposes.  And please do elaborate on how you'd expect it to work, and any references to source materials that might help explain.
