### ISSUE TITLE
Wrong description for Volatility Stop

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators#728]
Looks like there's a little mistake.

https://github.com/DaveSkender/Stock.Indicators/blob/c4c5bfa1ca76ec48e3c55c34ef7d5281e2eb43bf/src/s-z/VolatilityStop/info.xml#L5

**Comment by DaveSkender** [comment]
Oops 😬 
Thanks for reporting.  Will fix.
