### ISSUE TITLE
add [Wilder] ATR Trailing Stop

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#729]
In doing some research, I see this [ATR Trailing Stop](https://www.stockopedia.com/learn/charts-technical-analysis/atr-trailing-stops-462698/) is originally authored by Welles Wilder, so I should be able to find the original source recipe from his publications.

I think this pre-dates Oliver Seban’s SuperTrend and used close price where SuperTrend used HL2, but is otherwise identical, but need to verify.

_Originally suggested by @myalgomate in https://github.com/DaveSkender/Stock.Indicators/discussions/724_

**Comment by DaveSkender** [comment]
If this is identical to SuperTrend, I suggest making this as the original base method with a default `CandlePart` of Close, then reuse it for SuperTrend under the hood, for the sake of not being redundant.  Optional.

**Comment by DaveSkender** [comment]
This may just be Volatility Stop by another name.  If so, let’s just add the alias and update docs.

**Comment by DaveSkender** [comment]
> In looking at Wilder’s book _New Concepts in Technical Trading Systems_ I think this is actually just Volatility Stop by another name. If so, let’s just add the alias and update docs.

This is definitely not the same as Volatility Stop.  VS allows the trends to float up and down while ATR Trailing Stop and SuperTrend only allow them to move one way.

I'm still trying to see how this is different from SuperTrend.  I still think they are the exact same thing.

**Comment by DaveSkender** [comment]
I think what I’ll do here is create ATR Trailing Stop with new parameters to set 1) the baseline off of `CandlePart` and 2) the trigger off `EndType`  of High/Low or Close price.  I think SuperTrend is just the unique variant with `CandlePart.HL2` and `EndType.Close`, respectively.

**Comment by myalgomate** [comment]
Hi Dave,
IS ATR Trailing Stop added to our library...?

**Comment by DaveSkender** [comment]
> Hi Dave, IS ATR Trailing Stop added to our library...?

Not yet, no.  This issue represents the work to be done in our backlog and will be closed when it's been added.  We do have these very similar indicators in the library:

- Wilder's [Volatility Stop](https://daveskender.github.io/Stock.Indicators/indicators/VolatilityStop/#content)
- Wilder's [Parabolic SAR](https://daveskender.github.io/Stock.Indicators/indicators/ParabolicSar/#content)
- Seban's [SuperTrend](https://daveskender.github.io/Stock.Indicators/indicators/SuperTrend/#content)

**Comment by myalgomate** [comment]
Hi Dave,

Greetings for the day.
Hope you are doing well.

Just wanted to know when are you planning for this indicator.

Thanks a lot in advance 🙏

**Comment by DaveSkender** [comment]
This was released in v2.3.0

![image](https://user-images.githubusercontent.com/8432125/188789961-f9f7965d-fac8-4199-a6ed-6e3f22bf885b.png)
