### ISSUE TITLE
Indicator.GetEma 20 and 50 report wrong values compared to TradingView

### ISSUE THREAD

**Issue by M22arius494** [DaveSkender/Stock.Indicators#738]
apples and peers..

**Comment by DaveSkender** [comment]
It's hard to say what TV is doing.  A few things I always tell people to watch out for:

1. Different charting systems may use a slightly different formula, so they don't always make for a great basis of comparison.
2. They may also use different underlying quote histories that are not identical to what you might be using in this library.  Crypto data is especially inconsistent amongst providers.
3. Make sure you are providing enough historical quotes to the library to get past the [warmup and convergence periods](https://github.com/DaveSkender/Stock.Indicators/discussions/688).  It can take 200 or more unusable periods before calculations converge to better precision.
