### ISSUE TITLE
DEMA and TEMA - early calculations

### ISSUE THREAD

**Issue by mihakralj** [DaveSkender/Stock.Indicators#770]
Current implementation of DEMA/TEMA (Double and Triple EMAs) is unnecessarily laggy.

- **EMA:** calculate SMA of initial [period] data and then calculate each subsequent value by using k=2.0/(p+1) weight.
- **DEMA:** calculate SMA of initial [period], calculate EMA and EMA(EMA) of each next period
- **TEMA:** calculate SMA, then calculate EMA, EMA(EMA) and EMA(EMA(EMA) of each next period

Implementation here is recalculating SMA of EMA (for DEMA), and SMA of EMA of EMA (for TEMA), generating usable bars 3*period later than it could. This same bug appears in TA-LIB, but is not present in Pandas-TA - or other libraries.

After about 60 bars (for DEMA) or 100 bars (for TEMA) both algos completely converge into a same series, so this issue is minor and visible only to users that would like to use TEMA as early as possible and not wait for 3*period of warmup data.

**Comment by DaveSkender** [comment]
I’ll take a look.  Thanks for finding/posting.  Sounds like there may be a mathematical shortcut to the same result with a shorter warmup window.

I usually source formulas for original authors, but suspect others may do it differently.  These are on [Wikipedia](https://en.m.wikipedia.org/wiki/Double_exponential_moving_average).

Probably more of an enhancement than a bug though, right?

**Comment by mihakralj** [comment]
Check my validation tests [here](https://github.com/mihakralj/QuantLib/tree/main/Tests/Series) for DEMA/TEMA. They all pass (comparing my DEMA/TEMA with yours and with TA-LIB) - but I feed it 1,000 bars. Tests fail at 100-200 bars.

**Comment by DaveSkender** [comment]
Just took a look.  I like the way you’re suggesting to shorten the warmup window.  I’m simply reusing the existing EMA method to avoid duplicating code, but this improvement makes sense and still honors the fundamental math correctly.

**Comment by DaveSkender** [comment]
I'm running a convergence analysis on DEMA right now and starting earlier doesn't seem to improve the actual rate of convergence to accuracy at all.  The only _benefit_ is that you get more less-accurate warmup data.

**Comment by DaveSkender** [comment]
This will be available in the next version.
