### ISSUE TITLE
KAMA indicator - early values

### ISSUE THREAD

**Issue by mihakralj** [DaveSkender/Stock.Indicators#778]
I was comparing my KAMA() with your KAMA() and noticed that you are not generating KAMA outputs until erPeriods - meaning that KAMA(5) will completely ignore and discard values [1-4] [(see lines 72+)](https://github.com/DaveSkender/Stock.Indicators/blob/main/src/e-k/Kama/Kama.cs)

I find wasting perfectly good early data unacceptable - and am trying to find the reason for that implementation. I dug out several sources that I deem authoritative (not TV or stockcharts) and I cannot find any KAMA model that would start calculation on the _Period_ bar

https://corporatefinanceinstitute.com/resources/knowledge/trading-investing/kaufmans-adaptive-moving-average-kama

https://www.tutorialspoint.com/kaufman-s-adaptive-moving-average-kama-formula-and-how-does-it-work

**Comment by DaveSkender** [comment]
I’ll take a deeper look, but I’m sure that segment didn’t pass my definition of “perfectly good” for a reason.  Checkout my [manual calculation spreadsheet](https://github.com/DaveSkender/Stock.Indicators/tree/main/tests/indicators/e-k/Kama).  It might help.

**Comment by DaveSkender** [comment]
@mihakralj any final thoughts on this before I close it out?

**Comment by mihakralj** [comment]
I didn't check sources yet - but what you are saying is that all values where n < erPeriods are completely ignored - there is no SMA() calculated (like what EMA does) or anything like that? The first value that actually enters the series is n=erPeriods and it is not average, it is the value of input at n=erPeriods?

**Comment by DaveSkender** [comment]
The numerator for the ER calculation, part of the KAMA formula is | p<sub>t</sub> − p<sub>t−n</sub> |, where n=erPerods

**Comment by DaveSkender** [comment]
I think we’re doing the right thing here, but let me know if you still feel otherwise.  Thanks for the note nonetheless, I like to review these periodically.
