### ISSUE TITLE
MACD use diffrent CandlePart

### ISSUE THREAD

**Issue by tiger2014** [DaveSkender/Stock.Indicators#785]
Now, the project only uses CandlePart.Close for MACD. 
 Can you add a param in the MACD method? I can add in my project, but I hope you can add it for I dan't want to add somthing the the libary.

Thanks

**Comment by DaveSkender** [comment]
I'll add it to the backlog, thanks for recommending.

**Comment by DaveSkender** [comment]
I see you’ve modified this for yourself in #787.  Fork the repo and submit a [contribution](https://github.com/DaveSkender/Stock.Indicators/blob/main/docs/contributing.md)!  We’re always looking for help.
