### ISSUE TITLE
MACD is not consisten with TradeView

### ISSUE THREAD

**Issue by tiger2014** [DaveSkender/Stock.Indicators#787]
### the problem

when using the same params, macd gold cross is not consistent with what is TradeView 

![image](https://user-images.githubusercontent.com/6703612/165407256-39047b33-8de2-412c-a484-1f82b7bda051.png)
![image](https://user-images.githubusercontent.com/6703612/165407285-acf329e0-1154-48ed-b84c-cb3cb776dad7.png)

the first column on the screenshot of the console output is the time I buy the stock (it should be the K line which generating macd gold cross ), but it is sometimes later or earlier than what is generated by the Stock.Indicator

the code:

`List<MacdResult> macd = quotesList5m.GetMacd(5, 34, 5, CandlePart.OHLC4).ToList();`
`........`
`bool buy = macd[i - 1].Histogram < 0 && macd[i].Histogram > 0`

when the boll buy == true, I will buy stocks.

I use ES in this case, but you can use any stock to reproduce the issue.

**Comment by DaveSkender** [comment]
There’s several aspects here that you should check:

1. Your customized addition of OHLC4 is not doing something unusual.  TradingView is probably using Close price.
2. You’re providing enough historical quotes to surpass the less-accurate [warmup and convergence](https://github.com/DaveSkender/Stock.Indicators/discussions/688) periods
3. TradingView is using the same exact data as you’re providing to the library
4. TradingView is correct — I’ve seen cases where it is not right

**Comment by tiger2014** [comment]
1. I also use OHLC4 in the strategy of the screenshot on TradeView 
2. I have used enough data 
3. I can't check this, but I think it is probably that the data I used is not the same as TradeView. But I can't verify it.

**Comment by tiger2014** [comment]
By the way, do you have any free and trusted stock data sources to share? Thanks

**Comment by DaveSkender** [comment]
Here’s a few data sources: https://github.com/DaveSkender/Stock.Indicators/discussions/579

**Comment by DaveSkender** [comment]
Let me know if you still have unresolved issues
