### ISSUE TITLE
stock chart for backtest

### ISSUE THREAD

**Issue by tiger2014** [DaveSkender/Stock.Indicators#789]
I noticed that your website has a stock chart which can show the indicator on/below the chart.

Can you add it to the backtest project, so we can see the result directly on the chart?

Thanks!

**Comment by DaveSkender** [comment]
I don’t have a backtest project yet, but will keep visualizations in mind when I do.  It currently demo site shows the indicators only.  Most of them.

**Comment by tiger2014** [comment]
I find a sample of [backtest project](https://github.com/DaveSkender/Stock.Indicators/tree/main/docs/examples/Backtest) in your document folder
