### ISSUE TITLE
money flow index

### ISSUE THREAD

**Issue by RajeshDhalange** [DaveSkender/Stock.Indicators#80]
Hi,
First of all thanks for this awesome library.
Do you have any plan to create MFI indicator?

**Comment by DaveSkender** [comment]
Sounds like a good one to add.  I’ve added it to the backlog and will try to work on it in the next few days.  If you are interested in contributing this code yourself, let me know and please review the contributing guidelines.

AB#709

**Comment by DaveSkender** [comment]
I’m going to try and add one or two more indicators from the backlog before publishing a new package to NuGet, likely in the next 24-48 hours.

**Comment by DaveSkender** [comment]
This was published in package version 0.9.1
