### ISSUE TITLE
Possible bug: Indicators are not working to India Market Index

### ISSUE THREAD

**Issue by zenconix** [DaveSkender/Stock.Indicators#800]
Hi Dava,
I have tried to use library to India market index  BANK NIFTY (aka NIFTY BANK). I tried with 5 min time frame and cross checked in Trading view but seems result is not same. Could you please help to check? 

### to reproduce

1. What indicator and parameter arguments were used? - RSI(14), Moving average(10) and ADX(14)  
2. Attach the historical quotes you used as JSON (preferred), CSV, or Excel file. - 
[quote.txt](https://github.com/DaveSkender/Stock.Indicators/files/8647193/quote.txt) 
quote.txt file contains data from  2022-05-06 09:20:00 to 2022-05-06 15:30:00 in interval of 5 min. 
as I was not able to upload JSON file, uploading text file instead, please rename file extension to json. 

I have tried with simple function to calculate values as below. 

 ```
public void CalculateRSI(int length)
        {

            IEnumerable<Quote> quote = GetData.GetHistoryFeed();
            IEnumerable<RsiResult> result = quote.GetRsi(length);
            Console.WriteLine("RSI Result ::");

            foreach(RsiResult rsiResult in result)
            {
                Console.WriteLine("RSI was {0} on {1}", rsiResult.Rsi, rsiResult.Date); 
            }
        }

        public void CalculateEMA(int length)
        {
            IEnumerable<Quote> quote = GetData.GetHistoryFeed();
            IEnumerable<EmaResult> result = quote.GetEma(length);
            Console.WriteLine("EMA -----------");
            foreach(EmaResult emaResult in result.TakeLast(10))
            {
                Console.WriteLine("EMA was {0} on {1}", emaResult.Ema, emaResult.Date);    
            }

        }

        public void CalculateADX(int length)
        {
            IEnumerable<Quote> quote = GetData.GetHistoryFeed();
            IEnumerable<AdxResult> result = quote.GetAdx(length);
            Console.WriteLine("ADX result");

            foreach(AdxResult adxResult in result.TakeLast(10))
            {
                Console.WriteLine("ADX was {0}, positive DI{1}, negative DI{2} on Date: {3} ", 
                    adxResult.Adx, adxResult.Pdi, adxResult.Mdi, adxResult.Date);
            }

        }
```

But result is not same as tradingview's chart at link below. 
https://www.tradingview.com/chart/ZewoKRga/

**Comment by DaveSkender** [comment]
I suspect you're probably not using enough historical quotes to exceed the warmup periods.  We also have no way of validating your source of comparison to ensure the issue is not in their system; sometimes it's helpful to compare your source to other sources as well.

Check for issues in your implementation and let us know if you're still having problems.  Here's some helpful tips: #801

**Comment by zenconix** [comment]
Hi Dava,
I was not providing enough historical quote before. Now I have added lot many data and results seems improved. 

thank you for your help.
