### ISSUE TITLE
Bad Renko chart directional transition

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#812]
When there is a Renko transition, the brick is one brick size off in vertical position.

From @shinel70:
here is a picture i try to explain my problem 
![get renko](https://user-images.githubusercontent.com/46675285/169690633-85fde08d-c41c-4d81-8496-16d6003dff4a.jpg)
`
using Binance.Net.Clients;
using Skender.Stock.Indicators;
BinanceClient bc = new();
var data = await bc.UsdFuturesApi.CommonFuturesClient.GetKlinesAsync("BTCUSDT", TimeSpan.FromMinutes(1));
List<Quote> quotes = data.Data.Select(k => new Quote
{
    Open = k.OpenPrice.Value,
    High = k.HighPrice.Value,
    Close = k.ClosePrice.Value,
    Low = k.LowPrice.Value,
    Date = k.OpenTime,
    Volume = k.Volume.Value
}).ToList();
var renkoResult = quotes.GetRenko(10);
Console.ReadLine();`

_Originally posted by @shinel70 in https://github.com/DaveSkender/Stock.Indicators/discussions/478#discussioncomment-2798709_

**Comment by DaveSkender** [comment]
This should look like this:
![image](https://user-images.githubusercontent.com/8432125/169710756-038d50d4-c4a7-4198-bd90-0be4ff9c62ef.png)

But currently looks like (ignore the wicks):
![image](https://user-images.githubusercontent.com/8432125/169711074-0b0c71c8-ef10-462b-ab97-83546617172f.png)

**Comment by btwomey873** [comment]
Dave,

I'd like to give this one a try.  I'll provide my initial thought process once I look into it.

**Comment by DaveSkender** [comment]
Go for it, and thank you!

**Comment by DaveSkender** [comment]
@btwomey873 are you progressing well on this one?  Since this is an actual bug, I'd like to prioritize a fix for it so it does not persist in the library.

**Comment by DaveSkender** [comment]
@btwomey873 let me know if you're working on it and plan to submit a fix soon; otherwise, I'll start working on it.  I don't like to leave bugs open for long periods of time.

**Comment by DaveSkender** [comment]
This fix was implemented in v2.2.0
