### ISSUE TITLE
Doji is only None or Neutral

### ISSUE THREAD

**Issue by heavymanto** [DaveSkender/Stock.Indicators#814]
### to reproduce
```
ohlc.GetDoji().Condense()
```

### the problem

Hi, I don't understand why the doji signal has a unique neutral state. From the code you can clearly see that it is initialized to NONE and if the match condition becomes Neutral. How is there never a bearish / bullish ? thank you

![image](https://user-images.githubusercontent.com/6449169/170035444-4ca85ab4-7e79-4f7c-ac47-a3b569130f85.png)

**Comment by DaveSkender** [comment]
@heavymanto are you okay with this response?

**Comment by heavymanto** [comment]
ok, thanks
