### ISSUE TITLE
Provide Default Parameter Sets and Improve Validators

### ISSUE THREAD

**Issue by endeffects** [DaveSkender/Stock.Indicators#816]
Please provide default parameter sets for common timeframes (h1, h4, d1) on each indicator and make your validators more restrictive. Currently its possible to pass senseless parameter combinations where one parameter belongs to the value of an other. This would improve the possibility to brute force the best fitting setting for an indicator on a specific asset.

**Comment by DaveSkender** [comment]
Which indicator?  I need more context, and maybe an example.

**Comment by DaveSkender** [comment]
@endeffects without more info from you, I’m not going to be able to assess your request.  Closing, but will reopen if needed.
