### ISSUE TITLE
allow access to internal tools

### ISSUE THREAD

**Issue by burakoner** [DaveSkender/Stock.Indicators#818]
Hi.

Is it possible to make `internal` access modifiers to `public` in helper methods as below

- BasicData.Utilities.cs methods
- Candles.cs methods
- Quote.Models.cs QuoteD class
- Quote.Utilities.cs internal methods
- Functions.cs internal methods
- NullMath.cs internal methods.

Have a nice day

**Comment by DaveSkender** [comment]
It is possible, but I'd need to review these individually to see if it's good to expose those internal tools.  I'm already planning to expose some of these, along with planned new features; for example, allowing the use of `IEnumerable<QuoteD>` as an input option.

Were there specific items that you want to use, or are you just making a general statement about protecting internal methods?

**Comment by burakoner** [comment]
In fact, I want to edit some indicators. For example Pivot Points. There must be 5 resistances and 5 supports but there are only for in your library. I want to write some indicator extensions using your code style. So I need those methods :) Pivot points are only an example by the way. I want to be free if I add extra indicators. I dont want to duplicate your methods to my workspace.

Have a nice day

**Comment by DaveSkender** [comment]
That makes sense, especially for [custom indicators](https://daveskender.github.io/Stock.Indicators/custom-indicators/#content).  Regarding Pivot Points specifically, we do have an open feature request to extend to 5 levels, see #815

**Comment by burakoner** [comment]
Thank you very much. As I said PP is only one reason to access those tools.
I saw https://github.com/DaveSkender/Stock.Indicators/issues/815 issue. I'ii share my old PP formula codes on that issue. I hope they will help you.

Thank you.

**Comment by DaveSkender** [comment]
> Thank you very much. As I said PP is only one reason to access those tools. I saw #815 issue. I'ii share my old PP formula codes on that issue. I hope they will help you.

I generally don’t use third party code as a source of truth.  Do you have a written publication source from a recognized industry pro, like a book?

**Comment by burakoner** [comment]
I just want to help for P5 S5 formulas. I didnt mean you to use them.

**Comment by DaveSkender** [comment]
This was mostly implemented in v2.2.0
