### ISSUE TITLE
info - Gator Oscillator

### ISSUE THREAD

**Issue by heavymanto** [DaveSkender/Stock.Indicators#819]
hello, sorry I did not understand how to determine the color of the green / red of candles. 
Consequently I would like to establish the four main states:

- Sleeping (exhausted)
- Awakening (forming)
- Eating (strengthening)
- Sated (running out of momentum)

https://learn.tradimo.com/technical-analysis-how-to-work-with-indicators/the-gator-oscillator#:~:text=Summary&text=%E2%80%A6%20the%20Gator%20oscillator%20is%20an,)%20and%20sleeping%20(exhausted).

**Comment by DaveSkender** [comment]
It’s definitely possible with current values, as I’ve charted those colors in our doc site charts with the library, but I can explain better in docs.  I’ll also take a look at adding those recommended helper calculated values too.  I may add the extra analysis as an extension though, if there’s any noteworthy cost to performance.

![](https://daveskender.github.io/Stock.Indicators/assets/charts/Gator.png)
