### ISSUE TITLE
Parabolic SAR in fifteen minute result is giving wrong values

### ISSUE THREAD

**Issue by Erdogan34** [DaveSkender/Stock.Indicators#821]
Hi, thanks for this great library. I need a help about SAR indicator. When I try to get result of the SAR indicator in one minute, it’s good but values are wrong in fifteen minutes. What may be reason and how can I achieve right SAR values in 15m?

IEnumerable results = quotes.GetParabolicSar(.02, .2, .02);

**Comment by DaveSkender** [comment]
The output is directly correlated to the quotes you provide, so putting 15-minute bars will calculate differently than when you put in 1-minute bars (they're not supposed to be the same).  Can you clarify what you were expecting and why you suspect it's wrong?

**Comment by Erdogan34** [comment]
I'm sorry, my bad. It was about socket data management problem. I was giving socket data inaccurate. Could you advise blog post or article about this, please?

**Comment by DaveSkender** [comment]
I don't have a blog post in mind regarding WebSocket data management, but do expect to look into this further as I'm currently working on an experimental incremental indicator calculation model that is designed for streaming data use cases.
