### ISSUE TITLE
zero doesn't equal one here

### ISSUE THREAD

**Issue by HypsyNZ** [DaveSkender/Stock.Indicators#826]
Why not set `i=1` then you only have to subtract once instead of add twice

https://github.com/DaveSkender/Stock.Indicators/blob/4589861fe8187b90d10c0460c0d4b7f89450d30e/src/a-d/BollingerBands/BollingerBands.Series.cs#L18

https://github.com/DaveSkender/Stock.Indicators/blob/4589861fe8187b90d10c0460c0d4b7f89450d30e/src/a-d/BollingerBands/BollingerBands.Series.cs#L27

https://github.com/DaveSkender/Stock.Indicators/blob/4589861fe8187b90d10c0460c0d4b7f89450d30e/src/a-d/BollingerBands/BollingerBands.Series.cs#L33

unless I'm missing something, Yes, I know we usually start at 0.

**Comment by HypsyNZ** [comment]
Oh

**Comment by HypsyNZ** [comment]
I notice in a lot of places you have i + 1 being repeated over and over in loops

why not just set i=1 from the start instead of i=0 it will make a difference in large workloads.

https://github.com/DaveSkender/Stock.Indicators/blob/4589861fe8187b90d10c0460c0d4b7f89450d30e/src/a-d/BollingerBands/BollingerBands.Series.cs#L18

https://github.com/DaveSkender/Stock.Indicators/blob/4589861fe8187b90d10c0460c0d4b7f89450d30e/src/a-d/BollingerBands/BollingerBands.Series.cs#L27

https://github.com/DaveSkender/Stock.Indicators/blob/4589861fe8187b90d10c0460c0d4b7f89450d30e/src/a-d/BollingerBands/BollingerBands.Series.cs#L33

**Comment by DaveSkender** [comment]
Because `i=0` is needed.  If you look closer at what's happening at each level of that looping structure in your example, you'll see why `i=0` is needed.

But perhaps I'm not understanding your suggestion.  It might help if you made a Fork/Pull Request proposal with your fixes, to just that Bollinger Band file.

I agree that this `i+1` looks funny, and I'm opportunistically re-writing some of those.  For example, `i+1 < lookbackPeriods` can be rewritten as `i < lookbackPeriods - 1`.

Some history:  I used to have an unnecessary "helper" variable called `index=i+1` to make this look nicer but eventually eliminated it for simplification -- so it was a find/replace for that variable.

**Comment by DaveSkender** [comment]
I was just looking at this closer because I've not been happy with the whole `i+1` syntax either.  It's confusing to me.  I think I understand what you're suggesting.  Here's a before/after explanation:

### previous
```csharp
for (int i = 0; i < tpList.Count; i++)
{
    (DateTime date, double value) = tpList[i];
    var index = i + 1;
    [..]
    if (index >= lookbackPeriods) { .. }
```

### current
```csharp
for (int i = 0; i < tpList.Count; i++)
{
    (DateTime date, double value) = tpList[i];
    [..]
    if (i + 1 >= lookbackPeriods) { .. }
```

### proposed
```csharp
for (int i = 1; i <= tpList.Count; i++)
{
    (DateTime date, double value) = tpList[i - 1];
    [..]
    if (i >= lookbackPeriods) { .. }
```

I like your suggestion here as it solves my original problem [getting rid of `index`] in a bit of a more intuitive manner.  To me, this is more about readability than any observable performance improvement.  I'd be surprised if we could even reliably measure the performance difference.

**Comment by DaveSkender** [comment]
I've started this change and created a draft Pull Request, but am currently working on other items.  If anyone is interested in adding to this change by refactoring other indicators with the same convention, please do a forked contribution Pull Request to the [refactor-index](https://github.com/DaveSkender/Stock.Indicators/tree/refactor-index) branch.  The unit tests will let us know if you did it wrong.  Help wanted.

**Comment by HypsyNZ** [comment]
```cs
public static partial class Indicator
{
    internal static List<BollingerBandsResult> CalcBollingerBands(
        this List<(DateTime, double)> tpList,
        int lookbackPeriods,
        double standardDeviations)
    {
        // check parameter arguments
        ValidateBollingerBands(lookbackPeriods, standardDeviations);

        // initialize
        List<BollingerBandsResult> results = new(tpList.Count);

        // roll through quotes
        for (int i = 1; i < tpList.Count; i++)
        {
            (DateTime date, double value) = tpList[i];

            BollingerBandsResult r = new()
            {
                Date = date
            };

            if (i >= lookbackPeriods)
            {
                double[] window = new double[lookbackPeriods];
                double sum = 0;
                int n = 0;

                for (int p = i - lookbackPeriods; p <= (i - 1); p++)
                {
                    (DateTime _, double pValue) = tpList[p];
                    window[n] = pValue;
                    sum += pValue;
                    n++;
                }

                double? periodAvg = sum / lookbackPeriods;
                double? stdDev = Functions.StdDev(window);

                r.Sma = periodAvg;
                r.UpperBand = periodAvg + (standardDeviations * stdDev);
                r.LowerBand = periodAvg - (standardDeviations * stdDev);

                r.PercentB = (r.UpperBand == r.LowerBand) ? null
                    : (value - r.LowerBand) / (r.UpperBand - r.LowerBand);

                r.ZScore = (stdDev == 0) ? double.NaN : (value - r.Sma) / stdDev;
                r.Width = (periodAvg == 0) ? double.NaN : (r.UpperBand - r.LowerBand) / periodAvg;
            }

            results.Add(r);
        }

        return results;
    }
```
You don't change `i` you just read it and add `1` temporarily

If ` tpList.Count` is `1` then its wrong and should just return

**Comment by DaveSkender** [comment]
`(DateTime date, double value) = tpList[i - 1];` would be needed to get the first price, since the array starts at zero, right?

**Comment by HypsyNZ** [comment]
yes, that is correct, so it will only remove 1 operation per loop instead of 2.

**Comment by HypsyNZ** [comment]
` var index = i + 1;`

I do like this idea, But it isn't what I meant.

Great work btw.

**Comment by DaveSkender** [comment]
0 based arrays have always bothered me.  It’s confusing from a human intuition perspective, but get why binary counting works that way.  The 1st record isn’t the 0th record, right?

I’ll keep looking for better ways of writing it.  Room for improvement, even if just for readability.  At any rate, thanks for reporting.

**Comment by HypsyNZ** [comment]
No problem, It also just occurred to me that this would throw if `i` was `max-int`, probably not a real concern but if you subtracted instead it could never be an issue

**Comment by HypsyNZ** [comment]
![](https://user-images.githubusercontent.com/54571583/174533865-5cd3010c-bf6c-4c75-b393-bbde16fd6aa4.png)
