### ISSUE TITLE
Examples don't run

### ISSUE THREAD

**Issue by robroy1234** [DaveSkender/Stock.Indicators#828]
I loaded the examples in visual studio.  I have errors about not targeting dot net 6.0 or targeting it. It won't compile. I tried installing 6.0.  I not sure if it wants core or not or what is what.  It's confusing . Please help.

**Comment by DaveSkender** [comment]
.NET 6.0 requires a minimum of [Visual Studio 2022 edition](https://visualstudio.microsoft.com/downloads/).  You may need to upgrade.

**Comment by DaveSkender** [comment]
> Dave: Out of curiosity, what motivates you to do all this work and provide it for free? There must be some sort of financial incentive, right? Thanks. Rob

I think my motivation boils down to the premise of open-source:
- Call me weird, but it’s fun and I like helping people in this community!  I measure success here on how well users can incorporate this library to make great things, together.
- I’m far along enough in my career that money is not my core goal.  I have a day job that I also love, to support any needed income.
- Projects like this are also useful in honing skills and learning from the community.  It’s made me a better developer.
- We’re all going to get rich by using these tools, right? 😀

With that said, I do accept [donations for coffee and beer](https://github.com/sponsors/DaveSkender) as encouragement and tokens of appreciation.

**Comment by robroy1234** [comment]
I know i'm going to get rich from the tools.  Thanks, Dave!

**Comment by robroy1234** [comment]
Dave, it doesn't appear that I can call an SMA by an index value?  How am I
supposed to access the values?

[image: image.png]

**Comment by robroy1234** [comment]
Ah, thank you.

**Comment by robroy1234** [comment]
Dave:

It seems like your MACD indicator gives a different value from
Ninjatrader's.  These are the standard settings on both.

[image: image.png]

**Comment by robroy1234** [comment]
Hi Dave:

How do you get the slope of K in a stochastic?  First line is NinjaTrader.
Second line is me trying to use your GetSlope method.

//if (Slope(Stochastics(3, 5, 2).K, 1, 0) < 0.5 &&
            if (stochastic352.GetSlope(1).Last().Slope.Value < 0.5 &&

**Comment by DaveSkender** [comment]
> It seems like your MACD indicator gives a different value from
Ninjatrader's.  These are the standard settings on both.

See #801.  In short, I'm not going to spend a lot of time debugging other systems to uncover their issues, so you'll have to do some work here to isolate the problem before I can act on it.

> How do you get the slope of K in a stochastic?  First line is NinjaTrader.
Second line is me trying to use your GetSlope method. [above]

%K is just an alias for the Oscillator line in Stochastic.  It's [the default and basis for chaining](https://github.com/DaveSkender/Stock.Indicators/blob/90532a500de43ecb13aa59ee93895c13dffeca71/src/s-z/Stoch/Stoch.Models.cs), so this is easy:

```csharp
var results = quotes.Stochastic(...);
var slopeK = results.Slope();

# or in one step
var slopeK = quotes.Stochastic(..).Slope();
```

**Comment by robroy1234** [comment]
Thanks Dave:

I guess you are pretty confident NinjaTrader is calculating wrong and you
are not?  What if I confirmed who is right/wrong on yahoo finance.  Would
you look into the issue if it turned out it was two against one?

**Comment by DaveSkender** [comment]
> Thanks Dave: I guess you are pretty confident NinjaTrader is calculating wrong and you are not? What if I confirmed who is right/wrong on yahoo finance. Would you look into the issue if it turned out it was two against one?

If you can show me 3 reputable systems that are not actually the same software underneath that are identical in results, or if you calculate with actual math showing the error, then I'll take a look.  I just need some compelling evidence to indicate the problem is in the library (and not elsewhere or in your own wrapper code).

You're not the first person to make these sorts of observations.  The track record of the problem being elsewhere is quite high, so yes, confidence based on empirical data.  That and the only way to convince you is to have someone analyze all of these external systems to explain the difference.  I'd rather spend my time on new features than testing other people's code.

If I were to guess, I'd say you're not using enough data to cover the warmup and convergence periods.

**Comment by DaveSkender** [comment]
And it’s not always about other systems being wrong, they just do something differently, like have a different data provider with slightly different quote prices.

**Comment by robroy1234** [comment]
I took a look at another later date in the series and it was a match with
ninjatrader for MACD, so I feel good about it.  Must have been what you
said.  Maybe I didn't have enough data early in the series and the numbers
off?  Normally I would think they would be null rather than incorrect.
Thanks.

**Comment by DaveSkender** [comment]
> I took a look at another later date in the series and it was a match with ninjatrader for MACD, so I feel good about it. Must have been what you said. Maybe I didn't have enough data early in the series and the numbers off? Normally I would think they would be null rather than incorrect. Thanks.

See #685 for a history and recommendations on how to handle warmup periods.

**Comment by robroy1234** [comment]
Dave, what data provider do you recommend?

**Comment by DaveSkender** [comment]
> Dave, what data provider do you recommend?

If your just goofing around and want something free, see https://github.com/DaveSkender/Stock.Indicators/discussions/579.  These are all equally good and bad.

**Comment by robroy1234** [comment]
Ok next questions.  I have a stochastic with 252 records in it starting on
6/21/2022.  I calculate slope on this and now I have 246 records starting
on 6/29/2022.  I'm looping through day by day (currentBar).  I want to get
the slope based on currentBar, but it doesn't match and I'm getting out of
index errors.  It seems to me that you would want empty records in the
beginning to pad out the slope List so the dates and indexes match up.

This doesn't seem to be working in a friendly way.

**Comment by DaveSkender** [comment]
> Ok next questions. I have a stochastic with 252 records in it starting on 6/21/2022. I calculate slope on this and now I have 246 records starting on 6/29/2022. I'm looping through day by day (currentBar). I want to get the slope based on currentBar, but it doesn't match and I'm getting out of index errors. It seems to me that you would want empty records in the beginning to pad out the slope List so the dates and indexes match up. This doesn't seem to be working in a friendly way.

I’ve made some adjustments in v2.0.2 to ensure chained indicators return the same length with additional prepended `null` padding, as you suggested.  Thanks for the feedback!  It’s a good idea, for consistency.

**Comment by robroy1234** [comment]
Great thanks.
