### ISSUE TITLE
Fewer records return from chained indicator

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#832]
> I have a stochastic with 252 records in it starting on 6/21/2022.  I calculate slope on this and now I have 246 records starting on 6/29/2022.  I'm looping through day by day (currentBar).  I want to get the slope based on currentBar, but it doesn't match and I'm getting out of index errors.  It seems to me that you would want empty records in the beginning to pad out the slope List so the dates and indexes match up.

> This doesn't seem to be working in a friendly way.

_Originally posted by @robroy1234 in https://github.com/DaveSkender/Stock.Indicators/issues/828#issuecomment-1163943421_

**Comment by DaveSkender** [comment]
I don't love this either as it is nice to be able to use an indexing approach with comparable results.  Let me explain the reason this happens, and then will propose some features or modifications we might try in the library to maintain collection length.

### Reason

When chaining, you are using the results of one indicator as the input to another.  As you may know, most indicators require a warmup period and often return `null` values in early periods of the results since they are incalculable.  If you are now re-using that data, you have to remove those `null` values so the second indicator can properly initialize.

Since the second indicator in the chain has no memory of the original `quotes` or pre-pruned initial `results` length, it can only return the length that it knows.

### Potential fixes

- Idea 1: figure out how to do the pruning of later in the algorithm (within each indicator, instead of as a pre-process), so the length is known + then add back the pruned dates.  This would add extra processes to __all__ indicators, making them slower, though not by much.  I don't think I'd be able to get this to work well.

- Idea 2: add a helper function `refilledResults = results.FillMatch(quote)` or `.FillMatch(results)` that would take the comparison `quotes` or `results` and match them to your results; if any dates are missing, add them as `null` values.

Any other ideas?

**Comment by robroy1234** [comment]
I will read what you wrote later. Without thinking fully about what you
wrote, can't you process it similar to a sma or Ema where the first values
in the series are null because there's not enough data to do the
calculation yet? For example, a 15 day moving average requires 15 days of
data to do the first calculation. I assume a slope is probably similar
based on look back days.

**Comment by DaveSkender** [comment]
For almost all indicators, you'll get a result collection back that's the same size as the quotes provided, so `quotes.GetSlope()`, for example, would do just that.  The length only gets smaller when you chain `quotes.GetEma().GetSlope()`.

**Comment by DaveSkender** [comment]
This was fixed in v2.0.2

**Comment by robroy1234** [comment]
Thanks, looks like I had 2.0.1.  Thought it gave me the latest when I
pulled it down a week ago, but i guess not.
