### ISSUE TITLE
Custom RSI indicator

### ISSUE THREAD

**Issue by RajeshDhalange** [DaveSkender/Stock.Indicators#84]
Hello Dave Skender
One more suggestion can you add a **Custom RSI indicator** which is a very demanding study indicator.
Reference : [https://www.stockfetcher.com/forums/Indicators/Custom-RSI-CRSI/112583](url)
To CRSI we can pass other indicator output too

**Comment by DaveSkender** [comment]
The only difference I see on this one is that you can select which OHLC element to evaluate.  Instead of creating an entirely new indicator, I think adding an optional parameter to the existing one is probably simpler, with Close as default.

**Comment by RajeshDhalange** [comment]
Not only OHLC but also other indicator output, like if I want to check OBV indicators pattern bcoz OBV not play in a range but with the help of CRSI we cant check range.

**Comment by DaveSkender** [comment]
Can elaborate a bit more?  I’m not clear about what you’re suggesting.  Are you suggesting a comparison or evaluation of output from multiple indicators?

**Comment by DaveSkender** [comment]
If you are trying to do an RSI of the OBV, like this:

https://medium.com/@robswc/this-is-what-happens-when-you-combine-the-obv-and-rsi-indicators-6616d991773d

then all you need to do is take the results of your OBV indicator, convert it to a synthetic history, then run it through the RSI indicator.

**Comment by RajeshDhalange** [comment]
> If you are trying to do an RSI of the OBV, like this:
> 
> https://medium.com/@robswc/this-is-what-happens-when-you-combine-the-obv-and-rsi-indicators-6616d991773d
> 
> then all you need to do is take the results of your OBV indicator, convert it to a synthetic `history`, then run it through the RSI indicator.

Yes exactly what I mean. simply instead of passing fixed parameter (OHLC) allow any input parameter i.e.   

**obvOutput = Indicator.GetObv(history);**   
**Indicator.GetRsi(_obvOutput _,14)**

The same can apply to other indicators where history is a parameter.

**Comment by DaveSkender** [comment]
I suppose we can add some overrides that would do that conversion for you where it makes sense.  My biggest concern is the quantity of possible permutations when we start doing combinations like this ... and figuring out which ones are reasonable.

For now, you can still do this, but will have to do that history conversion in your own wrapper code.

Any suggestions on which ones to implement first?

**Comment by RajeshDhalange** [comment]
> I suppose we can add some overrides that would do that conversion for you where it makes sense. My biggest concern is the quantity of possible permutations when we start doing combinations like this ... and figuring out which ones are reasonable.
> 
> For now, you can still do this, but will have to do that history conversion in your own wrapper code.
> 
> Any suggestions on which ones to implement first?

I think for now wrapper code is a better option as this takes minimum time and add override in the pipeline

**Comment by DaveSkender** [comment]
After some thought and feedback in the poll (#92), I've decided to not pursue adding these indicator combinations (AB#711) for the sake of keeping things simple.  With that said, you can still do this using the recommendations above.

I'll keep the OHLC modified RSI (AB#710) in the backlog icebox for a while to think about it some more.  I don't think many people would use OHL values instead of Close price -- it seems like it would only produce a somewhat more volatile result.  Using something like Stochastic RSI would probably be a better alternative.  This may fall into the "just because you can, doesn't mean you should" category.  The same recommendation above can apply in this case as well.
