### ISSUE TITLE
Various revisions

### ISSUE THREAD

**Issue by JGronholz** [DaveSkender/Stock.Indicators#842]
I must apologize for my fork being a mess, but wanted to share a few specific things with you:

"Update Slope.cs" - 14e0b85a311de9335a35f3da42bc1d7a1a732087
The slope indicator was ignoring the candlepart parameter. The error appears to have been a copy-and-paste bug but, tbh, I'm not sure I didn't create the issue, myself, after committing with upstream conflicts... Either way, it's fixed now.

"Reusable speed optimization mechanism" - 0ee1ca2ce7d1dd5da073a42cc273d93bd7bd7881
This commit added a mechanism to "resume" an RSI calculation, drastically increasing throughput. A similar mechanism could be implemented for many/most other indicators. This sounds like what you might be up to, in the streaming branch.

"Rebase MA types ~~and refactor RSI, Stoch, and StochRSI methods~~" - fcc099ef7707da0a755b962fe661b98c34afac18
This may be related to the ReusableResult interface that you're working on.
The changes to RSI, and Stoch, in this commit, are not relevant.

**Comment by DaveSkender** [comment]
Wow, I really like some of what you're showing here.  I'll take a closer look this weekend.

Some of this is related to my open streaming use cases, and I've found that it does operate faster, especially with larger quote histories.  I'll see if I can reuse some of this to make my approach better.  Thanks!

**Comment by DaveSkender** [comment]
> "Update Slope.cs" - [14e0b85](https://github.com/DaveSkender/Stock.Indicators/commit/14e0b85a311de9335a35f3da42bc1d7a1a732087) The slope indicator was ignoring the candlepart parameter. The error appears to have been a copy-and-paste bug but, tbh, I'm not sure I didn't create the issue, myself, after committing with upstream conflicts... Either way, it's fixed now.

This one is just in your Fork

**Comment by DaveSkender** [comment]
> "Reusable speed optimization mechanism" - [0ee1ca2](https://github.com/DaveSkender/Stock.Indicators/commit/0ee1ca2ce7d1dd5da073a42cc273d93bd7bd7881) This commit added a mechanism to "resume" an RSI calculation, drastically increasing throughput. A similar mechanism could be implemented for many/most other indicators. This sounds like what you might be up to, in the streaming branch.

I think I have this covered in my current work on #824.  One difference is that your example here assumes all users want to maintain a persistent state for indicators (and keep in-memory).  What I'm doing instead is keeping these separate so users can have both static time-series calls and persistent streaming use cases.  A streaming use case would initialize with `InitRsi(..)`, for example, to establish a baseline that can be updated with incremental quotes.

**Comment by DaveSkender** [comment]
> "Rebase MA types ~and refactor RSI, Stoch, and StochRSI methods~" - [fcc099e](https://github.com/DaveSkender/Stock.Indicators/commit/fcc099ef7707da0a755b962fe661b98c34afac18) This may be related to the ReusableResult interface that you're working on. The changes to RSI, and Stoch, in this commit, are not relevant.

I'm not entirely following here, but you're right that the new chainable indicators introduced in v2 that use `IReusableResult` can be used to do things like RSI on a moving average price.  The more invasive modifications to Stoch and Stoch RSI are more like custom indicators with different internals -- I'm not handling those scenarios yet.

If you're interested in pursuing those more invasive options, I'd recommend proposing each of those as separate "Idea" [discussions](https://github.com/DaveSkender/Stock.Indicators/discussions); or at least separate Issues or Pull Requests so we can address them independently.

**Comment by DaveSkender** [comment]
Thank you for contributing some nice ideas.  Much appreciated.
