### ISSUE TITLE
ADX getting NaN values

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#859]
### Discussed in https://github.com/DaveSkender/Stock.Indicators/discussions/857

<div type='discussions-op-text'>

<sup>Originally posted by **myalgomate** August  3, 2022</sup>
Hi,
I hope you are doing well here i am attaching the OHLC data and ADX data for 3 min time frame.
I am using Heiken Ashi data to calculate ADX with 14 periods.

I am getting Nan value.

[HeikinAshiData.csv](https://github.com/DaveSkender/Stock.Indicators/files/9248312/HeikinAshiData.csv)

[ADX.csv](https://github.com/DaveSkender/Stock.Indicators/files/9248314/ADX.csv)

</div>

**Comment by DaveSkender** [comment]
Ah, let me check it out.  That shouldn’t happen after v2.0.3.  We’d decided to return `null` instead of `NaN` in data error cases (see [notes](https://github.com/DaveSkender/Stock.Indicators/releases/tag/2.0.3)).

**Comment by DaveSkender** [comment]
@myalgomate is this happening intermittently or every time?  I'll take a closer look this weekend.

**Comment by myalgomate** [comment]
Hi,
It's happening with this data set only.

**Comment by DaveSkender** [comment]
> It's happening with this data set only.

I suspect you found a rare combination of prices — an edge case where it produces a `div/0` scenario that we don’t handle correctly.  Thanks for reporting.  I’ll add it to our test suite.

**Comment by myalgomate** [comment]
This is the original data on chart Symbol: NIFTY2280417150PE with 3 min Heiken Ashi

![image](https://user-images.githubusercontent.com/76814842/182770927-07e60270-c6d3-46b6-8795-1f8ed0324ee5.png)

**Comment by myalgomate** [comment]
Hi,
Let me know if it's corrected and which NuGet package version I should use the latest

**Comment by DaveSkender** [comment]
This was fixed in v2.1.2

**Comment by DaveSkender** [comment]
Since ADX is a cumulative rolling calculation, any error due to bad data will now produce `null` instead of `NaN`.  Once this occurs any following ADX values cannot be calculated without re-initializing.

I've taken a note to see if there are opportunities for it to re-initialize automatically in a correct and valid manner, but I have some deeper thinking to do on how to make that work properly, without some hack.
