### ISSUE TITLE
add McGinley Dynamic Indicator 

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#867]
### Discussed in https://github.com/DaveSkender/Stock.Indicators/discussions/866

<div type='discussions-op-text'>

<sup>Originally posted by **myalgomate** August 13, 2022</sup>

Can we add Mcginley Dynamic indicator to our library?

Reference: 
[McGinley Dynamic Indicator](https://www.investopedia.com/terms/m/mcginley-dynamic.asp) (Investopedia) and [related article](https://www.investopedia.com/articles/forex/09/mcginley-dynamic-indicator.asp)

![2F3E02F3-2165-47E8-A756-7AAFC06BB826](https://user-images.githubusercontent.com/8432125/185272215-97e901fb-64a1-4de7-9642-82a45991964c.jpeg)

see also [S&C Magazine article](http://technical.traders.com/archive/articlefinal.asp?file=%5CV28%5CC03%5C045TWOM.pdf)

**Comment by phivanloi** [comment]
yes

**Comment by myalgomate** [comment]
Hi @DaveSkender,

I hope you are doing well.
It would be very much helpful for me if you could share a tentative line for this indicator.

Regards,
Harsh

**Comment by ooples** [comment]
@DaveSkender Feel free to use my code if you want. I created a [Pine script](https://www.tradingview.com/script/Ru8W19kG-McGinley-Dynamic-Indicator/) that fixes the issue with the Mcginley Dynamic Indicator and I use that version in my indicator library as well

**Comment by DaveSkender** [comment]
> I hope you are doing well. It would be very much helpful for me if you could share a tentative line for this indicator.
> 
> Regards, Harsh

I’ll take a look this weekend.  I’m also trying to fix a bug with Renko; I usually prioritize bugs over features.  Can’t promise anything specific as I can really only spend a few hours a week on this project, currently.  Contributions welcome!

**Comment by DaveSkender** [comment]
> @DaveSkender Feel free to use my code if you want. I created a [Pine script](https://www.tradingview.com/script/Ru8W19kG-McGinley-Dynamic-Indicator/) that fixes the issue with the Mcginley Dynamic Indicator and I use that version in my indicator library as well

Thanks @ooples.  I was planning to simply work from the raw formula link above, but will take a peek at you TV script.  What was the issue that you fixed in your modified variant?

**Comment by ooples** [comment]
@DaveSkender It is possible that it was just a TV bug because I can't seem to replicate it atm but there were issues with the denominator value being less than 1 for some stocks and this causes the indicator to start producing NaN values so I made a change that forced a minimum of 1 for the denominator and that fixed the issue

**Comment by DaveSkender** [comment]
> @DaveSkender It is possible that it was just a TV bug because I can't seem to replicate it atm but there were issues with the denominator value being less than 1 for some stocks and this causes the indicator to start producing NaN values so I made a change that forced a minimum of 1 for the denominator and that fixed the issue

Ok, cool.  I'll keep an eye on that and make sure we're handling error cases properly, for funky data scenarios.

**Comment by DaveSkender** [comment]
This was implemented in v2.2.0
