### ISSUE TITLE
Performance Problems with Stochastic Oscilator

### ISSUE THREAD

**Issue by Jenscaasen** [DaveSkender/Stock.Indicators#88]
Hi,
i realy like your library, it works as described.

But i have a problem: when using the Stochastic Oscillator it upps my execution time by a lot. Going through 1000 stocks using other means of measurement takes 0.9 seconds (pretty fast machine and optimized code). Going through the same stocks using only the Stochastic Oscilator increases the time to 76 seconds.

This is how i call it:

```
 static public IEnumerable<StochResult> GetStochasticHistory(IEnumerable<Quote> history)
        {
            IEnumerable<StochResult> results = null;
            if (history.Count() > 8)
            {
                results = Indicator.GetStoch(history, 5, 3, 3);
            }
            return results;
        }
```

Measured with resharper, the "GetStoch" takes the time:
![image](https://user-images.githubusercontent.com/8245848/90321321-d4db4280-df48-11ea-9aca-f9ba8b1ffd3b.png)

Is there any way to optimize the runtime? Is there maybe a light version?

**Comment by DaveSkender** [comment]
[Slow] Stochastic is a rather tough one to optimize because it does several passes to both smooth the line and then product the signal line.  I'll take a closer look.  I can probably help out a bit by dropping the `IsIncreasing` calculation and output value -- I've been debating whether we should add these extra analyses anyway and keep it simpler.

Ref: https://github.com/DaveSkender/Stock.Indicators/blob/master/Indicators/Stochastic/Stoch.cs

If you're using the same `history` over and over again, it would also be better to [preclean it](https://github.com/DaveSkender/Stock.Indicators/blob/master/GUIDE.md#cleaning-history), so it would skip that part.

Are you using the Signal line?  If not, I can also have it skip that calculation if you set `signalPeriod` to 1.

**Comment by DaveSkender** [comment]
I've been able to get a couple of quick fixes in #90.  I was able to get about 30-40% speed improvement on `GetStoch`.
Removing `IsIncreasing` made no difference, so I left it in there for now.

Turns out when you use `LINQ`, doing min / max / average on `IEnumerable` is slower than converting `ToList` then performing those operations.  Who knew?  The conventional wisdom is to avoid `ToList`, so they say.  Learn something new every day.

**Comment by DaveSkender** [comment]
These changes are available in v0.9.5
@Jenscaasen, let me know how it goes.  If you can send that same performance scan, it would be helpful for apple-to-apple comparison.  I expect to see 25-40% improvement.

**Comment by Jenscaasen** [comment]
Thank you Dave for the quick reaction.
For better comparison, here is an even more dedicated measurement before changing anything, so the delay times are actually usefull to look up:
![image](https://user-images.githubusercontent.com/8245848/90337897-dd358b00-dfe5-11ea-99a6-c75c6a0e6f34.png)

(for reference: that are 1370 stocks with around 300 quotes each, and each quote the stoch gets recalculated, so overall 411.000 times the GetStoch is executed)

 I made the following changes to the code:

-Update to the lib to 0.9.5
-add the line "Cleaners.PrepareHistory(history);" before calling GetStoch
-run the code in Release mode

As a result, the time was reduced to 34 Seconds:
![image](https://user-images.githubusercontent.com/8245848/90338065-3d78fc80-dfe7-11ea-936f-4a1074e8b912.png)

By itself that is already an impressive performance boost, keeping in mind that there are 411000 complex calculations done in those 34 seconds.

I now realize that maybe my usecase is not suitable for complex calculations. I use genetic algoritms that try out different combinations on indicators, that means those 411.000 calculations are attempted multiple times a second. 

Thank you for the performance boost so far!

**Comment by Jenscaasen** [comment]
Update:
As i was writing the response i realized that there might not need to be the need to recalculate the stochastics every Quote, since newer quotes do not change the past stochastic results (right?). So its save to calculate the stock at once and then use the date as a guide to a specific stochresult. Doing this the time is reduced to 1.5 Seconds, which is totally acceptable. 
The problem was between keyboard and chair in this case, not your algorithms. Thank you again, looking forward to use more of your algorithms in the future.

**Comment by DaveSkender** [comment]
Good luck!  Sounds interesting.  I'm doing something similar in my trading system, but gave up on massive on-demand and parallel processing as I thought my computer would catch on fire ... the fan was blazing!  At some point, you just need a supercomputer :)

Personally, I've moved to more of a cache and queue model for analyses (strategy backtests in my case).

I'll continue to explore options to improve the performance of this library; though extreme forms of optimization might require more of a point solution with the removal of some basic features.

**Comment by Jenscaasen** [comment]
Thank you for confirming. I had machine learning in mind when rebuilding the PC, so the genetic algorithms are happy about that now :D what is a cache and queue model?

I gave the 3 parameters of Stoch as hyperparameters up for guessing to the algorithm too, and interesting enough: he chose some values that are outside the usual range as best parameters (something like 18 - 25 - 12 instead of 14 - 3 - 3). In the end the stochastic increased my overall success rate for 2020 stocks to 84%, where previous attempts stopped around 40%.

One very last offtopic question: are you aware of a community to share and discuss ideas on the topic?

**Comment by DaveSkender** [comment]
My cache and queue model: basically I do some up-front data collection, then add a message to a queue that gets processed in a somewhat more controlled manner.  It prevents me from asking too much of my compute power by regulating how much is happening all at once.  I'm using some of the serverless stuff on Azure, that I could, I theory, scale-out if needed.

Your findings on Stoch are interesting.  I guess it likes longer cycles, perhaps picking up more of the systemic movement of the market?

I'm sure there are 100s of blogs and communities out there where such discussions might be occurring, but a lot of them revolve around a common tool or commercial entity, like Quantopian.  I'm always open for chatting.  I have a [public Teams site](https://teams.microsoft.com/l/team/19%3a1b9209d6959e442694a28c91250ad708%40thread.skype/conversations?groupId=199d1962-4cdd-46fb-998b-7e24d0f225cf&tenantId=089fffad-8315-4180-8556-a1105149f47e) you or anyone is welcome to join for such discussions.
