### ISSUE TITLE
Some indicators have unavailable description

### ISSUE THREAD

**Issue by Jarek300** [DaveSkender/Stock.Indicators#888]
The page [indicators (daveskender.github.io/Stock.Indicators/indicators)](https://daveskender.github.io/Stock.Indicators/indicators/) has probably a few incorrect links:

[Directional Movement Index (DMI)](https://daveskender.github.io/Stock.Indicators/indicators/Adx/#content)
[KDJ Index](https://daveskender.github.io/Stock.Indicators/indicators/Stoch/#content)
[Least Squares Moving Average (LSMA)](https://daveskender.github.io/Stock.Indicators/indicators/Epma/#content)
[Modified Moving Average (MMA)](https://daveskender.github.io/Stock.Indicators/indicators/Smma/#content)
[Running Moving Average (RMA)](https://daveskender.github.io/Stock.Indicators/indicators/Smma/#content)
[HL2](https://daveskender.github.io/Stock.Indicators/indicators/BasicQuote/#content)
[HLC3](https://daveskender.github.io/Stock.Indicators/indicators/BasicQuote/#content)
[OC2](https://daveskender.github.io/Stock.Indicators/indicators/BasicQuote/#content)
[OHL3](https://daveskender.github.io/Stock.Indicators/indicators/BasicQuote/#content)
[OHLC4](https://daveskender.github.io/Stock.Indicators/indicators/BasicQuote/#content)
[Historical Volatility (HV)](https://daveskender.github.io/Stock.Indicators/indicators/StdDev/#content)
[Normalized Average True Range](https://daveskender.github.io/Stock.Indicators/indicators/Atr/#content)
[Rescaled Range Analysis](https://daveskender.github.io/Stock.Indicators/indicators/Hurst/#content)
[True Range (TR)](https://daveskender.github.io/Stock.Indicators/indicators/Atr/#content)
[Mean absolute deviation](https://daveskender.github.io/Stock.Indicators/indicators/Sma/#content)
[Mean absolute percentage error](https://daveskender.github.io/Stock.Indicators/indicators/Sma/#content)
[Mean square error](https://daveskender.github.io/Stock.Indicators/indicators/Sma/#content)
[R-Squared (Coefficient of Determination)](https://daveskender.github.io/Stock.Indicators/indicators/Correlation/#content)
[Z-Score](https://daveskender.github.io/Stock.Indicators/indicators/StdDev/#content)

**Comment by DaveSkender** [comment]
If you are only comparing the main page title, I can see why this might be confusing.

However, if you read those pages a bit more, you’ll see that they are correctly linked.  For example TR and ATR are described on the same page, DMI and ADX are the same indicator, etc.  

I’m open to suggestion, do you have a recommendation on how to address aliases better?

**Comment by Jarek300** [comment]
Perhaps a link to a specific part of a page? For example Z-Score is a link to StdDevResult table:


![image](https://user-images.githubusercontent.com/10242002/187390571-fd1b6ea0-2ccd-4be9-ac98-5e751be2c631.png)

**Comment by DaveSkender** [comment]
> Perhaps a link to a specific part of a page? For example Z-Score could be a link to the StdDevResult table:

That could work in some cases, tough I worry that loses some of the important context.  For this example, I like your idea here.

**Comment by DaveSkender** [comment]
I can also just be more deliberate about mentioning it in the intro description when linking like this.
