### ISSUE TITLE
GetParabolicSar have some proble

### ISSUE THREAD

**Issue by lap888** [DaveSkender/Stock.Indicators#899]
### the problem

After 15 minutes of sar, Binance shows that sar is higher than the current price. Our indicator calculates that sar is lower than the current price, which conflicts with Binance.

See [related discussion](https://github.com/DaveSkender/Stock.Indicators/discussions/245#discussioncomment-3645254)

**Comment by DaveSkender** [comment]
Checkout #801 and let me know if that helps.

Generally speaking, Binance (which using TradingView), is not a source of truth for me given that I can't debug whatever their problem is in most cases.

With that said, if you provide the Binance quote data and indicator parameters that you're using, I may be able to look at this at some point to help explain or troubleshoot.  I don't suspect a problem with the library yet.

**Comment by lap888** [comment]
I have seen it, but I can't find the answer I want.

**Comment by lap888** [comment]
I found that the sar of binance is more accurate.

**Comment by DaveSkender** [comment]
> I found that the sar of binance is more accurate.

Can you provide more information?  I’d like to help, but don’t yet know how you determined that it’s more accurate.  Please provide:

1. Binance quote data
2. Quote data you are providing to the library
3. Parameter values used in both

If you’re using different data sources, check to make sure the input quotes are the same.  That’s one potential source of differences.

**Comment by lap888** [comment]
hi,dave:
1. quote data url=>[https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data](https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data)
2. library => <PackageReference Include="Skender.Stock.Indicators" Version="2.1.0" />
3. GetParabolicSar(0.022,0.2)
thank you please me.

**Comment by lap888** [comment]
> hi,dave:
> 
> 1. quote data url=>https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data
> 2. library =>
> 3. GetParabolicSar(0.022,0.2)
>    thank you please me.

hi,dave:

quote data url=>https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data
library =>
GetParabolicSar(0.022,0.2)
thank you please me.

**Comment by lap888** [comment]
> > I found that the sar of binance is more accurate.
> 
> Can you provide more information? I’d like to help, but don’t yet know how you determined that it’s more accurate. Please provide:
> 
> 1. Binance quote data
> 2. Quote data you are providing to the library
> 3. Parameter values used in both
> 
> If you’re using different data sources, check to make sure the input quotes are the same. That’s one potential source of differences.

hi,dave:

quote data url=>https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data
library =>
GetParabolicSar(0.022,0.2)
thank you please me.

**Comment by DaveSkender** [comment]
Is this a BTCUSD export from Binance?  I’ll try to take a look at it this weekend.
If you also have the exported Binance Parabolic SAR data and parameters, that’d also be helpful, for comparison.

**Comment by lap888** [comment]
hi,dave:

quote data url=>[https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data](https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data)
library => PackageReference Include="Skender.Stock.Indicators" Version="2.1.0"
parameter=> GetParabolicSar(0.022,0.2)
thank you please me.

> > I found that the sar of binance is more accurate.
> 
> Can you provide more information? I’d like to help, but don’t yet know how you determined that it’s more accurate. Please provide:
> 
> 1. Binance quote data
> 2. Quote data you are providing to the library
> 3. Parameter values used in both
> 
> If you’re using different data sources, check to make sure the input quotes are the same. That’s one potential source of differences.

hi,dave:

quote data url=>[https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data](https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data)
library => PackageReference Include="Skender.Stock.Indicators" Version="2.1.0"
parameter=> GetParabolicSar(0.022,0.2)
thank you please me.

**Comment by lap888** [comment]
> > I found that the sar of binance is more accurate.
> 
> Can you provide more information? I’d like to help, but don’t yet know how you determined that it’s more accurate. Please provide:
> 
> 1. Binance quote data
> 2. Quote data you are providing to the library
> 3. Parameter values used in both
> 
> If you’re using different data sources, check to make sure the input quotes are the same. That’s one potential source of differences.

hi,dave:

quote data url=>[https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data](https://gist.githubusercontent.com/lap888/4eb6543bc6c39cb931da3cd8eb462ac6/raw/55e93b7d77c7aff7c580ce4712d7094a1bd76a0a/btc-15m-data)
library => PackageReference Include="Skender.Stock.Indicators" Version="2.1.0"
parameter=> GetParabolicSar(0.022,0.2)
thank you please me.

**Comment by lap888** [comment]
> Is this a BTCUSD export from Binance? I’ll try to take a look at it this weekend. If you also have the exported Binance Parabolic SAR data and parameters, that’d also be helpful, for comparison.

the kline data=>[https://gist.githubusercontent.com/lap888/a1bc5fe3fd61499b80f8d8d3ee167501/raw/6be1de6652a89aff74187288ae9f1e71b860a424/btc-15m-kline](https://gist.githubusercontent.com/lap888/a1bc5fe3fd61499b80f8d8d3ee167501/raw/6be1de6652a89aff74187288ae9f1e71b860a424/btc-15m-kline)

the sar data=>[https://gist.githubusercontent.com/lap888/e74fb9625c60f11ec28c94bacf9106f2/raw/09952f6b52e570cfcae92b72491c4c675bccb67c/btc-15m-sar](https://gist.githubusercontent.com/lap888/e74fb9625c60f11ec28c94bacf9106f2/raw/09952f6b52e570cfcae92b72491c4c675bccb67c/btc-15m-sar)

thank you.

**Comment by DaveSkender** [comment]
The data you've provided does not match what is present in the TradingView chart, so your results will be different.  If you can use the same data from Binance (TradingView) in the library and still have a problem, please share that quote data and let me know.  As of now, this is clearly a case of comparing two different quote histories and expecting the same results.

### Quotes you provided:
![image](https://user-images.githubusercontent.com/8432125/190878940-95891541-d9e2-4a30-b99b-fb94832433e1.png)

### Quotes on TradingView for this time period:
![image](https://user-images.githubusercontent.com/8432125/190878916-67023c60-f869-42be-885a-1b4b3e3d2814.png)

**Comment by lap888** [comment]
the new data：
quote data => [https://gist.githubusercontent.com/lap888/2584b91dbdb14f08b7800dc47f5d39cc/raw/51c4b522a7864689e4c3a877ec1c77f90a5de943/btc-15m-kline-new](https://gist.githubusercontent.com/lap888/2584b91dbdb14f08b7800dc47f5d39cc/raw/51c4b522a7864689e4c3a877ec1c77f90a5de943/btc-15m-kline-new)

sar => [https://gist.githubusercontent.com/lap888/39f716e5650fb6299e60938c9a416a90/raw/1e959236ea7e4802a3fcc1ac9b9a0d7d42a63993/btc-15m-sar-new](https://gist.githubusercontent.com/lap888/39f716e5650fb6299e60938c9a416a90/raw/1e959236ea7e4802a3fcc1ac9b9a0d7d42a63993/btc-15m-sar-new)

still have problem thank u.

**Comment by DaveSkender** [comment]
> still have problem thank u.

It looks like you've provided a) quote data from an unknown source and b) library response data
I'm not sure what to do with that information.

Can you please clarify or repeat the description of the problem you are having?

**Comment by lap888** [comment]
> > still have problem thank u.
> 
> It looks like you've provided a) quote data from an unknown source and b) library response data I'm not sure what to do with that information.
> 
> Can you please clarify or description of the problem you are having?

quote data from binance api. I did time formatting.
library from PackageReference Include="Skender.Stock.Indicators" Version="2.1.0".
I checked that the data source is OK.

**Comment by lap888** [comment]
> > still have problem thank u.
> 
> It looks like you've provided a) quote data from an unknown source and b) library response data I'm not sure what to do with that information.
> 
> Can you please clarify or description of the problem you are having?

I'm in Beijing, your time zone seemed to be eight hours behind mine. Every time when I was sleeping, I received your reply.

**Comment by lap888** [comment]
Inconsistency between sar indicators and currency security will cause losses to users.

**Comment by DaveSkender** [comment]
I'm still unable to reproduce the error and am not clear on why you think it's incorrect.  Inconsistencies can happen for many reasons, but I can't yet determine if there is an actual error in our library without more information.

**Comment by DaveSkender** [comment]
> But I found a new problem. Why can't I get the current K line sar? The latest sar is that of the previous K

What is a K line?
