### ISSUE TITLE
Is Directional Movement Index in the library? The docs imply it is, can't find a trace of it. 

### ISSUE THREAD

**Issue by Marcusbaker1** [DaveSkender/Stock.Indicators#943]
### the problem

Is DMI actually in the library? 
I see it referenced in the docs, but the docs point back to ADX
https://dotnet.stockindicators.dev/indicators/#content

Directional Movement Index (DMI)
Links to here: https://dotnet.stockindicators.dev/indicators/Adx/#content

I also do not see it in https://github.com/DaveSkender/Stock.Indicators/tree/main/src/a-d

### to reproduce

try to find the indicator in the library ;)

Error message(s):

none

**Comment by Marcusbaker1** [comment]
nevermind, I get it now! Thanks for this awesome lib!

**Comment by DaveSkender** [comment]
You're not the first to notice!  DMI is a component of ADX.  I could separate these to avoid confusion but just kept them together to avoid redundancy.
