### ISSUE TITLE
Exclude first TR value

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#947]
This would cause a lot of dependent indicator initialization period adjustments, including ATR.  See https://github.com/mihakralj/QuanTAlib/issues/12

**Comment by mihakralj** [comment]
I found the original page from the book that defines ATR. The first value of TR is not 0, it is high-low:

![image](https://user-images.githubusercontent.com/31756078/203706470-fdb00865-1129-4f28-8f37-62ee68317013.png)

**Comment by DaveSkender** [comment]
Yah, that’s the example I’m referring to in you related issue above.  I think this is an error by Wilder or simply that he’d considered prior Close, but is just not showing it. Other examples later in the book skip TR in the first period.

**Comment by mihakralj** [comment]
he put 1.40 as a TR for the first value, which is high-low (51.20-49.80)

**Comment by DaveSkender** [comment]
> he put 1.40 as a TR for the first value, which is high-low (51.20-49.80)

Yes, but this is only accurate if it is greater than the other two conditions:

- Absolute value of the most recent period's high minus the previous close
- Absolute value of the most recent period's low minus the previous close

It may be right.  Not enough info.

**Comment by mihakralj** [comment]
btw, on OBV indicator you are going in the opposite direction: while other libraries use the Volume of the first bar as a starting point, your library starts with 0 - and shifts the complete OBV chain down for the Volume[0]... Is there a source/reason for that?

**Comment by DaveSkender** [comment]
This was implemented in v2.4.1
