### ISSUE TITLE
Hurst exponent lookback too high

### ISSUE THREAD

**Issue by sshquack** [DaveSkender/Stock.Indicators#964]
### the problem

Hi thanks for creating this amazing library!  🙏 

I'm trying to use the Hurst exponent on my quotes. I understand that Hurst works optimally when it has 100+ lookback data points. But I want to tweak it for a lookback of 30 lag datapoints since I operate on larger time frames.

https://github.com/DaveSkender/Stock.Indicators/blob/35c46e66a15e7d289a4313f127cc53889bcc6ef4/src/e-k/Hurst/Hurst.Series.cs#L147-L150

- For example in Matlab, it is just a recommendation to have more than 50 data series https://www.mathworks.com/matlabcentral/fileexchange/30076-generalized-hurst-exponent but it not enforced. So once can choose as low as 20
- The Python hurst library enforces the 100 data series, but it has a `min_window` parameter of 10 https://github.com/Mottl/hurst/blob/5ca5005485a679e6ce11a2769c948915ae27b2da/hurst/__init__.py#L130-L131
- Here is a Simple hurst exponent from Trading View script that allows 30 data points https://www.tradingview.com/script/Sjf9iGCS-Hurst-Exponent-Simple-pig/

Could you please recommend if I should create my own version of if there is a way to disable the validation in this library?

**Comment by DaveSkender** [comment]
Let me look into it a bit to see if there was a good reason to keep it at 100.  We can probably reduce it if there’s no mathematical accuracy impacts, but not because the cool kids are doing it.  Some of those aren’t cool kids.

**Comment by DaveSkender** [comment]
> Could you please recommend if I should create my own version of if there is a way to disable the validation in this library?

If you want to Fork and [contribute to this library](https://dotnet.stockindicators.dev/contributing/#content) for public good, go ahead and do a pull request and I’ll merge it after my own research.

**Comment by DaveSkender** [comment]
> Hi @DaveSkender I have created a PR for your review #978 . Please research and let me know if it needs any changes.

Oh, nice.  Thank you for contributing!  I’ll take a look and try to review and merge early next week.
